ioccc-src/mkiocccentry

mkiocccentry.c

Applied to only one place in the code, should I continue further or you don't like how it's done?

Added character escaping function.

---

mkiocccentry-test.sh

I started a script for mkiocccentry tests.

mkiocccentry-test.sh

---

dbg.c
mkiocccentry.c

And inserted "vim shiftwidth" header.

Fixed some warnings from Clang's -Weverything.

---

mkiocccentry-test.sh

Passes the test with: 
```
work_dir="--test_work"
src_dir="--test_src"
```

Added -- to commands from "mkiocccentry-test.sh".

---

mkiocccentry.c

Add -o <output> option that writes the answers to the specified file (if
it does not already exist; it is not overwritten). Then one can do e.g.
`cat answers.txt | ./mkiocccentry ...' so that you don't have to
repeatedly type the same information like id, name, abstract etc.
There is probably room for clean-up here maybe particularly the calls to
warn/fpara/para and possibly modularising the writing to the output file
but this was done quickly for the idea (I make a lot of updates during
the contest so having this feature would be highly useful).

Make it easier to update existing entries

---

mkiocccentry-test.sh
mkiocccentry.c

The third commit fixes `mkiocccentry-test.sh` as well. Since I have provided logs for each of the commits I will not include them here but if it doesn't show up in git log (as happened once) I'll make a comment here.

Answers enhancements and fixes

---

Makefile
mkiocccentry-test.sh
mkiocccentry.c

Various fixes and enhancements mostly related to warnings wrt the Makefile but also a compilation error in CentOS as well as make it easier to update version of answers file (the test script has been updated for this).

Fixes and enhancements

---

mkiocccentry.1

Perhaps a man page should be added for the iocccsize tool too but I'll
leave this to someone else or perhaps another time. More examples could
be added but this gives a general idea of how to use it.

Add man page for mkiocccentry tool

---

txzchk.c

There are three new functions: parse_line() which is the driver of the
other two; it takes the line read in from the tar command (or text file)
(readline() in check_tarball() which calls parse_line()) and checks for
special bits first, warning if any are found. Then it determines if the
output is linux (6 fields) or BSD/macOS (9 fields) and calls the
appropriate function depending on this. The check comes down to the
second field having a '/' in it.
What I will probably do next is move the checks that are done when
parsing the line (not all tests can be done in the same location) into
their own function and call that function from both parse_linux_line()
and parse_bsd_line(). Either way make test should now succeed on both
linux and macOS (and hopefully BSD). After this clean up …

Add support for linux tar output format

---

Makefile
iocccsize.c
jauthchk.c
jinfochk.c
json.h
limit_ioccc.h
mkiocccentry.1
mkiocccentry.c
txzchk.c
util.c
util.h

As for adding my URLs to `txzchk.c`: Thank you again Landon for adding my name to txzchk.c! I'm honoured and privileged and I'm happy I could help!
I think the other commits will be of help for a good start on the json tools. 
`make depend` was fixed as well (it reported an error after one of the recent changes in the `Makefile`) and I also executed it (so the dependencies have been updated at the end of the file).

Initial JSON tool checkers + add my URLs in txzchk.c

---

jauthchk.1
jinfochk.1

When fixing the earlier commits I forgot to add back the man pages.

Readd jinfochk.1 and jauthchk.1

---

Makefile
jauthchk.c
jauthchk.h
jinfochk.c
jinfochk.h
json.c
json.h
limit_ioccc.h
mkiocccentry.c
mkiocccentry.h
txzchk.1

Much progress made! See the git log for information on some things that should be updated and for what is done (I did not list everything that's not done).

Many checks added to jinfochk and jauthchk

---

jauthchk.c
jinfochk.c
json.c
jstr-test.sh
test_JSON/good/info.json.good
version.h

There are many fixes in these commits. See the git log for details.

New version: fix JSON data type handling

---

Makefile
jauthchk.c
jauthchk.h
jinfochk.c
jinfochk.h
json.c
json.h
limit_ioccc.h
mkiocccentry.c
mkiocccentry.h
txzchk.c
txzchk.h
version.h

Bug fixes and var/struct/function renaming

---

README.md
jauthchk.c
jinfochk.1
jinfochk.c
jinfochk.h
json-test.sh
json.c
location.c
utf8_posix_map.c
version.h

Changed some references of !*p to *p != '\0' and similar things like
that. This is not so much for me but for others.

Finish jinfochk

---

README.md
mkiocccentry.c
mkiocccentry.h
txzchk.1

See commit log for details: now I really am done for the day with programming!

Minor fixes

---

mkiocccentry.c

There. Solved the problem.
Now I'm going for the day. More tomorrow I'm sure!

Sequenced exit codes

---

json.c
txzchk.c

Bug fixes, code simplifications

---

CHANGES.md
README.md
fnamchk.1
fnamchk.c
fnamchk.h
jauthchk.1
jauthchk.c
jauthchk.h
jinfochk.1
jinfochk.c
jinfochk.h
json.c
jstrdecode.c
jstrdecode.h
jstrencode.c
jstrencode.h
mkiocccentry.1
mkiocccentry.c
mkiocccentry.h
sanity.c
txzchk.1
txzchk.c
txzchk.h
version.h

Bug fixes, comments and README.md update

---

jauthchk.1
jauthchk.c
jauthchk.h
jinfochk.1
jinfochk.c
jinfochk.h
json.c
json.h
location.c
sanity.h
txzchk.c

See the git log for more details; heading off now.

Improve jwarn() + typo fixes

---

Makefile
dbg.c
fnamchk.1
fnamchk.c
fnamchk.h
jauthchk.1
jauthchk.c
jauthchk.h
jinfochk.1
jinfochk.c
jinfochk.h
json.c
json.codes
json.h
jstrdecode.c
jstrdecode.h
jstrencode.c
jstrencode.h
mkiocccentry.1
mkiocccentry.c
mkiocccentry.h
txzchk.1
txzchk.c
txzchk.h

This includes a new file that documents the current json warning codes. 
I've also fixed the debug, warn and error functions to use errno.
There were also typo fixes and maybe some other things.

Bug fixes and json warning codes updates

---

dbg.c
jauthchk.1
jauthchk.c
jauthchk.h
jinfochk.1
jinfochk.c
jinfochk.h
json.c
json.codes
json.h
json_err.codes
json_warn.codes
location.c
utf8_posix_map.c

See git log for details. I don't plan on doing anything more today with this repo.

JSON warning and error updates + clean up

---

.gitignore
Makefile

As requested I've renamed the local Makefile makefile.config to
makefile.local.

makefile.config -> makefile.local

---

Makefile
fnamchk.c
fnamchk.h
jauthchk.c
jinfochk.c
jparse.c
jparse.l
json.c
mkiocccentry.c
sanity.c

There were some other changes as well but that's the most of it.

Minor bug fixes in json scanner

---

Makefile
jauthchk.c
jinfochk.c
json.c
json.h
json_err.codes
json_warn.codes
txzchk.h

See the git log for commits 0204642, 0f72fcc, b8807a0 and 9efaaf4a7.
I'm not sure if this is all I'll do code wise today but most likely it is. I do hope to do more reading and if I do I might in fact make some changes but these changes are at least in. I still think I need to work out a proper struct/union (possibly more than one) before I can really start writing the parser but this will come later on (hopefully sooner than later)

JSON updates + minor rewording txzchk usage

---

jparse.tab.c
jparse.tab.ref.c
jparse.y
mkiocccentry.c
txzchk.c
utf8_posix_map.c
utf8_posix_map.h
utf8_test.c

It's not certain but I'm afraid this might be all I do today .. still trying to recover from the past few days (as of the day before yesterday).

Remove artefact from shell_cmd/pipe_open + typos

---

Makefile
jparse.l
jparse.ref.c
jparse.tab.ref.c
jparse.tab.ref.h
jparse.y
json.h

As for struct json see comment https://github.com/ioccc-src/mkiocccentry/issues/68#issuecomment-1092863593 at the jinfochk issue page.

Added struct json and typo fixes

---

Makefile
jparse.l
jparse.y
json.c
json_chk.c

The most significant commit is commit https://github.com/ioccc-src/mkiocccentry/commit/84accd31cde8a79eded5e0550b807839b72d1377. The others are minor (at least the others at the time of forming the pull request).

JSON parser updates and improvements

---

jparse.l
jparse.ref.c

Don't use '.*' regex for invalid token but only use '.'. The original
thought I had was not actually of use and this actually caused a syntax
error with unexpected tokens.

Fix commit ce8f576b

---

Makefile
dbg.c
dbg.h
jparse.1
jparse.tab.ref.c
jparse.y
txzchk.1
vermod.sh
version.h

Sorry for the confusion of the earlier pull requests. Wanted to clean it up. I'm off to do other things now as I'm having a difficult day. Going to take it easy but I can discuss things with you still.
Good day!

Minor fixes, txzchk.1 update and add jparse.1 #188

---

jparse.l
jparse.ref.c
json.c
json.h
txzchk.1
txzchk.c
verge.1

I'm afraid that this is almost certainly all I'll be doing today as I'm not feeling well again. I do hope to reply to the other thread today but so far it's not looking very probable. Hope you're having a nice sleep!
If I don't do anything more today I'm sure to do more tomorrow.

Various updates, fixes and improvements

---

json.c

And I'm heading off now. Good day!

Typo fixes in json.c

---

Makefile
run_bison.sh
run_flex.sh
version.h

sed -i 's/\<\(FLEX\|BISON\)_VERSION/MIN_\1_VERSION/g' *.{sh,h} Makefile
make build

Change (FLEX|BISON)_VERSION to MIN_(FLEX|BISON)_

---

jparse.l
jparse.ref.c
jparse.tab.ref.c
jparse.y

I decided to do it now to get it out of the way. Going back to other things now.

Minor bug fixes

---

jparse.h
jparse.l
jparse.ref.c
jparse.tab.ref.c
jparse.y
util.c

Maybe can do more in a bit. I hope so though I don't know what yet.

Minor updates and fixes in json parser

---

ioccc_test.sh
jparse.tab.ref.c
jparse.y
json_parse.c
jstr_test.sh
utf8_posix_map.c
utf8_posix_map.h

Possibly all I'll be doing today. I'm feeling some better but still want to be careful. Might end up doing more later but as of this time I don't plan on it (though that doesn't generally mean much).

Typo fixes and test added to ioccc_test.sh

---

jauthchk.1
jinfochk.1
jparse.1
json_entry.c
json_entry.h
json_err.codes
json_parse.c
json_parse.h

Perhaps the most interesting commit is https://github.com/ioccc-src/mkiocccentry/commit/6d1e2d8f948b0b32e9bef441ff2b116f8da62bcf:
errno errors in json_entry
There were a number of places in the file where errno was set to 0 prior
to a write operation but warn() was used instead of warnp().
There were some cases where errno was not set to 0 prior to using
warnp() for errors.
Also (a more subtle issue) in json_fprintf_str(): if json_putc() fails it
used warnp() but without setting errno to 0. But json_putc() only
returns false in two conditions: (0) when a NULL pointer is passed to it
(which means errno is not relevant unless we set it to EINVAL or
something like that ahead of time); and (1) when writing to the stream
fails. In the latter case warnp() is actually used. It's true that …

Various updates and fixes (including errno fixes)

---

dbg.c
json_parse.c
mkiocccentry.c
mkiocccentry.h
util.c
version.h

That's all I'll be doing for the day. Off to do something else.

Bug fix warn_on_err + typo fixes

---

.gitignore
Makefile.example
dbg.3
dbg.md
dbg_example.c

The most significant commit is commit https://github.com/ioccc-src/mkiocccentry/commit/c482f0fdcfe0f9b2d0bfb7fd9cf7c725defd076a. I will paste the log in the other thread to discuss.
I am aware of something in comments in dbg.c and probably dbg.md that should be addressed but those can come later. I want to make the other comment and then take a break. Probably these are the only commits I will make today.

First complete pass of dbg.3 + typo fixes

---

dbg.c

I am aware of some others but these are also in dbg.md and I'm saving
them for when I update that file as well.

Typo fix in dbg.c

---

Makefile
fnamchk.1
fnamchk.c
fnamchk.h
jparse.ref.c
jparse.tab.ref.c
txzchk.1
txzchk.c
txzchk.h
txzchk_test.sh
util.c

From earlier commits make parser was not done so the reference files
were not updated and committed.

txzchk_test.sh error message clean up & fixes + make parser

---

json_util.c
txzchk_test.sh

Leaving now. If this conflicts with what you're working on don't worry about it. I can always do it again or you can do it yourself - it's just one place.
Good day!

Typo fix in json_util.c

---

README.md
chkentry.c
chkentry.h
ioccc_test.sh
jparse.h
jparse.ref.c
jparse.tab.ref.c
jparse.tab.ref.h
jparse_test.sh
jstr_test.sh
mkiocccentry_test.sh
sorry.tm.ca.h
txzchk_test.sh

I am going to do something else now and I don't expect to return to this today. I'm not even sure I can get to the other comments today. We'll see but sorry if I cannot. Was a difficult night and I have a lot of other things on my mind.

Various updates and fixes

---

jparse_test.sh

In the usage message the -D was described twice.
Instead of cognitive behavioural modification (CBT) we now have script
behavioural modification (SBT) :) as follows: The script now reads by
default the test suite text file json_teststr.txt. To read from stdin
use the Unix de facto standard -.
There is a reason for the above change in functionality: often I mean to
run the default tests but it blocks as it reads from stdin. Then I
remember that it default reads from stdin. However the test cases we
have used as we were developing the parser are in json_teststr.txt so
this seems a better default file to use. Since - signifies stdin in many
tools we use that for reading of stdin instead of defaulting to stdin.

jparse_test.sh typo fix and behaviour modification

---

jparse.l
jparse.ref.c
jsemtblgen.c
util.c

That's all I'll be doing for now and probably until at least tomorrow. These were things I noticed by chance that I have enough energy to do (but barely enough). Going to rest now ... good day!

Minor fixes in jparse filename check + typo fix util.c

---

.gitignore
jparse.1
jsemtblgen.c
jsemtblgen.h
json_parse.c
mkiocccentry.c

Might end up doing more in a bit ... couldn't sleep but I think I might be able to at least lie down again now so I'll be doing that shortly. Hope you're having a nice sleep my friend!

Minor fixes and updates

---

jnum_chk.c
jnum_chk.h
jnum_gen.c
jnum_gen.h
jnum_header.c
jnum_test.c
jparse.1
jparse.h
jparse.l
jparse.ref.c
jparse.tab.ref.c
jparse.y
jparse_main.c
jparse_main.h
jsemtblgen.c
jsemtblgen.h
json_parse.c
json_parse.h
json_sem.h
json_util.c
json_util.h
jstrdecode.c
jstrdecode.h
jstrencode.c
jstrencode.h
txzchk.1

...and I'm afraid this is probably all I'll be able to do today. Busy day and unfortunately I woke up way too early today.
Hopefully tomorrow will be better and I can start making some real changes again.
Good day!

Typo fix / clarification in txzchk.1 DESCRIPTION + json parser comments updates

---

jsemcgen.sh

Don't hard code patch path in jsemcgen.sh

---

README.md
hostchk.sh
jsemcgen.sh
txzchk_test.sh

I not only don't expect to work on anything else here today but I plan not to. This might change of course but I don't think it's likely to happen. Going to try and sleep again.
Good day!

Bring README.md up to date and improve type -P usage in scripts

---

Makefile
jsemtblgen.c
jsemtblgen.h

I'm going to do something else now and I plan on not doing anything else here today. 
Hope you have a great day!

Makefile improvement (wrt invoking shell commands) and comments updates

---

dbg.3

In addition to the new functions from commit 7941077df have been added
to the man page I have moved the errno versions higher up and also made
a few fixes and clarifications.
The dbg.md file has to be updated still but this will very possibly not
be done today as it will take more time and thought.

Update dbg.3 for 7941077df functions + other fixes

---

chkentry.c
foo.c
foo.h
txzchk_test.sh

I do have more updates in mind but I wanted to commit these especially as there's a change in function name (and also variable name) so I don't want any conflicts.

Make foo more fubar

---

CHANGES.md

Just so you know I still have in mind to work on the debug documentation. I have a reminder set as well. I just have not felt up to much - and fubar has taken over as well.
This will be the final change I make today but hopefully tomorrow I can make some more changes. Hope you have a good night! Just taking it easy a bit longer and then will get ready to sleep. Good night!

Typo fixes in CHANGES.md

---

chk_validate.c
chk_validate.h
entry_util.h

You might find the following point of interest .. or perhaps not. I'll let you decide:
```git
Upon doing these I thought of another bool that could be added but I've
not done so because it would require modifying the test_JSON tree and
possibly other places too: a mismatch of all rule: namely that if
first_rule_is_all == true && found_all_rule == false there's a problem.
```
Anyway I hope these help. I'll next do more foo stuff though I might try going back to sleep first.

.info.json bool check functions code complete

---

foo.c

Without explaining the purpose of the original check I cannot explain
the fix so use your imagination and don't panic! :)

Fix warning on some systems in foo.c

---

foo.c
foo.h

You're not supposed to understand this :-)
Nevertheless if you can decipher the below you might be able to
understand this:
Co fsq eym awyd iw fsq xutt lbutt bnumh C'i eayjf.
Co fsq eym'b awyd iw fsq xutt lbutt bnumh C'i eayjf
Nqb twb'l rw nsmwlb: fsq eym'b awyd iw, eym fsq? C dudm'b bnumh ls.
:)
PS: foo is live wax.
Zsq dudm'b qmdwalbymd bnyb wubnwa dud fsq?

You're not supposed to understand this :-) 

---

entry_util.c
entry_util.h
foo.c
foo.h
mkiocccentry.c

The following functions were added:
test_github()
test_twitter()
test_url()
and the #if 0 .. #endif was removed for each one.
As well since test_affiliation() already existed (which I only
discovered after writing it) I removed the #if 0 .. #endif so that it's
validated too.
...there were also some comment fixes in foo. 
This is probably all I'll do today: very tired and going to try sleeping again. Later like I said I have a surgery follow-up and so I am probably done here.

Add three json test_ functions

---

Makefile

Fixed now. And now I really am doing something else for the day.

Run picky on oebxergfB.h

---

limit_ioccc.h
oebxergfB.h
util.c

Minor improvements to oebxergfB

---

jparse_test.sh
mkiocccentry.c
run_usage.8
util.c

When I changed jparse_test.sh to use -j instead of -p I did update the case statement but I forgot to update the getopts which would mean that the -j option would never have been seen. Thank you Landon for pointing this out to me!

Fix commit d9018f5505c2eb0b1fa77baa1ee9f73af70b3b7a

---

Makefile

Just like with commit 3d1c7f12be1853d01e182ff97ccdad985b274616 I have changed the command -v to type -P due to the possible problem I described in that commit.

Fix potential invocation errors in Makefile

---

util.c

The second and third checks on count increment seemed to be in error and this was fixed but with the caveat that I could be missing something. There still exists a problem with the summing part of the code but I'm not as certain what needs to be tested and what does not.
I added more information to all the calls to warn() to help identify any problems. In my changes (that cannot be committed until sum_and_count() is fixed) of txzchk.c which uses sum_and_count() one might see the following output, to give an idea of what it looks like:
Performing checks on tarball ...
test-0
txzchk: ./test_txzchk/good/entry.test-0.19248687209.txt size of 506 bytes OK
drwxr-xr-x  0 501    20          0 Feb 14 11:58 test-0/
-rw-r--r--  0 501    20        896 Feb 14 11:58 test-0/Makefile
-rw-r--r--  0 501 …

Improve (and fix in part) sum_and_check()

---

verge.c
verge.h

This will almost certainly be the last commit today.

Typo fix in verge.{h,c}

---

test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2-19944411114.txt.err
test_txzchk/bad/entry.test-10.9876543210.txt.err
txzchk_test.sh

This should resolve the two problems. Thanks for bringing them to my attention!

Bug and typo fix txzchk_test.sh + add missing error files

---

Makefile
bug_report.1
bug_report.sh
fnamchk.1
hostchk.1
hostchk.sh
jnum_chk.c
mkiocccentry.1

For the updates to the scripts I'll let the logs speak for themselves. There is an amusing set of notes in the scripts though that I'll share here:
```sh
#
#
```
A similar note is there in `bug_report.sh`. I noted this in one of the other threads.
There's also a reference to the old bug fixed:
```sh
#
```
I'll be taking a break now. Not sure if I'll do anything more today here. Pretty tired but I feel good about what I got done at least.

Additional man pages, man page fixes, shell script updates and fixes and typo fixes

---

jparse.l
jparse.ref.c
man/bug_report.1
man/chkentry.1
man/chkentry_test.8
man/dbg.3
man/have_timegm.8
man/hostchk.1
man/ioccc_test.8
man/jnum_chk.8
man/jnum_gen.8
man/jparse_test.8
man/jstr_test.8
man/limit_ioccc.8
man/mkiocccentry.1
man/mkiocccentry_test.8
man/run_bison.1
man/run_flex.1
man/run_usage.8
man/txzchk.1
man/txzchk_test.8
test/ioccc_test.sh
test/jstr_test.sh
test/mkiocccentry_test.sh
test/txzchk_test.sh
txzchk.c
utf8_posix_map.c

It's not certain if I'll be doing more or not. I'm hoping I can rest sometime soon but this does not seem very likely. I hope to do more in a while though.

Minor fixes (comments, man pages and typo fixes)

---

bug_report.sh
jparse.h
jparse.l
jparse.ref.c
jparse.tab.ref.c
jparse.y
jparse_main.c
jsemtblgen.c
run_usage.sh
test/chkentry_test.sh
test/ioccc_test.sh
test/jparse_test.sh
test/jstr_test.sh
test/txzchk_test.sh
vermod.sh

Several scripts under test did not show the version right in the case of bug_report.sh. Specifically I removed the 1>&2 from the echo of the version as with that there it showed a different and confusing output. For example:
0.5 2022-11-04
./test/txzchk_test.sh version
Notice the last two lines where the version by itself is printed on a line and then below it it just says the name of the script followed by version followed by a space and then newline. It now looks like:
./test/txzchk_test.sh version 0.5 2022-11-04
which is cleaner and clearer.
Updated bug_report.sh version. It now has a new function get_version_minimal which tries to get the version of a tool in a minimal way. Consider cat(1). Using -v is problematic because it blocks (it's an option and then expects input from stdin). …

Bug fixes and enhancements

---

CHANGES.md
README.md
jparse.l
jparse.lex.ref.h
jparse.md
jparse.ref.c
man/txzchk.1
man/verge.8
reset_tstamp.sh
test/jstr_test.sh
txzchk.c
txzchk.h

Very possibly all I'll end up doing today .. been having some difficult nights and slow and off days. I'll be taking a break soon as well but maybe I can do more later on.
I hope you're having a nice sleep!

Minor fixes and improvements

---

Makefile
dbg.md
dyn_array.md
man/dyn_array.3

The dyn_array.md file has yet to be written. There are at least two other things that I will briefly mention on GitHub as they should also be done before creating a separate repo but this is a good start.

Add dyn_array man page

---

Makefile
dyn_array/Makefile
dyn_array/dyn_test.h
jparse/README.md
utf8_posix_map.c

The commit https://github.com/ioccc-src/mkiocccentry/commit/0ec8f81843b9c7b317950b2656497f6b59317e7f should be obvious but the other one I'll include the log here even though it's easy enough to see:
Don't use ../dyn_array/dyn_array.h in dyn_test.h
This is because when it's a separate repo there's no guarantee that the
directory name will be dyn_array/ so it might actually fail to include
the right file.
Make depend.
As for the other things I was hoping to tackle today or start anyway - the man pages related issue. I was going to start but suddenly felt not up to it. I also have other things I need to do very soon so I probably won't get to that today. Maybe I can tomorrow. We shall see.

Various updates

---

Makefile
bug_report.sh
dbg/Makefile
jparse/test_jparse/Makefile
soup/Makefile
soup/man/man1/bug_report.1
test_ioccc/ioccc_test.sh
test_ioccc/prep.sh

This fixes a problem where make install would show:
test_jparse: make install starting
v -d -m 0775 /usr/local/bin
bash: line 1: v: command not found
make[2]: [install] Error 127 (ignored)
v -m 0555  jnum_chk /usr/local/bin
bash: line 1: v: command not found
make[2]: [install] Error 127 (ignored)
test_jparse: make install complete
It does not fix any other possible problem (that might or might not be in this subdirectory).

Various fixes, updates and enhancements

---

CHANGES.md
soup/Makefile
soup/man/man8/prep.8
test_ioccc/prep.sh

More should be added when more is done (some things I noted were done in the past few days after the change in version was made) or thought of (as I certainly did not note everything since the previous version).

Update CHANGES.md + new man page (for prep.sh)

---

bug_report.sh

New bug_report.sh version.
The script now collects all types commands that are needed as well as those that are optional. In other words it uses `type -a` on each command.
Additionally in the version check functions we don't report a problem if the command is not executable (don't call is_exec but instead is_exec_quiet). Instead it will go to what it always did - check for built in (though it might be in one of the functions this did not happen) - and then it will work on that. An important note here though is that for some tools like what(1) it does need a path. But doing it this way will allow for better collection of versions since most often it'll be a file anyway but in case it's not we might be able to obtain the version of the built-in (if there is one). The script could be …

Improve bug_report.sh

---

Makefile
dbg/Makefile
dyn_array/Makefile
jparse/Makefile
jparse/test_jparse/Makefile
soup/Makefile
test_ioccc/Makefile

Since it's no longer available at the original website I made a GitHub repo of the code. Now make picky refers to this instead.

Update picky url

---

.gitignore
Makefile
bug_report.sh
dbg/Makefile
dyn_array/Makefile
jparse/Makefile
jparse/test_jparse/Makefile
jparse/util.c
soup/Makefile
soup/oebxergfB.h
test_ioccc/Makefile
test_ioccc/test_txzchk/README.md
test_ioccc/test_txzchk/bad/entry.test-2.1922598666.txt
test_ioccc/test_txzchk/bad/entry.test-2.1922598666.txt.err

Please see the git log of the commits.
I don't expect to do anything else here today but I'm also not sure what else needs to be done aside from some man page issues that I should bring up.

Various fixes and enhancements

---

FAQ.md
README.md
soup/entry_util.c

As far as the README goes it now links to the FAQ under the new section 'Getting help'. It also links to the FAQ when explaining to report any issues found with bug_report.sh (under the testing section).
As far as the FAQ goes it has only a few items so far but this can be considered a work in progress.

Add FAQ.md, update README.md

---

FAQ.md
bug_report.sh
dyn_array/dyn_array.c
dyn_array/dyn_test.c
jparse/jparse.tab.ref.c
jparse/jparse.y
jparse/json_parse.c
jparse/man/man8/jsemtblgen.8
soup/man/man8/all_sem_ref.8
test_ioccc/chkentry_test.sh
test_ioccc/hostchk.sh

As for rewording: one should not try downloading and installing GNU tar at the GNU website as they'll very likely be unable to log in to it :-) Instead suggest that they can try downloading it FROM the website and then compile and install it so the tools may find it.

Various updates, fixes and enhancements

---

CHANGES.md
jparse/jsemcgen.sh
jparse/run_flex.sh
soup/all_sem_ref.sh
soup/run_usage.sh
test_ioccc/mkiocccentry_test.sh

With the exceptions noted on GitHub all error messages should be checked.
I did not check these as thoroughly as in the C files (and I very possibly missed some there too) but I did discover a number of issues that were fixed (or else noted on GitHub for discussion).

Check remaining script files for error messages

---

soup/man/man1/bug_report.1
soup/man/man1/chkentry.1
soup/man/man1/mkiocccentry.1
soup/man/man1/txzchk.1
test_ioccc/man/man1/fnamchk.1
test_ioccc/man/man8/chkentry_test.8
test_ioccc/man/man8/hostchk.8
test_ioccc/man/man8/ioccc_test.8
test_ioccc/man/man8/iocccsize_test.8
test_ioccc/man/man8/mkiocccentry_test.8
test_ioccc/man/man8/prep.8
test_ioccc/man/man8/txzchk_test.8
test_ioccc/man/man8/utf8_test.8
test_ioccc/static_analysis.md

With this commit I have looked over the man pages, made improvements and fixes and we should be good.
Only section 1 man pages under soup/ were touched because the section 8 man pages were fine.

Go through soup/man/man1 pages

---

FAQ.md
README.md

Added some links to make it easier to navigate.
Typo fixes and clarifications.
Explained (linked) to the zip file in case the user does not have git.
Reworded a few things here and there.

Improve FAQ further

---

jparse/test_jparse/test_JSON/bad/party-invalid-json.json
jparse/test_jparse/test_JSON/bad/party.json
soup/oebxergfB.h

The bad/party.json file had invalid json. Instead make a new file which has bad json and let the other one be invalid in semantics.
Some of this will have to be changed when the time comes for the jparse repo because it's too complex now (and this commit makes it more complex in a way). I was going to remove some of the files but as we're essentially at the point of freezing the code I wanted to get this in quickly and easily.

Minor updates to party.json files

---

remarks.example.md

Made things a bit clearer (I hope :-) ).

Reword sections section in remarks.example.md

---

.gitignore
jparse/Makefile
jparse/jprint.c
jparse/jprint.h

Nothing specific to this tool is parsed yet and nothing in that
category can be until more discussion is had.
This is just to get this part out of the way as I started it just to get 
the initial part done. Before we can continue working on the actual code 
of this tool we have to discuss the tool more including the usage
message. These options have the standard (for this repo) options but
nothing more.
Without -h no usage message is printed but this is because nothing is
done beyond parsing args. Nothing can be done until more is discussed in
detail.
It's possible that no further updates to these files will be done for 
some days at the very least for the above reasons.

Add initial INCOMPLETE command line parsing

---

soup/Makefile
soup/kitchen.sh

This is also for fun just to make the soup a bit more accessible. :-)

Add a soup kitchen :-)

---

soup/Makefile

This is just for fun. See the diff if you wish to know more!

Cook more soup :-)

---

soup/man/man1/location.1

This is not complete checked yet. I will look at it more thoroughly later hopefully today. Hopefully nothing else needs to be done and if that's the case the only commit might be a comment update.
The fixes were typos and formatting / styling.
--
Fix rest of location.1
I believe that at this time everything is good. There might be a few
things off / wrong but there were additional typo fixes and a minor
change in an example.
I am actually aware that the EXAMPLES section could probably be improved
formatting wise but since it looks fine it's probably okay and it might
be that I am remembering wrong: certainly it's the format I once had but
I believe I ended up changing it a bit later on. This is unneeded 
however.

Minor improvements and fixes to location.1

---

CHANGES.md
jparse/Makefile
jparse/jprint.c
jparse/jprint.h
jparse/jprint_util.c
jparse/jprint_util.h

At this time the tool is strictly being developed by me so I removed 
Landon from the comments. It's very possible at the end it will have
been worked on by both of us like jparse was and in which case he'll be
added back but I'd like to have it consistent with what is currently
going on.

Update jprint header comments

---

CHANGES.md
jparse/Makefile
jparse/jprint.c
jparse/jprint.h
jparse/jprint_util.c
jparse/jprint_util.h

There are currently no functions in the files but there will be in time
when I add routines that will be used by jprint itself.
Update Makefile and run make depend.

Add jprint_util.{h,c}

---

jparse/jprint.c
jparse/jprint_util.c
jparse/jprint_util.h

There currently is no code to check whether name or value or both was 
specified and just like with -t it might prove another way is better 
when I get to the point of working on the actual processing of the json 
to print.

Add code to parse jprint -p option

---

jparse/jprint.c
jparse/jprint_util.c
jparse/jprint_util.h

Should check for -p b as well as -p both.
Also added utility functions to test what bits are set and made use of 
them to display what will be printed, names, values or both.

Minor bug fix jprint -p option

---

jparse/jprint.c
jparse/jprint_util.c
jparse/jprint_util.h

The idea of any is that all bits are set, not that at least one is set.

Bug fix jprint_match_any()

---

CHANGES.md
jparse/jparse.h
jparse/jparse.l
jparse/jparse.lex.ref.h
jparse/jparse.ref.c
remarks.example.md

It's better to first copy the example file to a remarks.md file and
modify that file instead.

Clarify renaming of remarks.example.md for entries

---

jparse/jprint.c

... even though technically the tool is not done yet :-)

Add Jessica Noll comment to jprint.c main()

---

CHANGES.md
jparse/jprint.c
jparse/jprint.h
jparse/util.c
jparse/util.h
mkiocccentry.c
txzchk.c

As pointed out on GitHub as it's only for write or read mode it can be 
misleading to have a char const *mode. Thus it is now a boolean which 
states whether it should be write or read. The boolean is write_mode.

Change the way pipe_open() handles modes

---

CHANGES.md
soup/version.h

The CHANGES.md file notes the version change. The changes prompting the version update are already there.

Update txzchk version

---

CHANGES.md
jparse/jprint.c
jparse/jprint.h

Now prior to adding something to the matches list it will compare verify
that it's the same as the pattern requested. No regexp support yet.
Note that currently it only prints what is found and nothing else. It 
does not consider if only value should be printed and if it's a value 
for example. This can come later.

Partly implement pattern searching

---

jparse/jprint.c
jparse/test_jparse/jnum_gen.c
jparse/test_jparse/jnum_test.c

The problem was that when I added the boolean is_integer to the struct 
json_number I forgot about the jnum test array so the array was
incomplete.
Also fixed a typo in an earlier comment in the array (in the code to 
generate the file).

Fix make prep

---

CHANGES.md
jparse/jprint.c
jparse/jprint.h

More will have to be done at another time after some critical fixes
(due to a misunderstanding of the name_args use) are in place. These 
fixes will affect more than -E But -E will certainly be affected as 
well.

Implement as much as possible of jprint -E

---

README.md

Consistency wrt the file in question that it refers to (in the fix).

More consistency fixes in README.md

---

CHANGES.md
jparse/json_search.c

This file is currently in discussion and it will also be an important file to test functionality of the jprint tool.

Add test_jparse/test_json/good/42.json test file

---

CHANGES.md
jparse/json-README.md

This includes typos and other kinds of fixes as well as general improvements (like with formatting). More might be done in the near future but this is a good start.
Updated CHANGES.md noting this file and the fixes.

Fixes and improvements in the json-README.md file

---

CHANGES.md
jparse/README.md
jparse/json_parse.c
jparse/json_parse.h
jparse/json_sem.c
jparse/json_sem.h
jparse/json_util.c
jparse/man/man1/jparse.1
jparse/man/man3/jparse.3

Until the other tools can be further decided upon nothing else was added
in place of jprint. I will do that later.

Remove reference to jprint in jparse/README.md

---

CHANGES.md
jparse/README.md
jparse/json_parse.c
jparse/json_parse.h
jparse/json_sem.c
jparse/json_sem.h
jparse/json_util.c

The json readme was changed to json_README.md but the README.md file was
not updated.

Update jparse/README.md with correct file name

---

CHANGES.md
jparse/README.md
jparse/json_parse.c
jparse/json_parse.h
jparse/json_sem.c
jparse/json_sem.h
jparse/json_util.c
jparse/man/man1/jparse.1

Note that if a value cannot be converted but is valid it will report 
that it is valid JSON but will warn that conversion failed.

Update jparse.1 man page

---

CHANGES.md
jparse/README.md
jparse/json_parse.c
jparse/json_parse.h
jparse/json_sem.c
jparse/json_sem.h
jparse/json_util.c
jparse/man/man1/jparse.1
jparse/man/man3/jparse.3

Add note on JSON validity if conversion fails.

Update jparse.3 man page

---

CHANGES.md
jparse/json_util_README.md

I fixed typos and other issues. It is not a complete check. I only went up through the very beginning of the tool jnamval and I am sure I missed some things in the other tools too as I am very tired (and this is why I stopped). I hope that by tomorrow I can do a more thorough check.

Fixes in json_util_README.md

---

CHANGES.md
dbg/dbg.c
dbg/dbg.h
dbg/dbg_example.c
dbg/man/man3/dbg.3
dyn_array/Makefile
dyn_array/dyn_test.c
jparse/jparse.h
jparse/man/man1/jfmt.1
jparse/man/man1/jnamval.1
jparse/man/man1/jval.1
jparse/util.c
jparse/util.h

There is - how to say? - let's say a colourful update to the man pages 
as well to do with one of the -F styles.

Add -F fmt to jfmt, jval, jnamval man pages

---

soup/man/man1/chkentry.1
soup/man/man1/mkiocccentry.1

Though intended well it was decided that certain references are perhaps not a good idea to have after all.

Fix chkentry.1 and mkiocccentry.1

---

jparse/json_README.md

Only one file needed modification, it seemed: jparse/json_README.md.

Fix 'web site' to 'website'

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

.. though this certainly can be improved some still, the entire wording of the sentence. That will be considered later.
Thank you to @SirWumpus for indirectly making me aware of this: I know he hates templates so I feel like I should thank him specially :-)

Minor grammar improvement in issue templates

---

.github/workflows/test.yml
Makefile
test_ioccc/prep.sh

`prep.sh` to reference `$MAKE` in place of `make`.

GH-893 Fix root Makefile to pass`-m${MAKE}` to `prep.sh`; fix

---

.github/workflows/test.yml

It now installs checknr as the original did not have an exit code that would indicate failure if there was a problem until I added it (in the repo that was created by Landon for those who do not have access to it).

Minor improvement of workflows/test.yml

---

.github/workflows/test.yml
Makefile

A yank paste oversight caused this. Added sudo to the rest of the install commands that did not use sudo.

Add missing 'sudo' to GitHub workflow test.yml

---

dbg/Makefile
dyn_array/Makefile
jparse/Makefile
jparse/test_jparse/Makefile
soup/Makefile
test_ioccc/Makefile

Not sure how this did not get through as I could have sworn I did 'git commit -va' but apparently not.

Actually add picky link fix to Makefiles

---

FAQ.md

Typo fix div id== in FAQ.md

---

Makefile.example

Typo fix and change 'entry' to 'submission' (in two places).

Minor fixes in Makefile.example

---

jparse/jparse.l
jparse/jparse.ref.c

Typo fix in jparse.l

---

CHANGES.md
Makefile
Makefile.example
chkentry.c
chkentry.h
jparse/CHANGES.md
jparse/jparse_main.c
jparse/jsemtblgen.c
jparse/jstrdecode.c
jparse/jstrencode.c
jparse/test_jparse/jnum_chk.c
jparse/test_jparse/jnum_gen.c
jparse/test_jparse/pr_jparse_test.c
jparse/verge.c
jparse/version.h
mkiocccentry.c
mkiocccentry.h
soup/Makefile
soup/location.h
soup/location_main.c
soup/version.h
test_ioccc/Makefile
test_ioccc/fnamchk.c
test_ioccc/fnamchk.h
test_ioccc/utf8_test.c
txzchk.c
txzchk.h

It is actually used to silence the unknown warning option, not unknown
warnings.

Correct comment in Makefile.example for CUNKNOWN

---

jparse/man/man8/pr_jparse_test.8
jparse/man/man8/run_jparse_tests.8
jparse/test_jparse/run_jparse_tests.sh

This commit should fix the make test failing.

Add missing jparse files

---

soup/version.h

This was left out of the commit by mistake.

Update version.h for release

---

CHANGES.md
mkiocccentry.c
soup/version.h

The collect_topdir_files() now verifies that all three required files (prog.c, Makefile and remarks.md) are found.
The collect_topdir_files() also only records extra files if it's not an optional file or a required file.
Updated MKIOCCCENTRY_VERSION to "1.2.8 2025-01-29".

More work on #1070

---

CHANGES.md
soup/man/man1/mkiocccentry.1
soup/version.h

Other fixes (typos and formatting) were also applied but it is quite likely that this update is incomplete or has additional problems. These will be looked at (and if fixed if necessary) later.

Updated mkiocccentry.1 for newer syntax

---

CHANGES.md
bug_report.sh

In particular it did not check test_ioccc/gen_test_JSON.sh.

Fix bug_report.sh to check newer tool

---

CHANGES.md
jparse/CHANGES.md
jparse/util.c
jparse/util.h
jparse/version.h
mkiocccentry.c
mkiocccentry.h
soup/version.h

Sync jparse repo (https://github.com/xexyl/jparse/) to jparse/ for new
utility functions that will be useful for issue #1152.
Renamed append_unique_str() in mkiocccentry to append_unique_filename().
Sequenced exit codes.

New util functions from jparse

---

CHANGES.md
jparse/CHANGES.md
jparse/util.c
jparse/util.h
jparse/version.h
mkiocccentry.c
soup/version.h
test_ioccc/mkiocccentry_test.sh

This function finds a path in a paths array.
BTW: we do realise that a lot of the util functions in jparse have
nothing to do with JSON parsing but there is a historical reason behind
this.

Sync jparse with new util function for #1152

---

CHANGES.md
mkiocccentry.c
soup/man/man1/txzchk.1
soup/version.h

Fix scan_topdir() to not count dot files/directories against max allowed.
Updated MKIOCCCENTRY_VERSION to "2.0.4 2025-04-24".
Typo fix in txzchk.1.

Bug fix scan_topdir() count of max files

---

CHANGES.md
soup/version.h
test_ioccc/man/man8/test_file_util.8
test_ioccc/test_file_util.c

Fix exit codes in test_file_util.c and add test_file_util.8.

Fix exit codes in test_file_util.c

---

dbg/c_bool.h

It is, of course, Sméagol. Also added a bit more context to both quotes so that Landon does not have to :-)

Add missing diacritic in dbg/c_bool.h
