- mkiocccentry.c
This fixes the following compiler warning:
```
mkiocccentry.c:768:13: error: type qualifiers ignored on function return type [-Wignored-qualifiers]
static char const * const strnull(char const * const str);
^~~~~
```
> Fix compiler warning: type qualifiers ignored on function return type

- mkiocccentry.c
This fixes the following compiler warning:
```
mkiocccentry.c: In function ‘get_contest_id’:
mkiocccentry.c:3222:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
for (i = 0; i < len; ++i) {
^
```
> Fix signed/unsigned comparison in get_contest_id

- mkiocccentry.c
This fixes the following compiler warning:
```
mkiocccentry.c:5071:57: warning: unused parameter ‘entry_num’ [-Wunused-parameter]
get_author_info(struct info *infop, char *ioccc_id, int entry_num, struct author **author_set_p)
~~~~^~~~~~~~~
```
> Remove unused parameter "entry_num" from get_author_info()

- mkiocccentry.c
```
Now that we have formed the compressed tarball file, you
can remove the entry directory we have formed by executing:
rm -rf -- --123\ 456/test-1
If you are curious, you may examine the newly created compressed tarball
by running the following command:
(cd -- --123\ 456 && /bin/tar -Jtvf entry.test.1.1642655744.txz)
```
> Fixed remind_user() to print the correct commands.

- dbg.c
- mkiocccentry.c
Mostly fixes for passing string constants to a char* pointer and assigning a type to the result of malloc().
Now compiled by the C++ compiler without warnings: 
`make clobber all CC="g++"`
> The mkiocccentry code has been updated to higher C++ standards.

- mkiocccentry.c
TenDRA:
`  [C90 6.5.2]: The type 'suseconds_t' hasn't been declared.`
Better to avoid this type, it's uncommon. But `int` type is enough to hold microseconds.
Little C compiler:
`mkiocccentry.c:984: warning: missing return value`
Also needed for C89 compilers that don't know that exit() doesn't return.
Little C compiler:
```
mkiocccentry.c:1512: warning: overflow in converting constant expression from `int' to `unsigned long'
```
```c
static size_t
file_size(char const *path)
```
Here:
```c
return -1;
```
I did this:
```c
return ~(size_t)0;
```
I can't still fully compile with TenDRA due to the missing `ssize_t`. And linking with LCC is failed, but at least it compiles.
> Compatibility with other compilers.

- dbg.h
To compile with the `-std=gnu89` option.
> __func__ is not supported prior to C99

- mkiocccentry.c
The TenDRA compiler found another issue: 
`		      "    A–Z a–z 0–9 . _ - +",`
```
mkiocccentry.c, line 3868: Error:
[C90 6.1.3.4]: Character out of range.
```
And finally mkioccccentry is compiled with TenDRA but I can't link it properly.
> Changed "U+2013 EN DASH" to "U+002D HYPHEN-MINUS".

- mkiocccentry.c
There were some typos: ansewrs > answers.
When I added the answers file code I said to do `cat answers |
./mkiocccentry ...' but I should have (and knew better) specified to
just do `./mkiocccentry ...  < answers' and I've updated the strings in
the code to do this.
I've also added my name to the right of my handle (I have also added my
name to my profile so that hopefully this will not be a problem in the
future with commits). Thank you Landon for adding my name to the
comments in the first place - I really appreciate it!
> Typo fixes + remove useless use of cat for answers

- mkiocccentry.c
The problem with opening it first is that if the entry directory already exists and we have created the answers file then the answers file will have invalid data. Thus we open it after and then write the previously obtained information to the file.
> Answer file fixes

- mkiocccentry.c
Seems to be a typo - file name 'remarks_md' instead of 'remarks.md' in the tarball.
> Remarks in tarball fix

- mkiocccentry.c
When remarks.md could not be found the message referred to prog.c rather than remarks.md.
> Check remarks md typo

- mkiocccentry.c
If answer file specified and user ignores warnings write the
confirmation to the answers file.
When ignoring warnings and specifying the answers file we print a
warning that if they change this (fix the warnings or cause additional
warnings) that the results are likely to be incorrect and strongly
recommend that they re-enter the answers.
When showing how to use the answers file to update an entry warn them
that if they had ignored warnings and fixed them (or if new warnings are
triggered) then they are strongly recommended to re-enter the answers.
> Ignoring warnings with answer file fixes

- mkiocccentry.c
Bad file descriptor fix + warn on answers I/O 
If -i is specified you can get a bad file descriptor when confirming that the tarball is correct. I _thought_ I fixed this yesterday but there's another case: because I use freopen() to make stdin refer to the answers file the answers file has to be open until _after_ everything has been read (the confirmation of the tarball being correct comes from stdin or answers file so we can't close answers file until after this is done). Thus form the tarball before finalising the answers file.
I also added a counter of I/O errors on the answers file so we can warn the user that the file might not be correct.
Additionally I have added a warning for answers file even if no warnings were ignored, telling the user that if they do happen to add or change a …
> Minor answers file fixes

- mkiocccentry.c
The problem was in a comment: it had '–' instead of '-'.
> Fix high bit mkiocccentry

- mkiocccentry-test.sh
- mkiocccentry.c
1. The answers file contains no more (y/n) confirmations.
2. Reading the answers file doesn't ask for confirmation.
3. Reading the answers file doesn't repeat questions again, exits with an error if there were problems.
4. Added a marker for the end of answers file and checking for its presence.
5. Reading the answers file doesn't print hints.
6. Fixed the echo of the lines read from the answers file.
> Rewritten answers file writing/reading.

- mkiocccentry-test.sh
- mkiocccentry.c
If -a is specified and -A is NOT specified, warn the user if the answers
file already exists and ask them if they want to overwrite it. If they
say yes the answers file will be overwritten. If -A is specified or the
answers file does not already exist, the answers file is written to
whether or not it exists. -A implies -a (falls through in switch).
To make it easier to test add an option that allows the user to ignore
warnings. When this option -W is specified, ignore warnings once and
warn them that they're doing this, telling them how to fix this (in case
they did it by accident) and reminding them that the judges will not
ignore the warnings.
> Resolve issue #47 + add ignore warnings option

- .gitignore
- Makefile
This shows how it works. I have left out the rule_count.o because the
rule is special. Anyway when a new object file is added you can add it
to the OBJFILES variable and then run make depend. It uses awk but it
could be done with cut too (and probably should be fixed). I'm sure you
get the idea behind this and you can adapt it to your purposes if
necessary.
> Add make depend

- Makefile
- filenamechk.c
- mkiocccentry.1
- mkiocccentry.c
- txzchk.c
- util.c
- util.h
This is incomplete but the following changes were made for this commit.
It's a lot and if there are any problems (as is possible with such
changes) I will fix them. I've tested various tarballs (size, not
starting with a directory, having any special files etc.) but much could
be done still. Because there's a lot I'm going to make a comment in the
GitHub pull request. I'm sorry if for all the text there but I think
it's important! I'll fix any problems and I'll tackle the things not
completed another time (probably not today) if the judges (or someone
else) does not (there are a number of things left to do).
* mkiocccentry
Change usage message a bit: since the line was so long for the
synopsis I just have [options] and below the options are shown (as
they always were).
The tool now runs …
> Initial txzchk (issue #42)

- mkiocccentry.c
- util.h
Since the txzchk is always executed by mkiocccentry and since txzchk
prints out the contents of the tarball (since it has to parse the output
of tar) there's no need to explicitly invoke tar -tJvf. If the txzchk
tool is changed so it doesn't show the output of the tar listing then
this will have to be added back but this way it's no longer showing the
same information twice.
Typo fix(es).
> Remove redundant tarball listing output

- README.md
- fnamchk.1
- fnamchk.c
- iocccsize.1
- mkiocccentry.1
- mkiocccentry.c
- txzchk.1
- txzchk.c
- util.h
Man pages for the iocccsize(1), fnamchk(1) and txzchk(1) tools have been
added.
README.md now tells the user how to get more information and examples of
the tools by referring to the man pages (this includes mkiocccentry).
> Documentation updates + resolve several tarball issues in txzchk

- fnamchk.1
- fnamchk.c
- mkiocccentry.c
- txzchk.c
- util.c
- util.h
Many changes have been made. Several checks have been added but not all are listed below. The original push had these changes:
*   File sizes test added to txzchk
txzchk now tallies the size of all the files in the tarball and rounds it up to the next multiple of 1024 and warns if it's > MAX_DIR_KSIZE (also if it's < 0 - which is an error).
The function that rounds it up (round_to_multiple()) uses off_t as it's meant for file sizes but perhaps it could be changed to be more general (maybe long long).
*   Bump version in fnamchk and mkiocccentry
The change in filename format seems like a reason to update the version.
*   t_flag_used -> tar_flag_used (txzchk.c)
Previously only fnamchk bool had this format.
*   Make txz filename format consistent w/dir name
In anticipation of the txzchk …
> txzchk updates and fixes (including several checks added)

- txzchk.1
- txzchk.c
* Clean up and bug fix txzchk
Make warning messages more consistent in format: always show the tool's name and the txzpath. For example if there's no .info.json file it'll now show e.g.: 
Warning: txzchk: test.txz: no .info.json found
...whereas before it showed the function name and did not show the tarball path (in this case the fnamchk would issue an error). I feel that showing the utility name is more useful than 'check_tarball()'.  It's possible I have missed a warning. I tried to do the same with errors but I spent less time working on those as those are fatal and the program ends.
Removed the check_files() function; the tests are now all in check_tarball().
check_tarball() now issues a warning if fnamchk fails so that we can continue if it does fail (though currently it's the last …
> txzchk: Clean up, bug fixes and more tests added

- Makefile
- fnamchk.c
- limit_ioccc.h
- mkiocccentry.c
- txzchk.1
- txzchk.c
- util.c
This commit changes the C standard to C99. This in turn required that some feature test macros be enabled for CentOS but making these changes some other fixes had to be made for macOS. Since the Makefile is a dependency for the C files one should simply be able to pull these commits and recompile cleanly under both CentOS (and other Linux distributions) and macOS.
What this *does not fix* is a problem discovered yesterday where **tar(1)** has a different format under macOS/BSD and Linux. This will be fixed in the near future but for for now the `txzchk` will only succeed under macOS/BSD (which in turn means `mkiocccentry` will not work under Linux).
Sorry for this inconvenience! I hope to have this resolved today but I do not know when it will be other than it should be soon - in a day or …
> txzchk: portability, bug fixes and enhancements

- txzchk.1
- txzchk.c
I forgot to update `txzchk.1` after changing the filename format of the entry tarballs and I also had a typo in the comments in `txzchk.c`.
> Fix txzchk man page and typo fix in txzchk.c

- txzchk.c
Show all warnings _after_ parsing files. This is done by saving every
line to another linked list so that after the entire tarball contents
are displayed (via the readline() function) the checks are run on the
list of lines rather than each line as the line is read. There are still
some warnings that are shown before and after rounding the total file(s)
size to a 1024 multiple but I tried to move as many warnings together as
possible (some warnings have to be detected whilst parsing each line;
others can be done at the end and some fit better when parsing each
line).
Move duplicate code into separate functions.
I tried also to make warning messages a more consistent format but more
can be done in this department.
These changes have been tested under linux (CentOS) and macOS with the …
> Major clean up of txzchk - output + modularity

- iocccsize.1
- txzchk.1
- txzchk.c
I've updated the code to use `strtok_r`() instead of `strtok()`.
The self-deprecating humour in the man page fits me well as I enjoy laughing at myself.
I also removed some ambiguity in a variable name.
Changed the detection of `../` in paths a bit (now checks for just `..`) and fixed the dot file warning to say only 'file' if only one dot file was found (i.e. it used to say files but now it only shows that if > 1 found).
> txzchk: bug fixes and man page updates

- txzchk.c
The pointer saveptr should never be NULL but I've added it to the NULL
pointers check in both parse_bsd_line() and parse_linux_line() to be
complete (I forgot to do this when changing strtok() to strtok_r()).
> NULL pointer checks in txzchk.c

- fnamchk.1
- fnamchk.c
- iocccsize.1
- jauthchk.1
- jinfochk.1
- jinfochk.c
- txzchk.1
- txzchk.c
txzchk now checks for invalid chars in filenames (full path): that is it
now only allows fully POSIX portable chars (see mkiocccentry.c) as well
as '/' (since we check on the full path and not just the basename). I.e.
it checks on the field 'char *filename' in struct file. Note that as
soon as an invalid char is detected it breaks out of the loop (so a file
with two invalid chars only triggers one warning and issue).
txzchk also now checks for files called just '.'. These files are
counted as BOTH an invalidly named dot file AND a file called just '.'
(which is clearly abuse).
The show_txz_info() function has been updated for both of these changes.
As well instead of showing if there were any unacceptable dot files it
shows how many.
> Various updates and fixes

- Makefile
- jauthchk.1
- jinfochk.1
- json.h
- limit_ioccc.h
- mkiocccentry.c
- txzchk.1
- txzchk.c
- txzchk.h
- util.c
- util.h
Moved the file scope variables of `txzchk.c` to new file `txzchk.h`.
I also fixed the man pages for commit 29789c5b.
I forgot to note that I also ran `make depend` (this in turn added an additional dependency rule that was neglected in a more recent update).
> Various updates

- Makefile
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- jstrdecode.c
- jstrdecode.h
- mkiocccentry.c
- mkiocccentry.h
- txzchk.c
- txzchk.h
- util.h
Strict mode added (`mkiocccentry` uses this mode) to both `jinfochk` and `jauthchk` and the checks for the proper first and last char in the files are added.
There were some other clean-ups in the files as well (so far two commits to this pull request).
> jinfochk and jauthchk updates

- jauthchk.h
- jinfochk.h
I apologise for the long commit log: I made a lot of commits and some
had elaborate details (some important and others less important) and
unfortunately the logs did not carry over. I've removed my name, the
date and the commit id as GitHub does to make it as short as possible
and I also removed other text.
*   MAX_WINNER_HANDLE -> MAX_HANDLE
*   num_authors -> author_count
*   txzchk: Minor rewording message for !exists(tar)
*   jinfochk and jauthchk: Add formed_timestamp check
*   jinfochk/jauthchk: Add formed_timestamp_usec test
*   Add min_timestamp check to jinfochk and jauthchk
*   Add seqcexit rule to Makefile + run make seqcexit
Checks for seqcexit tool being installed and if it is it runs it on the
source files. Now whenever source files are updated one can simply run
make …
> Many updates to the tools

- Makefile
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- limit_ioccc.h
- mkiocccentry.c
- mkiocccentry.h
- txzchk.h
- version.h
With the exception of the answers file macros all _VERSION constants are
now in new file version.h and these are all exported into limit_ioccc.sh
(upon running make).
Change format of MKIOCCCENTRY_ANSWERS_VERSION (was
MKIOCCCENTRY_ANSWERS_VER): instead of year it now has IOCCC[0-9][0-9]
(i.e. the contest in question) or IOCCCMOCK (for mock contest) i.e. it
coincides with the #define IOCCC_CONTEST in limit_ioccc.h.
Update Makefile dependencies (due to adding version.h).
Fix handling of winner handle so that if the input is invalid it does
not abort but instead it prompts the user again (after telling them what
the problem is).
The #defines in mkiocccentry.c that are not related to the answers file
have been moved to mkiocccentry.h.
mkiocccentry.c: warn_rule2a_size() -> warn_rule_2a_size() …
> IOCCC tools versions mods + bug fix winner handles

- CHANGES.md
- Makefile
- dbg.c
- dbg.h
- fnamchk.1
- fnamchk.c
- fnamchk.h
- iocccsize-test.sh
- jauthchk.1
- jauthchk.c
- jauthchk.h
- jinfochk.1
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- jstrdecode.c
- jstrdecode.h
- jstrencode.c
- jstrencode.h
- limit_ioccc.h
- mkiocccentry.1
- mkiocccentry.c
- mkiocccentry.h
- txzchk.1
- txzchk.c
- txzchk.h
- util.c
- util.h
- version.h
I've not added any additional tests to the `jinfochk` and `jauthchk` tools but I think these updates are better to have. I think that I will probably get the tarball check added today but I'm not sure that if I do when it will be.
The `check_common_json_fields()` function has had its definition updated so that each tool can keep a log of problems to report at the end if quiet mode is not set. Note that this function does not yet add anything to the structs and some of it will very possibly change but this will take a bit more thought and time.
There were some typo fixes as well. I also actually thought of an additional test for `jinfochk` but I'll note that on that issue - in a few minutes I should expect (though I have to open the file again to make sure I am saying it right).
> Various updates, fixes and clean up

- jauthchk.c
- jinfochk.c
- json.c
- json.h
- mkiocccentry-test.sh
- mkiocccentry.c
- mkiocccentry.h
Move common JSON fields to json_common struct
That is to say that the fields that are written to .info.json and
.author.json are now in a common struct which is in both struct info and
struct author. Please do note that in mkiocccentry.c these still share
memory (or rather the info struct is used): previously in the functions
that refer to author and info structs it referenced e.g. info.ioccc_id
or infop->ioccc_id and the memory was only allocated in the info struct.
Now it's just info.common.ioccc_id or infop->common.ioccc_id instead.
This change is primarily for jinfochk and jauthchk in a future commit.
> Minor updates and fixes

- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- mkiocccentry.c
- mkiocccentry.h
- util.c
With commit abea8068f4f `mkiocccentry` no longer fails; the problem was with the way the `iocccsize_ver` variable was being assigned after the update to the `IOCCCSIZE_VERSION`. See the commit log for more details on this.
There were two typos in `util.c` as well. 
In a bit I hope to add some more changes though they might be minor too.
> Bug fixes, enhancements and typos

- README.md
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- mkiocccentry.c
- test_JSON/good/info.json.sorted
- util.c
- util.h
- version.h
The first commit cleans up commits 8c7c56f6 and a99522d5 (the former of which fixed some issues in the latter) and also makes more consistent names of variables and parameters.
Fix memory leaks. This includes referencing struct json_field's char *value instead of 'struct json_value *values' (which is what's used).  'value' has now been removed. 
In functions the parameter for the field name is now called 'name' and the parameter for the value is now called 'val'. In the functions (most of them - the ones that directly act on a struct json_field * and/or struct json_value *) the struct json_field * is called 'field' and the struct json_value * is called 'value'. Any 'char *' for the value is called 'val' (just like in the parameter). In the check_(info|author)_json() functions the variable …
> Complete all common json fields checks

- dbg.h
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- limit_ioccc.h
- mkiocccentry.c
- util.c
- util.h
- version.h
New version for these tools: 0.9 2022-02-27.
The `struct json_field` now has an `int field_type` which can be one of:
`JSON_NUMBER`, `JSON_BOOL`, `JSON_STRING`, `JSON_ARRAY`, `JSON_ARRAY_NUMBER`, `JSON_ARRAY_BOOL` or `JSON_ARRAY_STRING`. `JSON_NULL` also exists: this is only as an end of list marker. Note that the array versions are not
handled yet because arrays are not handled yet and the JSON_ARRAY_
macros might be changed but I needed to distinguish that they're part of
an array. The `JSON_STRING` and `JSON_ARRAY_STRING` are used to decide
whether or not to remove '"'s from the values (they're always removed
from the field names). It used to be done via a bunch of `strcmp() != 0`
results i.e. by a long list of names.
Added list for both .info.json and .author.json. All the fields in …
> Release new version of jinfochk and jauthchk

- fnamchk.1
- fnamchk.c
- fnamchk.h
- jauthchk.c
- jinfochk.c
- json.c
- json.h
- mkiocccentry.c
- mkiocccentry.h
- version.h
Add empty_override and rule 2a/2b size mismatches: If empty_override ==
true and either the rule 2a or 2b size != 0 then it's an issue; if false
and either rule 2a or 2b size == 0 it's an issue. This has also been
added to mkiocccentry: if either size is 0 then warn about empty prog.c.
The 'test_mode' field is now common to both .info.json and .author.json
and we verify test_mode consistency with fnamchk: that is to say that if
test_mode == true the tarball filename must start with "entry.test-"; if
false it must be a UUID. This is done by adding two options to fnamchk:
-u: if filename is a test mode filename then it's an error; -t: if
filename is a UUID filename it is an error.
I've bumped the version of fnamchk, jinfochk, jauthchk and mkiocccentry
for the above changes.
> jinfochk and jauthchk: additional checks added

- Makefile
- dbg.c
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json.c
- json.h
- location.c
- location.h
- mkiocccentry.c
- mkiocccentry.h
- sanity.c
- sanity.h
- txzchk.c
- txzchk.h
- utf8_posix_map.c
- utf8_posix_map.h
...because sometimes we're all a little insane, some of us are a lot
insane and code is often very insane. :-)
What this commit does is add sanity.{h,c} which has a new function:
ioccc_sanity_chk() which runs sanity checks on all the tables: the
location table, the UTF-8 POSIX map and the three JSON fields tables.
The jinfochk and jauthchk fields tables checks were moved to json.c
because the tools which have a sanity check function all run the new
ioccc_sanity_chk (because if something is not right in one or more of
the tables it suggests there's a problem in the toolkit) and jinfochk.c
and jauthchk.c obviously have main() each as well as verbosity_level.
> Add sanity

- .gitignore
- Makefile
- Makefile.example
- jauthchk.c
- jauthchk.h
- jinfochk.c
- jinfochk.h
- json-test.sh
- json.c
- location.h
- mkiocccentry-test.sh
- mkiocccentry.1
- mkiocccentry.c
- mkiocccentry.h
- sanity.c
- sanity.h
- test_JSON/author.json/good/default-author.json
- test_JSON/author.json/strict-bad/all.random.text
- test_JSON/author.json/strict-good/default-author.json
- txzchk.c
- txzchk.h
Make the new json test script work: due to some missing directories it would abort.
This commit also includes a quiet option for `mkiocccentry` which is used in `make test`. At first I thought it would be useful with the `ioccc_sanity_chk()` (now suffixed as `_chks()` as are all the others) but then I remembered the messages in that function are via `dbg()` so there's no need for a quiet mode there. Still seems like something that might be good to have so I kept it in.
See the git log for other fixes (typos).
> JSON tests, typo and other fixes and updates 

- jauthchk.c
- jinfochk.c
- json.c
- mkiocccentry.c
The common json field author_count is no longer common but instead only
in .author.json.
The common json field iocccsize_version is no longer common but instead
only in .info.json.
In the functions check_found_info_json_fields() and
check_common_json_fields() no longer allow missing fields to be not a
problem if test mode is enabled.  This was causing some tests to fail
and since the problematic fields are no longer common this should be
okay. Because not all fields are checked in jauthchk this was not done
so this is not a problem. The test option does still allow for different
versions of the tools to be there however.
This commit resolves a number of cases in the test_JSON directories
specific to jinfochk. As jauthchk does not yet parse the authors array
I'm not sure where the test …
> Various bug fixes and updates

- json-test.sh
- json.c
- json.h
/*
* jwarn - issue a JSON warning message
*
* given:
*      program name of program e.g. jinfochk, jauthchk etc.
*      name    name of function issuing the warning
*      code    warning code
*      line    line number of the calling file (__LINE__ macro)
*      fmt     format of the warning
*      ...     optional format args
*
* Example:
*
*      jwarn(program, __func__, 1, __LINE__, "unexpected foobar: %d", value);
*
* NOTE: We warn with extra newlines to help internal fault messages stand out.
*       Normally one should NOT include newlines in warn messages.
*/
void
jwarn(char const *program, char const *name, int code, int line, char const *fmt, ...)
{
}
This function will construct a warning message for JSON specific issues.
Example output:
jinfochk: …
> Write new function for json warnings: jwarn()

- json.h
The JSON_CODE_RESERVED_MAX + 9999 makes it > 9999 which is actually the
max.
> Fix JSON_CODE_MAX macro + typo fixes

- jparse.c
- jparse.h
If you want jparse to parse a string use -S <string>; anything left on
the command line will be assumed to be a file. Just like before - means
stdin. You can specify any file more than once and that includes stdin
(and just like before it takes care to not close stdin and makes sure to
clear the EOF and error flags).
If -S not used and there are no files specified (nothing left on the
command line) it is an error.
A note of interest on the subject of -S when used with -s: -s is
considered for the next -S arg only (for strings):
/*
* XXX Rather than having an option to disable strict mode so that
* in the same invocation we can test some strings in strict mode
* and some not strict after each string is parsed the strict mode
* is disabled so that so that another -s has to be specified …
> Simplify jparse wrt string versus file args

- jauthchk.1
- jauthchk.c
- jauthchk.h
- jinfochk.1
- jinfochk.h
- jparse.c
- jparse.h
- jstrdecode.c
- jstrdecode.h
The logic behind this is that string arg will be more commonly used and
more useful than strict mode and therefore although currently only one
tool has string arg (jparse) it feels more natural to have -s for string
and -S for strict mode. Discussing this with Landon we both had come to
this same though so the tools that have strict mode have been updated.
The two letters have been swapped in jparse.
Additionally the man pages for jinfochk and jauthchk were updated to
include this information (they did not yet have strict mode added to the
SYNOPSIS and OPTIONS sections).
> Make -S for strict and -s for string arg

- jinfochk.c
- jstr-test.sh
- mkiocccentry.c
I totally forgot that mkiocccentry uses -s for jinfochk and jauthchk.
The reason it didn't fail on jinfochk also is that I somehow forgot to
update the getopt() call and the switch case 's' to 'S' in main().
Typo fixes in mkiocccentry.c (make things a bit clearer).
> Fix commit 859116a8fb

- jparse.c
- jparse.l
- mkiocccentry-test.sh
- utf8_posix_map.c
This is what changed in the current commits:
- `mkiocccentry-test.sh` did not pass `shellcheck` again.
- Typos.
- Remove '.' (as in any char) in lexer grammar (`jparse.l`). 
- And I also updated some comments to reflect recent changes.
I might commit more but I'm unsure of this. I'm going to take a break and I hope to get back to reading after that. I'd like to get more into the book today but I'm unsure of how much I will do. In case you missed it Saturday I won't be able to do much except in the morning (so on replying to anything after about 11 or so in the morning most likely) but the rest of the week (by which I include Sunday) is fine.
Hope you're having a nice sleep and I hope things are resolved now!
> Minor fixes and comments updates

- jparse.c
- jparse.l
The errors in question are when the file couldn't be read in (i.e.
read_all() returns NULL) and if there are embedded NUL byte(s) in the
file.
I also increment num_errors in in these cases as well as some other
warnings that did not have this done already. This allows for the parser
to continue to the next file or string to actually make testing easier.
Sequenced exit codes (which did not end up needing to modify any other
files but it was done anyway).
> Convert two errors in jparse.l to warnings

- Makefile
- fnamchk.1
- fnamchk.c
- fnamchk.h
- jauthchk.1
- jauthchk.c
- jauthchk.h
- jinfochk.1
- jinfochk.c
- jinfochk.h
- jparse.tab.c
- jparse.y
- jstrdecode.c
- jstrdecode.h
- jstrencode.c
- jstrencode.h
- mkiocccentry.1
- mkiocccentry.c
- mkiocccentry.h
- txzchk.1
- txzchk.c
- txzchk.h
- version.h
As discussed with Landon at
https://github.com/ioccc-src/mkiocccentry/issues/132#issuecomment-1079967380
and
https://github.com/ioccc-src/mkiocccentry/issues/132#issuecomment-1079978436
I have removed the -T option from all the tools. This includes usage
messages, from all the getopt() calls and the man pages.
Because of this I've changed back the txzchk option -f to -T which is
slightly more clear as to what it's purpose is - the file is a text file
rather than just any file (as -f might suggest).
> Remove toolkit version, change txzchk -f to -T

- jint.c
free() was called if the pointer was == NULL rather than != NULL.
> Fix memory leak in jint.c

- jint.c
- jparse.c
- jparse.h
- jparse.l
- util.c
- util.h
The functions clearerr_or_fclose() and print_newline() have been moved
to util.c so that the definitions are not needed in the lexer.
The print_newline() function now takes a bool output_newline. I'm aware
of another file that prints a newline based on a bool but that file does
not use this routine. Whether util.c is the best file I don't know and
I'm more than fine with it elsewhere.
Sequenced exit codes.
> Minor clean up parser/lexer + make seqcexit

- Makefile
After splitting OBJFILES into two variables this broke the SRCFILES
variable which breaks make depend. As I put this in I'll explain how
the black magic of make depend works:
First of all the lines:
OBJFILES= dbg.o util.o mkiocccentry.o iocccsize.o fnamchk.o txzchk.o jauthchk.o jinfochk.o \
json.o jstrencode.o jstrdecode.o rule_count.o location.o sanity.o \
utf8_test.o jint.o jint.test.o jfloat.o jfloat.test.o verge.o
SPECIAL_OBJ= jparse.o jparse.tab.o utf8_posix_map.o
define object files that are generated by compiling the .c files. Next
the lines:
SRCFILES= $(patsubst %.o,%.c,$(OBJFILES))
SRCFILES+= $(patsubst %.o,%.c,$(SPECIAL_OBJ))
Create and append to the variable SRCFILES the .c files that are used to
create the object files (or more specifically it replaces all files in
the …
> Fix make depend

- Makefile
- jparse.h
- jparse.tab.c
- jparse.tab.ref.c
- jparse.y
- mkiocccentry.c
NOTE: For information I've discovered after the fact see comments below (comment https://github.com/ioccc-src/mkiocccentry/pull/145#issuecomment-1090423738).
There's a fun bug fix in the Makefile which I described in detail in the git log but which I am duplicating here. Actually I did a git pull and recommit as I figured out the second half of the puzzle and I wanted it in the git log as well. **THERE'S STILL A PROBLEM WITH `make seqcexit` FOLLOWED BY `make`!**
```git
Fix issue where make seqcexit updated parser/lexer
If one were to do:
make seqcexit
make seqcexit
They would see something like:
$ make seqcexit
seqcexit -c -- jparse.l jparse.y
seqcexit -- utf8_posix_map.c jparse.c jparse.tab.c dbg.c util.c mkiocccentry.c iocccsize.c fnamchk.c txzchk.c jauthchk.c jinfochk.c json.c …
```
> Makefile fixes + vfprintf usage in yyerror()

- json.h
- txzchk.1
- txzchk.c
- txzchk.h
In the second commit (commit a3e77b2cc) I include a long guide in how to write a test suite for `txzchk`. I'm duplicating it here so that it's in git log as well as here:
```git
commit a3e77b2cc3320d3bf3b99cb839d5c21b4d2ec7c2 (HEAD -> updates, origin/updates)
Author: Cody Boone Ferguson <53008573+xexyl@users.noreply.github.com>
Date:   Mon Apr 11 04:02:30 2022 -0700
Update txzchk.1 for commit f7338647
I did not specify how to write a test suite for txzchk here and although
I did on GitHub I'll duplicate it here with more information.
* How to write a test suite for txzchk
First of all we might have a directory for txzchk like for the JSON with
good and bad subdirectories (i.e. test_JSON) e.g. test_txz or
test_txzchk.
Then a script similar to json-test.sh but maybe txz-test.sh or maybe …
```
> Complete commit 6ba89af and typo fix in json.h

- bfok.sh
- jauthchk.c
- jinfochk.c
- jparse.h
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- mkiocccentry.c
- mkiocccentry.h
- sorry.tm.ca.h
- txzchk.c
- txzchk.h
- util.c
- util.h
- verge.c
- verge.h
- version.h
Specifically honor -> honour. There are two reasons but one was only
argued to plead my case of the other (yes this might be a bit
manipulative :( in the mind of some but my reasoning is below and I
think it's more than fair).
The first one is that I'm the one working on the parser and since I use
British English and it also goes against my honour to spell honour honor
:) and in fact the removal of 'u' in American English goes against my
very nature so I think it's fair to keep my honour by spelling it
honour not honor.
The second one is that honor is a US spelling so I argued that to truly
honour Canadians one should actually use their spelling! :)
Of course as a logophile and amateur philologist I will point out that
yes I do know that American English actually keeps some of the …
> Spelling fix in sorry.tm.ca.h + various updates

- txzchk.1
Backdated to 11 April 2022 when I added the -E option (the man page was
updated but I forgot to update the date).
> Fix date in txzchk.1

- Makefile
- fnamchk.c
- jfloat.c
- json.c
- json.h
- mkiocccentry.c
- rule_count.c
- utf8_posix_map.c
- util.c
- verge.c
- verge.h
- vermod.sh
The function floorl() requires -lm under CentOS 7 (the proper feature
test macros were already enabled although I have also changed
_XOPEN_SOURCE to be 600 up from 500: not sure if this is strictly
necessary but it doesn't hurt to have it at 600).
The Makefile has had some changes in the way warnings are handled
described below as thus:
First the warning flags -Wall -Wextra -Werror have been moved to the new
variable WARN_FLAGS. After this in WARN_FLAGS specific warnings have
been disabled in particular:
-Wno-unused-command-line-argument -Wno-poison-system-directories -Wno-unreachable-code-break -Wno-padded
The first one is important for macOS as after adding -lm to the CFLAGS
(via the standard LDFLAGS variable) we get that error for the fewer
objects that don't use -lm. Since many of the …
> Fix compilation under CentOS 7 + English updates

- jauthchk.c
- jinfochk.c
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- jparse.y
- json.c
- json.h
- mkiocccentry.c
The JTYPE_ enum in jparse.h have been renamed with the prefix JSON_ and
the JSON_ in the lexer and parser have been prefixed instead with JTYPE_
as nobody in their right mind will look at the parser or scanner code
but people will look at the other code. Actually nobody in their left
(wrong) mind would look at the generated code either because anyone who
does will have horrible nightmares about spaghetti code with very long
tentacles attached to the pasta that tries to grab them and pull them
into its mouth before consuming them with insatiable craving for humans
in its eyes. Okay you get the point: JTYPE_ is a better name for the
ugly, offensive code that can't be maintained whereas JSON_ is better
for code that can be maintained and is not ugly or offensive.
In the %union block in the …
> JSON parser + lexer updates and mkiocccentry fixes

- dyn_alloc_test.h
- fnamchk.h
- jauthchk.h
- jfloat.c
- jfloat.h
- jinfochk.h
- jint.c
- jint.h
- jparse.h
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- json.c
- jstrdecode.h
- jstrencode.h
- mkiocccentry.c
- mkiocccentry.h
- sorry.tm.ca.h
- txzchk.h
- utf8_posix_map.c
- util.c
- verge.h
For non-standard thru -> through:
As part of making this repo ready for public consumption (even though
the code is not ready for that :) ) I've made this change. Besides that
it triggers vim spelllocal highlight which shouldn't happen except
perhaps for American English[0] versus British English[0] (and other
Englishes[1] I guess): whereas the Judges and others use American
English I use British English but they keep my spelling and I do
likewise with theirs.
[0] Well OK 'should' is actually subjective: I would prefer it all be
British English but it is an international contest so we should all be
fair to everyone else with languages ... unless of course someone tries
putting in other computer languages (especially that ghastly C++ or any
references to it :) ).
[1] The astute reader who …
> Spelling updates and fix commit 463ec301

- Makefile
For the rules used by make prep that require certain tools always use
the form (when the tool is not found) of:
echo 'The seqcexit tool could not be found.' 1>&2; \
echo 'The seqcexit tool is required for this rule.'; 1>&2; \
Before this commit for seqcexit it said:
echo 'If you have not installed the seqcexit tool, then' 1>&2; \
echo 'you may not run this rule.'; 1>&2; \
which could be construed as somewhat negative. This same pattern was
used in the shellcheck command. For shellcheck I also suggested that one
could use their OS package manager to install it (after giving the
GitHub repo link).
I've not touched the reset_min_timestamp rule with this wording for the
rpl tool as this rule was made by the judges and only for the judges. I
did however make a typo fix in the comments above …
> Minor update to Makefile

- dyn_array.h
- jparse.l
- jparse.ref.c
Extra '(' in a few examples in comment dyn_array.h.
Change 'true: ' prefix in jparse.l to 'boolean: '. This happened as an
artefact of when I had separate tokens for true and false.
> Typo fixes in dyn_array.h and jparse.l

- Makefile
- dyn_array.c
- jfloat.c
- jfloat.test.c
- jint.c
- jint.test.c
- jparse.l
- jparse.ref.c
- json.c
- json.h
- mkiocccentry.c
- prep.sh
- utf8_posix_map.c
- util.c
- verge.c
As for commit https://github.com/ioccc-src/mkiocccentry/commit/45d9d324d6a910f88eb128b5d47b484af9958862 I am pointing out the log here for those who need a laugh and who are easily amused:
```
Typo fix in prep.sh
Not to criticise (atefr all, we all mkae tpyos :) ) but just point it out
out because it's an ironic and funny typo: FALL -> FAIL which was a FAIL
itself :)
```
And yes: there are several intentional typos in the commit log! Bonus points to those who can find them all.
> Several updates including typos

- Makefile
- jauthchk.c
- jinfochk.c
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- jparse.y
- json.c
- json.h
- json_chk.c
- json_chk.h
- sanity.c
- txzchk.h
I'd like in particular to point out commit 1f4dd7687a69fc:
```
Older bison and POSIX Yacc compatibility
Change parse.error 'detailed' to 'verbose' to support older versions of
bison. Now bison version 3.0.4 will work which means CentOS 7 bison can
actually generate the file. The change in verbosity does not seem to
make a difference for me so this is a worthwhile change. Please note the
version has not yet been updated in version.h.
Now passes -Wyacc which has been added to the Makefile. This is done by
making a couple changes described below.
POSIX Yacc does not support the %empty directive so we use /* empty */
instead.
POSIX Yacc does not support the %define directive but it does support
the -D option. Thus instead of having in jparse.y (where detailed is now
verbose as described …
```
> txzchk fixes + several JSON updates

- Makefile
- jparse.h
If sorry.tm.ca.h or jparse.h is updated both flex and bison will
regenerate the files. This is because if jparse.h is updated it might be
a change in prototypes (or new functions or variables or something else)
and if sorry.tm.ca.h is updated we want the updated apology to be
injected into the files again.
> Makefile dependency updates for flex and bison

- jparse.h
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- jparse.y
In other words if someone passes invalid input to jparse like:
./jparse -s '++'
they would see:
debug[0]: Calling parse_json_string("++"):
debug[0]: *** BEGIN PARSE:
'
++
'
Starting parse
Entering state 0
Stack now 0
Reading a token
--(end of buffer or a NUL)
--accepting rule at line 145 ("++")
JSON parser error on line 1: invalid input: ++
Next token is token JSON_INVALID_TOKEN ()
LAC: initial context established for JSON_INVALID_TOKEN
LAC: checking lookahead JSON_INVALID_TOKEN: R1 G8 Err
Constructing syntax error message
LAC: checking lookahead "end of file": R1 G8 S23
LAC: checking lookahead "{": S1
LAC: checking lookahead "}": R1 G8 Err
LAC: checking lookahead "[": S2
LAC: checking lookahead "]": R1 G8 Err
LAC: checking lookahead ",": R1 G8 Err
LAC: checking lookahead ":": R1 G8 Err …
> Lexer and parser now deal with invalid input

- Makefile
- jstrdecode.1
- jstrdecode.c
- jstrdecode.h
- jstrencode.1
- jstrencode.c
- jstrencode.h
- prep.sh
- run_flex.sh
The tools now will parse `-` at the command line as `stdin`. NOTE: exactly `-`: doing `-5` still counts as a string though of course one would have to first pass `--`.
Added man pages for these two tools and updated Makefile to install these (added to the man page targets variable).
> JSON (and other) updates (including man pages)

- jparse.h
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- reset_tstamp.sh
- run_bison.sh
- run_flex.sh
- txzchk.c
- util.c
- util.h
As for commit https://github.com/ioccc-src/mkiocccentry/pull/184/commits/231c53e7e58f4ded5a1751d18dcd8ddce7938b21:
```
Noted that the ugly_ prefix is a satire for the IOCCC and if it's moved
to a new repo for a JSON parser (as was suggested to me) after the IOCCC
has used it I might well remove the prefix even though we all think the
generated code by flex and bison is in fact ugly. Perhaps this should be
moved further up in the comment but this can come at another time.
```
I think that should be noted here so all can see. 
I don't plan on doing any more today but am sure to do more tomorrow.
> Various updates and fixes (including typos)

- verge.c
In allocate_vers() a string was strdup()d but prior to returning the
copy was not freed.
> Fix memory leak in verge.c

- jparse.1
Had \fb instead of \fB for flex(1) and bison(1).
In SEE ALSO section add reference to flex(1) and bison(1) as well.
> Minor fixes (typos) and updates in jparse.1

- jparse.tab.ref.c
- jparse.y
- json.c
- json.h
Add function 'char const *json_element_name(enum element_type
json_type)' to print the element type by name rather than a number.
Add to the conversion functions a call (in some cases more than one
call) to dbg() with new debug value (#defined in json.h as DBG_NONE)
JSON_DBG_LEVEL so that I can see the type in each call to the conversion
functions. The reason I named it JSON_DBG_LEVEL is so that it's easy to
remove once this is no longer needed (alternatively it could be changed
to some other debug value if it's worth keeping).
Add action to json_member so that it actually parses a member (it does
NOT add to the parse tree as currently there is no parse tree) or a list
of members. The diff in jparse.y looks like:
-json_member:	JSON_STRING JSON_COLON json_element
+json_member:	JSON_STRING …
> Update JSON parser including one action added

- jparse.h
- jparse.tab.ref.c
- jparse.y
- json.c
- util.c
- util.h
In the parse_json_bool() function I accidentally had checked the
converted bool of 'null' in the union. This has been fixed.
Add several more actions to the parser. In particular:
json_value:       json_object
| json_array
| JSON_STRING { $$ = *parse_json_string(ugly_text, &tree); }
| json_number
| JSON_TRUE { $$ = *parse_json_bool(ugly_text, &tree); }
| JSON_FALSE { $$ = *parse_json_bool(ugly_text, &tree); }
| JSON_NULL { $$ = *parse_json_null(ugly_text, &tree); }
;
json_number:    JSON_NUMBER { $$ = *parse_json_number(ugly_text, &tree); }
;
In parse_json_null() check if converted is true. If not it's an error;
else print a debug statement saying it was converted.
In parse_json_number() it still does not print the number or check for
conversion. Part of this is there's more to check and …
> Bug fix and add JSON parser actions + JSON tree

- .gitignore
- Makefile
- jparse.1
- jparse.h
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- json.c
- json.h
- json_chk.c
- json_util.c
- json_util.h
- run_bison.sh
- run_flex.sh
- sanity.c
- util.c
The json_member action now uses json_conv_member(). This means that the
parse_json_member() now is:
struct json *parse_json_member(struct json *name, struct json *value, struct json *ast);
and the action looks like:
+json_member:	JSON_STRING JSON_COLON json_element { $$ = *parse_json_member(&$1, &$3, &tree); }
which in the generated code is:
{ yyval = *parse_json_member(&yyvsp[-2], &yyvsp[0], &tree); }
Override default debug level in jparse to be DBG_MED and change
JSON_DBG_LEVEL to DBG_MED. I have the idea that a json debug function
could be added that is prefixed with JSON instead of dbg and which might
take a different variable which would mean that the other tools won't be
chatty but jparse can be. However for now this is not done. I made it
DBG_MED as I don't want too much …
> JSON parser updates

- .gitignore
- Makefile
Add new variable BISON_FLAGS:
#
#
#
#
#
#
BISON_FLAGS = -Werror --report all -Wcounterexamples -Wmidrule-values \
-Wprecedence -Wdeprecated -d
This enables some additional warnings and turns them into errors. Note
that -d is also in the call to run_bison.sh after the BISON_FLAGS is
referenced because it's possible to override the BISON_FLAGS in
makefile.local (as I do in fact on the macOS for html output).
Add new variable FLEX_FLAGS:
#
FLEX_FLAGS = -d -8
Add jparse.html to be deleted in make clobber.
Add jparse.html to .gitignore.
> JSON parser Makefile updates

- jparse.h
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- jstrdecode.1
- jstrencode.1
If a string (or a file) has a NUL byte not within a string it is a
syntax error in the parser and parsing will not continue. If however a
NUL byte is in a string it will be accepted.
The way this works is quite simple. The string regex already allowed for
NUL bytes and the default rule (that we define later) in the lexer does
not allow for NUL bytes. Now in the lexer we have the length of each
pattern that matched in ugly_leng. This variable does not exist in bison
though so for each string matched we set ugly_length to ugly_leng
(perhaps this should always be done?). Now the parse_json_string()
function has changed to be:
/* parse_json_string - parse a json string
*
* given:
*
*	string	    - the text that triggered the action
*	len	    - length of the string to convert (important for NUL …
> JSON parser now allows NUL bytes - resolve #208

- prep.sh
Presumably a yank paste error: the help for -o option only referred to
bison but for prep.sh it's both bison and flex (the same message is in
run_bison.sh and the flex counterpart is in run_flex.sh).
Also:
-    echo "$0: ERROR: Makefile file not found: $MAKEFILE" 1>&2
+    echo "$0: ERROR: Makefile not found: $MAKEFILE" 1>&2
> Typo fixes in prep.sh

- dbg.c
- json_parse.h
- json_util.h
In some functions the check if output was allowed was done prior to
checking if that bool should be set to false. I believe this was done
when I moved the check up to make it not do anything at all if it was
not allowed
> Add back bug fix in commit cab3cd304ff

- Makefile
- jauthchk.c
- jinfochk.c
- jparse.tab.ref.c
- jparse.y
- json_chk.c
Primarily an unhandled field was added to the check function (the no-comment one). There was also a problem in that the Makefile did not have for jinfochk and jauthchk the dependency `json_chk.o` so updating `json_chk.c` would not result in recompilation of those tools. 
Those are the bugs I refer to but perhaps JSON should itself be called a bug or maybe a virus. Probably not as I don't know that I would call it efficient (but I might be a tad bit biased). Well ... just something to think about maybe.
> Various bug fixes and updates to do with json

- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.tab.ref.h
- jparse.y
- json_parse.c
- json_parse.h
- json_util.c
An interesting thing I pointed out in commit https://github.com/ioccc-src/mkiocccentry/commit/3c65ca0106c91bcd0b9181ebe4377105eee12e52:
```
Rename 'JSON_INVALID_TOKEN' to be just 'token' for better error
messages:
[...]
* Now if bison has an actual reference to the token value itself this would be
* ideal to pass to the error message but if it does I'm unaware of it and
* unfortunately UGLY_ABORT is specific to bison and not in flex. That being
* said it does have a feature for more custom error functions and this can be
* looked into.
*/
```
I will look into this functionality more. It doesn't appear to have the token itself but it might have something better than what we have here. I'm not sure. I will look into it in the near future. I'd like to do it now but I'm much too tired for …
> Add hack for better json error messages + minor comment updates

- jnum_chk.h
- json_chk.c
- json_chk.h
- json_parse.c
- json_parse.h
- json_util.c
- json_util.h
It referred to the old 'struct number' which quite a while back was
changed to 'struct json_number'. The rest of jnum_chk already have
'struct json_number'.
> Typo (struct name) fix in jnum_chk usage message

- run_bison.sh
- run_flex.sh
For some reason when doing a git commit --amend to fix something else
both run_bison.sh and run_flex.sh did not commit properly. Thus some of
the '..'s still were in the files.
> Fix commit e9225c8c684b6d

- dbg.c
In functions
printf_usage
vprintf_usage
fprintf_usage
vfprintf_usage
if exit code >= 0 it would call exit() if usage messages were allowed
rather than not allowed (in other words if usage_output_allowed == true
instead of == false). Thus doing e.g.:
./foo -h
would print nothing.
> Fix -h mode when exit code >= 0

- dbg.c
- dbg.md
- jnum_chk.c
- txzchk.c
- txzchk.h
The changes are for consistency (but see below) as well as typo fixes
and trying to reduce the length of the text (removing some redundancy).
Some points of interest:
In most cases the texts describing what happens if fmt == NULL or name
== NULL have been moved to the top of the dbg.md to remove duplicate
text. The only difference between each instance was the function name
but I used 'foo' and put below that 'foo' is whichever function is being
used.
Reworded some things to help make said things clearer.
Added missing words in some sentences.
In the example code I changed the VERSION_STRING to be the current date
(or actually 1 June as I made that change yesterday). This is because
the date referred to 2021 and many improvements have been made since
2021. Maybe when everything is in …
> Many dbg.{c,md} updates and bug fixes (dbg.c, txzchk.c) + other fixes and updates

- txzchk.c
In this place it was if fnamchk fails but errno is not relevant there:
fnamchk will return an error code but it's not a C function error.
Instead use warn() rather than warnp().
> Fix warnp call in txzchk where errno is not valid

- test_txzchk/bad/entry.test-0.1652598667.txt
- test_txzchk/bad/entry.test-2.1652598667.txt
- test_txzchk/bad/entry.test-3.1652598667.txt
- test_txzchk/bad/entry.test-4.1652598667.txt
- test_txzchk/bad/entry.test-5.1652598667.txt
Specifically the following files were removed:
$ for i in $(grep 'tar fvt' *|cut -f1 -d:); do git rm "${i}"; done
rm 'test_txzchk/bad/entry.test-0.1652598667.txt'
rm 'test_txzchk/bad/entry.test-2.1652598667.txt'
rm 'test_txzchk/bad/entry.test-3.1652598667.txt'
rm 'test_txzchk/bad/entry.test-4.1652598667.txt'
rm 'test_txzchk/bad/entry.test-5.1652598667.txt'
The reason being is that they only had:
$ grep 'tar fvt' *
entry.test-0.1652598667.txt:tar fvt entry.test-0.1644411114.txz
entry.test-2.1652598667.txt:tar fvt entry.test-2.1644411114.txz
entry.test-3.1652598667.txt:tar fvt entry.test-3.1644411114.txz
entry.test-4.1652598667.txt:tar fvt entry.test-4.1644411114.txz
entry.test-5.1652598667.txt:tar fvt entry.test-5.1644411114.txz
in them. How this happened I cannot say entirely but they are …
> Remove invalid files in test_txzchk/bad

- run_bison.sh
- run_flex.sh
- util.h
In run_bison.sh and run_flex.sh in add_sorry it said 'expects 1 args'
instead of 'arg'.
Why not change it to 'one'? It might be up to debate but the reason I
did not is because $# shows digits and not words so I left it as digits
too to keep it matching.
In util.h: I moved a comment above
-/* for string to int functions */
-#define LLONG_MAX_BASE10_DIGITS (19)
+#define LLONG_MAX_BASE10_DIGITS (19) /* for string to int functions */
because there are lines right below that are not related to string to
int but might be confused as being related in some way or another.
> Typo fixes

- Makefile
- hostchk.sh
- json_util.c
Currently it does not parse options and there are only two checks:
Checks that tar with the required options is available.
Test compiles a C program with each of the system header files included
in all the C and header files in the repo. See below for how this is
done.
Rather than have to update the script each time a header file is removed
or added it uses a pipeline of grep and sort in a while read loop. The
pipeline itself is:
grep -h -o '#include.*<.*>' ./*.c ./*.h|sort -u
and the top and bottom of the loop is:
while read -r h; do
...
done < <(grep -h -o '#include.*<.*>' ./*.c ./*.h|sort -u)
But instead of creating a C file for each header file used we use some
magic with the compiler and stdin. Thus the part that compiles each test
file is:
printf "%s\n%s\n" "$h" "int main(void){ …
> Add initial hostchk.sh

- jauthchk.c
- jcodechk.sh
- jinfochk.c
- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- jparse_test.sh
- json_test.sh
- mkiocccentry.c
- prep.sh
- reset_tstamp.sh
- run_bison.sh
- run_flex.sh
- txzchk.c
- txzchk_test.sh
- vermod.sh
- version.h
There were many references to 'not a file' after first determining that
it actually exists and is a file (should have read 'not a regular
file').
In json_test.sh a variable was called EXIT_CODE_FIlE instead of
EXIT_CODE_FILE (if it's not obvious at a quick glance the former name
had a lower case ell).
The C files:
jauthchk.c
jinfochk.c
mkiocccentry.c
txzchk.c
All referred to 'not a file' after first determining that said path is
in fact a file (again here should have read 'not a regular file' as they
now do).
In vermod.sh change the name (in comment) to vermod.sh (was vermod).
There might have been some other fixes as well but the above are the
significant ones.
> Many typo fixes in scripts and source files

- .gitignore
- ioccc_test.sh
- utf8_posix_map.c
According to OED lambda is:
the eleventh letter of the Greek alphabet (Λ, λ), transliterated as ‘l’.
so it should be capital (or uncial; majuscule) and lower case (or
minuscule) ELL and not y and n. Thus:
-    { "\xc6\x9b", "y" , -1, -1},	/*  U+019B - ƛ - LATIN SMALL LETTER LAMBDA WITH STROKE */
+    { "\xc6\x9b", "l" , -1, -1},	/*  U+019B - ƛ - LATIN SMALL LETTER LAMBDA WITH STROKE */
-    { "\xce\x9b", "n" , -1, -1},	/*  U+039B - Λ - GREEK CAPITAL LETTER LAMDA */
+    { "\xce\x9b", "L" , -1, -1},	/*  U+039B - Λ - GREEK CAPITAL LETTER LAMBDA */
-    { "\xce\xbb", "y" , -1, -1},	/*  U+03BB - λ - GREEK SMALL LETTER LAMDA */
+    { "\xce\xbb", "l" , -1, -1},	/*  U+03BB - λ - GREEK SMALL LETTER LAMBDA */
Now the question of the Latin version. As best I could find this is not
even actually a …
> Change lambda transliterations in utf8_posix_map.c + update .gitignore

- jparse.tab.ref.c
- jparse.y
- jparse_main.c
- jparse_main.h
- utf8_posix_map.c
- version.h
I forgot that the UTF-8 POSIX map has to have all lower case letters and
so the Greek capital letter lambda has to have a lower case
transliteration (L -> l).
This commit fixes both mkiocccentry and txzchk which broke due to the
hmap being invalid.
> Fix commit 8855d2ff12b7054f74fd846cd5e88d332df03b3a + typos/formatting in version.h

- dyn_array.c
This completes the TODO item in commit
976f311d84dc9124da8fdeed6abd35f3ae935136:
TODO: Make use of dbg_allowed(level) in dyn_array.c to reduce the
CPU impact of dbg() calls that have lots of args.
> Use dbg_allowed() throughout dyn_array.c

- mkiocccentry.c
The chkentry flag is -C but the comment said the old -J.
Running chkentry does not indirectly show the user the contents of the
tarball; that's txzchk which is called in form_tarball().
> Minor typo fixes in mkiocccentry.c

- chkentry.1
- dbg.3
- dbg.c
- dbg_example.c
- entry_util.c
- jparse.1
- jsemtblgen.c
- json_parse.h
- json_sem.h
- sanity.c
Update the dbg.3 man page to refer to the functions added in commit
09b6563:
extern void snmsg(char *str, size_t size, char const *fmt, ...)
extern void sndbg(char *str, size_t size, int level, char const *fmt, ...);
extern void snwarn(char *str, size_t size, char const *name, char const *fmt, ...);
extern void snwarnp(char *str, size_t size, char const *name, char const *fmt, ...);
extern void snwerr(int error_code, char *str, size_t size, char const *name, char const *fmt, ...);
extern void snwerrp(int error_code, char *str, size_t size, char const *name, char const *fmt, ...);
Additionally the dbg_example.c file with a message for each output that
says what the next line should print so that the user can verify it's
correct. It does not make use of the sn functions above (though I did …
> dbg interface documentation + jparse.1 updates

- jparse.h
- jparse_main.c
- jsemtblgen.c
- verge.c
- version.h
See the rationale of updating the json parser version in commit https://github.com/ioccc-src/mkiocccentry/commit/96b58dd3090f199babf28d1507869004e6e5dcc6:
The previous version was 0.8 2022-06-12 but since that time the parser
was code complete (this happened with commit
7f8d7411c9157fe314a237a3eec5c404a4de3c79 at Thu Jun 23 15:41:54 2022
-0700) which by itself warrants a new version. That should be 0.9
2022-06-23.
But earlier this morning (00:48:17) some additional changes were made
and since the jparse version was updated at this point I believe it
worth updating the json parser version as well. The two now are the same
version: 0.10 2022-07-03.
As for the other fix it's simply so the user can see the usage message as is done with other tools.
I might end up doing more later on today but …
> Update JSON parser version + use usage() with wrong number of args

- chkentry.1
- dbg.3
The typos had to do with formatting and now make checknr passes.
> Typo fixes in chkentry.1 and dbg.3

- txzchk.c
- txzchk.h
Instead of saying 'All checks passed.' txzchk now says 'No feathers
found in tarball.' if all tests pass.
Also the top comment now says more about what txzchk actually does (it
did not even state that it verifies that the tarball conforms to the
IOCCC tarball rules as it now does) but having fun with the idea of the
problems checked for are feathers.
> More fun with tar and feathers :-)

- entry_util.c
- entry_util.h
- json_util.c
- json_util.h
In entry_util.{c,h} add that the parser was co-developed by Landon and
me.
In json_util.{c,h} move "Because sometimes even the IOCCC Judges need
some help." :-) to below our names (there might be other files that need
this change as well).
> JSON parser comments updates

- CHANGES.md
- dbg.md
It was in error to escape _ as in the generation of the html it shows \_
instead of just _. Fixed via:
sed -i 's,\\_,_,g' *.md
> Remove \ before _ in markdown files

- entry_util.c
- entry_util.h
- txzchk.1
- txzchk.c
- txzchk.h
The following commits were made but due to conflicts in other commits I
am making a new pull request. Unfortunately it's harder to keep track of
what commit did what as I have it all in one commit now but the
following commits were made except that I have attempted to merge some
of the logs together. The commit ids will no longer be valid of course
but I'm doing it this way to try and keep it more organised (try but
maybe not succeed):
commit 7ceb5e60d15400dc02d4ea8875f1c516efcdd9fc
Date:   Fri Jul 29 07:55:11 2022 -0700
Minor updates and fixes in txzchk
Change remaining references of 'issues' to 'feathers' to continue the
fun of:
"Because sometimes people add feathers to tar." :-(
(There are still a few references to issues but this is only to make it
clear that it's just wordplay: all …
> Various fixes and updates to txzchk and new test functions for chkentry

- Makefile
- chkentry.h
- foo.h
Because chkentry.c uses a function that is defined in foo.c chkentry.h
included foo.h. However this resulted in a compilation error in CentOS
as supposedly an array that was defined was not being used (this is
because it's used in foo.c but not chkentry.c but chkentry.c #included
foo.h for above mentioned function) i.e. it was used in one place but
not the other.  Removing static would not work because then it would
result in multiple definitions of the same symbol.
There were three fixes I could think of. One was discarded before as
undesirable (inclusion guards to enable certain variables) and another
would be a crime against foo so I opted with moving the function
declaration into chkentry.h since that's where it's used anyway.
Run make depend and fix typos in Makefile.
> Fix 16beee5 for CentOS compilation

- foo.c
- txzchk.c
- txzchk.h
The following fixes were made (but note that if a test is not mentioned
below it does not mean it's not already in place and it's entirely
possible I miss below one or more tests that has or have been added).
After each file size is parsed if the new total size is < the previous
size it is an issue.
After each file size is parsed if the new total size is > MAX_DIR_KSIZE
it is an issue (this was only done at the end after all files parsed).
After each file size is parsed if the new total size is < 0 it is an
issue (the current file size was tested for < 0 and also 0 but the total
was not until the very end).
After each file size is parsed if the new rounded file size (up to 1024
multiple) is < the previous it is an issue.
Each test is only displayed once. That is there are new booleans …
> Several fixes and enhancements to txzchk + formatting fix in foo

- entry_util.c
- entry_util.h
- mkiocccentry.c
The following functions were added:
+extern bool test_remarks(char *str);
+extern bool test_min_timestamp(time_t tstamp);
+extern bool test_timestamp_epoch(char *str);
To clarify the difference between test_min_timestamp() with the already
existing test_formed_timestamp() (since it also refers to
MIN_TIMESTAMP): the test_formed_timestamp() function verifies that the
formed timestamp >= MIN_TIMESTAMP whereas test_min_timestamp() tests
that the entry has the same minimum timestamp required.
I also fixed some typos.
As well I added some defines:
#define PROG_C_FILENAME "prog.c"
#define REMARKS_FILENAME "remarks.md"
#define MAKEFILE_FILENAME "Makefile"
and made use of these in the entry_util.c file. Perhaps these can also
be used in mkiocccentry.c but I only just thought of this and I must …
> Add more test_ functions to entry_util + fix typos

- entry_util.c
- run_bison.sh
- run_flex.sh
The scripts used command -v to determine the path of the tools. But this is a problem because it doesn't force checking of the path. For example on my macOS system doing command -v ls reports:
alias ls='ls -GF'
but with type -P ls:
/bin/ls
It's improbable that most would have an alias for flex or bison but better safe than sorry. At this time no other scripts use command but instead use type (if necessary). However the Makefile does use it but I'm not sure if this is good or bad. Probably it should also be fixed but for now I'm leaving it off pending discussion.
> Fix potential invocation error in run_{flex,bison}

- Makefile
- ioccc_test.8
- iocccsize_test.8
- jparse_test.8
- mkiocccentry_test.8
- txzchk_test.8
As for the files not named I simply fixed the name so that they all have .sh in the name as they're all shell scripts.
The usage of make install will now install mkiocccentry_test.8 as well.
> Man page updates + addition of mkiocccentry_test.8

- Makefile
- jparse.l
- jparse.ref.c
- test_txzchk/README.md
The question of whether or not it should just do `make all' is certainly something to consider but for now this covers everything that will need to be recompiled after the parser is regenerated.
There was also a typo fix in jparse.l - kind of. I had removed 'demo' from 'demo tool' but I meant to add it back as maybe jparse itself is kind of a demo as it doesn't actually do anything with it - it just parses it but does nothing with it other than report if it's valid or not.
> `make parser' now compiles chkentry + update readme for txzchk_test.sh

- hostchk.sh
- test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2-19944411114.txt.err
- util.c
A problem occurred in string_to_intmax2() in the order of checks for failures so that under linux the errno was set to non-zero but this was not triggered under macOS. This fix saves errno first (as an abundance of caution) and then checks the other conditions. Then after those are passed the saved errno is checked and if not 0 then it's used (setting errno to the saved value).
I also updated the test_txzchk/bad error file. This should solve the problem but if not I'll have to look at it tomorrow.
> Fix txzchk_test.sh under linux

- bug_report.1
- fnamchk.1
- have_timegm.8
- hostchk.1
- ioccc_test.8
- iocccsize.1
- iocccsize_test.8
- jnum_chk.8
- jnum_gen.8
- jparse.1
- jparse_test.8
- jstr_test.8
- jstrdecode.1
- jstrencode.1
- mkiocccentry.1
- mkiocccentry_test.8
- run_bison.8
- run_flex.8
- txzchk.1
- txzchk_test.8
- utf8_test.8
- verge.8
- vermod.8
This commit was in part an experiment with fixing formatting in some places in man pages. Possibly for some of the changes some files need to be updated still and there also definitely has to be more consistency updates but these can wait until another time. I went ahead and did certain things for a number of man pages as follows:
In the case of specific exit codes being in a list use .TP and .TQ macros. This makes it much cleaner and it aligns the two columns correctly. The .TQ macro might be used in one other man page in one place too though not sure which one that might be now.
In some cases I have used .I and .B instead of \fI..\fP and \fB..\fP but this is not consistent and in some cases it cannot be done this way (thinking of a full stop or dot as the very next character - it might …
> Mass update man pages

- bug_report.sh
- jparse.l
- jparse.ref.c
- mkiocccentry.c
- mkiocccentry.h
- version.h
This is a big update which adds checks for all the tools we need as well as all the optional tools. This does which(1) on each tool but depending on if it's optional or not it will be reported differently if it's not found.
Add more thorough version checks as well. The comments in the script explain the process which I will repeat here but first an important point is that for some tools we do not try getting the version. For example echo supposedly has a --version option in linux but from quick tests it doesn't work and in macOS (and presumably BSD) it does not even have that option in the man page. Another example is cat because some options namely -v are valid and cat would block whether or not you consider -v harmful (as a certain person (in?)famously suggested (perhaps controversially …
> New version of bug_report.sh

- iocccsize_test.8
- mkiocccentry.1
- txzchk_test.8
I have tried to make some options a bit clearer and I fixed a typo as well.
> Typo fixes and rewording in man pages

- .gitignore
- chk.auth.head.c
- chk.auth.head.h
- chk.info.head.c
- chk.info.head.h
- chk_sem_auth.c
- chk_sem_auth.h
- chk_sem_info.c
- chk_sem_info.h
- hostchk.1
- hostchk.sh
- verge.c
- verge.h
Added test source files that must return specific values (and in the case of one print a certain string).
It's not modular yet. Whether this should be done or not I don't know. One benefit from that might be that we be that it would be easier to run all of these tests even if one fails. Currently when one fails no further tests are run.
There are several kinds of tests. First we obtain the value of ENOENT and then verify that setting errno = ENOENT will indeed be the value previously obtained. We then check for the string: "errno: $ENOENT" (whatever ENOENT might be: keep it in a variable for consistency check but also in case some system has a different value). We also print "Hello, world" and check that that was indeed printed. There are checks for return values 1 and 0 and maybe another …
> New version of hostchk.sh + comments consistency update

- CHANGES.md
- README.md
- entry_util.c
- entry_util.h
- foo.c
- foo.h
- jsemtblgen.c
- json_util.c
- oebxergfB.h
- util.h
- vermod.8
The functionality for ignoring warnings has been not needed for quite some time. The functions were removed but the prototypes were not.
I also updated comments so that any reference to 'being co-developed by' was changed to 'was co-developed by' (or if both chkentry and the JSON parser 'were'). I'm aware of some files that still need some of this added but those that had it in some form should be fixed.
> Remove unused function prototypes

- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- mkiocccentry.c
- mkiocccentry.h
If the submit server is not ready the user of mkiocccentry is told that
because the submit server is not ready they may not enter the contest.
It also asks them to please not email the Judges. If however the server
is ready it tells them how to register as well as (after forming the
tarball that's not a test entry) where they can upload their entry
(again assuming they've registered).
This commit makes these checks a bit more modular (well - the checks
weren't actually in before except for test mode but the display of these
things were there and it is this that is modular but the check for the
submit server being ready was added to it in the two new functions).
That commit also fixed some typos and in commit d4e9f088c9aefe1be679927842a8e45b8de8bf34 there was also a typo fix (jparse.y).
> Add check for IOCCC submit server readiness

- jparse.l
- jparse.ref.c
- jparse.tab.ref.c
- jparse.y
- json_parse.c
- json_parse.h
- jstrdecode.c
- mkiocccentry.c
- mkiocccentry.h
This commit is on a different branch because it's somewhat hackish and I
might be missing something. More specifically I'm not quite sure it's
correct. Although the has_nul is set to true if it's encoded there very
possibly is a better way. Not only that but I might have missed some
cases.
Nevertheless with a file like:
$ cat nul.json
"test\u0000test"
one will see:
$ ./jparse -J 5 nul.json
in parse_json_stream(): JSON debug[5]: calling parse_json on data block with length 17:
in yyparse(): JSON debug[5]: under json_string: returning $json_string type: JTYPE_STRING
JSON tree[5]:       lvl: 0  type: JTYPE_STRING      len{q0a}: 9     value:  "test\0test"
in yyparse(): JSON debug[5]: under json_value: returning $json_value type: JTYPE_STRING
JSON tree[5]:       lvl: 0  type: JTYPE_STRING …
> Add check for has_nul in json_decode()

- man/chkentry_test.8
- man/hostchk.1
In chkentry_test.8: remove from the BUGS section the statement that some of the tests fail as this no longer is true.
In hostchk.1: fix formatting detected by checknr.
> Minor fixes in two man pages

- chkentry.c
- jparse.h
- jparse.l
- jparse.lex.ref.h
- jparse.ref.c
- jparse_main.c
- jsemtblgen.c
Under macOS this problem did not show up but under linux it did. The problem is that chkentry also called clearerr_or_fclose() on the streams of the .info.json and .auth.json files but because the scanner also uses this it resulted in a double free. I'm not sure exactly why this did not happen before since it was always the same stream in the end but possibly because yyin was used it was in a different state. As I noted in either a commit log or a GitHub comment we can no longer use yyin due to complexities introduced with the re-entrant scanner wrt setting/getting yyin needing the scanner context (which we don't always have): specifically the function that opens the json stream (or stream that is supposed to be json) does not have the scanner. Instead the function that that function …
> Fix segfault in chkentry and memory leak in jparse

- chkentry.c
- jparse.h
- jparse.l
- jparse.ref.c
- jparse_main.c
- jsemtblgen.c
The diff for the parameter changes:
-extern struct json *parse_json(char const *filename, char const *ptr, size_t len, bool *is_valid);
-extern struct json *parse_json_stream(char const *filename, FILE *stream, bool *is_valid);
+extern struct json *parse_json(char const *ptr, size_t len, char const *filename, bool *is_valid);
+extern struct json *parse_json_stream(FILE *stream, char const *filename, bool *is_valid);
> Reorder parse_json and parse_json_stream args

- bug_report.sh
Since have_timegm.sh no longer exists bug_report.sh failed because it tried to run it along with all the other tools.
> Fix bug_report.sh

- entry_util.c
- json_sem.c
- test/jstr_test.sh
- txzchk.c
- util.c
Now the script checks for failure of test 3. I'm not sure if there are any conditions that might not be picked up. For example if another part of the pipeline fails it might not be detected but at least if one of the files does not exist (or cannot be found) the test will fail.
> Fix bug in jstr_test.sh - resolves #407

- Makefile
- soup/Makefile
- test_ioccc/Makefile
Fix 'No rule to make target `jparse/Makefile', needed by `jparse'' in Makefile.
Fix strange issue where running make clobber would pass to rm -f -f instead of just -f. I'm not even sure why this happened - I don't have the time or energy to try figuring it out. It seems odd because there's no reference to -f -f in any file. It did not occur with the dbg subdirectory but it does with soup and test_ioccc/. The fix was removing the single -f from the rm invocation in those Makefiles. It's very funny because even after removing the -f from the invocation in e.g. soup/Makefile if one does `cd soup; make clobber' you'll see that it does in fact run rm -f.
> Makefiles clean up and fixes

- Makefile
- soup/Makefile
- test_ioccc/Makefile
Reverts ioccc-src/mkiocccentry#420
Due to `make clobber` failure, plus other issues.
> Revert "Makefiles clean up and fixes"

- jsemcgen.sh
A comment describing a situation was above the place in the script that it could have happened so I moved that part of the comment to after the fact but prior to testing it.
> Fix comment location in jsemcgen.sh

- limit_ioccc.h
Although technically correct at what it was, it was suggested to lower it. I actually thought of this as well so I went ahead and did it. A note on it though. The 255 to 64 does not really need an explanation as 64 is also the value of MAX_URL_LEN so it is a reasonable limit. If this is ever a problem for either it could of course be increased.
But the 20 instead of 19 is because unlike twitter, mastodon handles have two '@'s so the limit should allow for the same number of characters in twitter handles, as far as user names go, which was 18.
> Lower MAX_MASTODON_LEN

- jparse/Makefile
It was missing jnum_gen which means that one would have to do make -C jparse before jnum_gen was built. This prevented bug_report.sh from working as it could not execute jparse/jnum_gen since it was not compiled.
> Fix EXTERN_PROG in jparse/Makefile

- bug_report.sh
Due to moved files the paths in bug_report.sh were broken which prevented a successful run of the script.
> Fix bug_report.sh from 2f8f47ff5e

- Makefile
- bug_report.sh
- dbg/Makefile
- dyn_array/Makefile
- jparse/Makefile
- soup/Makefile
- test_ioccc/Makefile
There might still be some issues but at least now running make all more
than once will try recompiling everything. This is on a different branch
because of some problems I had some of which I'm not sure entirely of
the source.
Specifically one to do with permissions. This was very possibly because
of earlier on trying to do make && sudo make install but then the make
install as root actually compiling the object files again - but it might
not be because make clobber all sometimes (not always) resulted in the
problem again.
Sometimes I got an error trying to link dbg but that was because, it
appears, that a Makefile (not in dbg/) did make dbg instead of dbg.o or
dbg.a. I changed it to dbg.a but in retrospect it might need to be
dbg.o: I'm not sure but noting this in case it is a problem. …
> Fix the make all repeatedly compiling everything

- test_ioccc/Makefile
The problem was that in test_ioccc/Makefile the rule ../dbg/dbg.a did make -C ../dbg dbg.a extern_liba and extern_liba was all that was necessary as that rule itself runs the dbg.a rule. This silences make entirely after a successful make all.
> Fix make[2]: `dbg.a' is up to date.

- jparse/test_jparse/jparse_test.sh
- test_ioccc/ioccc_test.sh
Default is now "." and the test_ioccc/ioccc_test.sh specifies -s general.json. The jparse/test_jparse/Makefile still uses -s but it no longer should have to.
> Change default value of -s in jparse_test.sh

- Makefile
- dbg/Makefile
- dyn_array/Makefile
- jparse/Makefile
- jparse/test_jparse/Makefile
- jparse/test_jparse/test_JSON/bad/party.json
- jparse/verge.h
- soup/Makefile
- test_ioccc/Makefile
The reason make test did not fail for me is that I had made an empty directory bad/ under jparse/test_jparse/test_JSON but I forgot to add a file which means that the directory could not be found. Thus I have added a jparse/test_jparse/test_JSON/bad/party.json (to be in the theme of the good/party.json).
I also came to realise that diacritics are allowed in json so I changed the diacritics being escaped to diacritics. Perhaps though we should have some of the \u codes as well.
An aside for those who look at the party.json file and who are also interested in The Lord of the Rings. It is NOT an error to say that an alias of Gollum is Dígol. This is because in the earlier draft (see History of Middle-earth [HoMe] VI - The Return of the Shadow) there was no friend and it was ONLY Dígol. There …
> Fix make test on other systems (than mine)

- Makefile
- bug_report.sh
- soup/Makefile
- test_ioccc/prep.sh
To do this required writing some new functions and reworking some things as well but with these changes bug_report.sh -l is now completely silent.
test_ioccc/prep.sh runs new Makefile rule bug_report-txl which runs bug_report.sh with -t -x -l which means to not run the make actions (prep.sh will have already done this), remove the log file if everything is okay and make the actions silent (respectively). Note though that prep.sh is still quite verbose. It does have an option for a log file but it's not yet used and I'm not even clear yet on the way it's supposed to work.
There were two bugs in bug_report.sh though one did not seem to be triggered always. The one that was not triggered in every case was that because the function exec_command() was empty it was a parse error (it might also …
> Bug fix + make bug_report.sh -l completely silent

- Makefile
- bug_report.sh
- dyn_array/dyn_array.c
- dyn_array/dyn_array.h
- jparse/Makefile
- test_ioccc/Makefile
- test_ioccc/hostchk.sh
- test_ioccc/man/man8/hostchk.8
We now collect shell options that are set (shopt -s).
When we're getting the bash version, if the basename is "bash", we get the values of the variables:
$BASH_VERSION
${BASH_VERSINFO[0-4]} # as in each of the five indices
$MACHTYPE
A note about the BASH_VERSINFO array. We do not string it up as one string but rather echo each element one at a time. This is a cosmetic choice as it would be a long line in the bug report. Additionally for each one the status is shown by not the element or array but what it stands for. For instance for ${BASH_VERSINFO[4]} we show something like:
release
The $MACHTYPE is the same value as ${BASH_VERSINFO[5]} but to be more clear we use $MACHTYPE. We still do it if it's the command passed to get_version is "bash" as it's a bash thing (though maybe other shells …
> Various enhancements, updates and fixes

- Makefile
- bug_report.sh
- dbg/man/man3/dbg.3
- dyn_array/man/man3/dyn_array.3
- jparse/man/man3/jparse.3
- soup/Makefile
- soup/all_sem_ref.sh
- soup/sanity.h
- soup/soup.h
- soup/version.h
- test_ioccc/ioccc_test.sh
With the soup_version string in sanity.c but not in any header file it triggered a warning that there was no previous extern declaration for non-static variable:
sanity.c:22:19: warning: no previous extern declaration for non-static variable 'soup_version' [-Wmissing-variable-declarations]
const char *const soup_version = SOUP_VERSION;  /* library version format: major.minor YYYY-MM-DD */
^
sanity.c:22:7: note: declare 'static' if the variable is not intended to be used outside of this translation unit
const char *const soup_version = SOUP_VERSION;  /* library version format: major.minor YYYY-MM-DD */
^
Now it could have gone in sanity.h but I felt soup.h was more fitting. If there was a soup.c the version could have gone in there but it seems like making a soup.c just for that might be …
> Fix -Wmissing-variable-declarations in sanity.c

- CHANGES.md
- README.md
- dbg/man/man3/dbg.3
- dyn_array/man/man3/dyn_array.3
- jparse/Makefile
- jparse/README.md
- jparse/jparse.h
- jparse/jparse.tab.ref.c
- jparse/jparse.tab.ref.h
- jparse/jparse.y
- jparse/man/man3/jparse.3
- mkiocccentry.c
- soup/man/man1/txzchk.1
- test_ioccc/dynamic_analysis.md
- test_ioccc/fnamchk.c
- test_ioccc/txzchk_test.sh
- txzchk.c
- txzchk.h
With commit b5fc2a3658e8eeea711eb908a2fd6c6806b58bae the txzpath was changed to txzpath_path which seems like it might not be what was intended. In any case it seems clearer as tarball_path so that's what it now is called in all cases including the man page and usage message.
> Various updates, enhancements and fixes

- txzchk.h
Due to changing the txzpath to tarball_path the number of tabs in that line (as in \t) in the usage_msg string was incorrect.
> Formatting fix in txzchk -h

- mkiocccentry.c
- soup/oebxergfB.h
- test_ioccc/static_analysis.md
The problem was a missing 'else' in front of the 'if' that happened right after the free and set to NULL author name. Perhaps this was missed because of the way the comments were below the last if.
> Fix segfault when author name too long

- soup/location.c
Although ions have their place when peroxide ions in particular combine with water and diluted acids it forms hydrogen peroxide which has ended up killing people when those unaware of the dangers misunderstand the request that someone would like a glass of H2O too. Thus we should get rid of stray ions in the repo and now have.
Yes there's a point (or actually two points) in the above. In order to help discern what they are you should start by looking at the diff.
> Typo fix in soup/location.c

- mkiocccentry.c
- mkiocccentry.h
- soup/entry_time.c
- soup/entry_util.c
- soup/utf8_posix_map.c
- test_ioccc/fnamchk.c
- txzchk.c
With the exception of perhaps dyn_array.c all error messages have been checked. It is inevitable that I missed some things as it was a lot to go through and I did not do it by scrolling down from the top line by line but rather in ways that would help find errors and similar messages.
In mkiocccentry.c other types of messages were checked and in some cases improved.
One directory that might need to be rechecked for debug messages is jparse/ as I did not look for json_dbg() (I did under soup/) but this can happen another time.
Besides that the only other error (and related) messages to check are those in shell scripts.
> Check final C file for error messages

- CHANGES.md
- FAQ.md
- Makefile
- dbg/man/man3/dbg.3
- jparse/man/man1/jstrencode.1
- jparse/man/man8/verge.8
- soup/man/man1/iocccsize.1
- soup/man/man8/all_sem_ref.8
- soup/man/man8/vermod.8
- soup/vermod.sh
- test_ioccc/chkentry_test.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/man/man8/ioccc_test.8
- test_ioccc/man/man8/mkiocccentry_test.8
- test_ioccc/man/man8/txzchk_test.8
- test_ioccc/mkiocccentry_test.sh
- test_ioccc/test_txzchk/README.md
- test_ioccc/txzchk_test.sh
In order to test other implementations of tar the txzchk_test.sh script has been enhanced to take an optional tar path. To make the tool more consistent with other tools (except in a way txzchk itself, see below) the script now is -t tar and -T txzchk. This is because in mkiocccentry that's the meaning of the options.
The mkiocccentry_test.sh and ioccc_test.sh scripts now also take -t tar and mkiocccentry_test.sh additionally takes an option for cp (-c cp), ls (-l ls), txzchk (-T txzchk) and fnamchk (-F fnamchk).
The way these changes are not consistent with txzchk is simply that txzchk takes a -T option to set text file (or if you prefer 'test') mode and -t for tar and additionally mkiocccentry takes a -T txzchk so the scripts that now take a -T that doesn't set txzchk won't match but …
> Improve some of the test scripts

- CHANGES.md
- test_ioccc/hostchk.sh
For whatever reason POSIX grep does not require -o or -h options which we used before. The -o we never actually needed but the -h we do need because we check more than one file and need only the contents not the files the contents are in.
Instead of using grep -o -h we pipe the grep to `cut -f 2- -d:' and pipe that to sort -u (the order is important). This will remove the filenames from the output and it'll show the exact lines we need but in a POSIX portable way. This is because (as part of POSIX) if more than one file is specified to search then the output is prefixed with:
"%s:", <file>
but we only need the second field in all our cases.
This makes hostchk.sh work on hosts that do not have one or both of grep -o or grep -h options.
> Make hostchk grep usage POSIX compliant

- jparse/Makefile
An annoying problem was in jparse/Makefile when running make parser that made it appear that the scripts were not running. There are two parts to this.
First the script was set to 0 verbosity level and I did not realise this so it seemed as it was not running (only obscure hints that it was). The second part is that the make parser rule had the lines:
${E} ${MAKE} jparse.tab.c jparse.tab.h
${E} ${MAKE} jparse.c jparse.lex.h
and the problem with that is that the first of each implies the second so we would get the messages:
make[2]: `jparse.tab.h' is up to date.
make[2]: `jparse.lex.h' is up to date.
This made me believe that the problem I was facing was the scripts were not running but instead it's that the rule was run twice which is unnecessary. Thus a comment above each one notes that …
> Fix up to date issues in make parser rule

- CHANGES.md
- mkiocccentry.c
When the past winner and winner handle prompts were added to the mkiocccentry tool the tool was changed to read the values from the answers file but it did not write it to the answers file.
But why did the test script work? It's simply because the script (of course) does not run the interactive tool but merely reads from the answers file which the script itself creates.
Now one can use the -a/-A feature and expect -i to work.
> Fix writing of answers file (past winner, handle)

- CHANGES.md
- jparse/Makefile
- jparse/json_util.c
- jparse/util.c
- mkiocccentry.c
Two warnings were being triggered under macOS: one about unused but set
variable (in generated code). That was solved by adding
-Wno-unused-but-set-variable to the WARN_FLAGS. Note that clang in some
platforms (like CentOS 7) do not have that option but it is not fatal so
this is okay (though in that platform it would generate additional
warnings).
The other was a more recent one:
json_util.c:129:18: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
json_warn_allowed()
^
void
The solution is to add void to the function arg list.
Aesthetic changes that don't really matter but were done and by accident
made in this commit (I already saved and quit - this is an emendation): 
off-by-one char in a comment and better wording of a …
> Fix warnings compiling jparse

- CHANGES.md
- remarks.example.md
This file gives instructions for writing a remarks.md file for IOCCC entries. This commit was supposed to be done quite a while ago but it slipped my mind and I haven't looked at the repo in a long while (or git status of the repo in a long while).
This file is of the same nature as the Makefile.example.
Updated CHANGES.md to note this addition.
> Add remarks.example.md for authors

- CHANGES.md
- bug_report.sh
- jparse/Makefile
- remarks.example.md
After make clobber (under jparse/) the bogus file created by
bug_report.sh, lex.jparse_.c, is removed.
bug_report.sh also removes this file in the clean up stage.
Updated README.md with this bug fix.
> Remove lex.jparse_.c - resolves #518

- .gitignore
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
Right now it only links in the jparse, dynamic array and debug libraries and when run it exits 0.
The Makefile has been updated and make depend was run as well.
This tool will I believe take some time and careful thought and it definitely will be developed over many commits but now it should be possible to just start writing the code without having to worry about editing the Makefile etc. More editing of the Makefile will have to be done later - for instance when man pages are added or some dependency changes or if a new file has to be added but at this point I can start working on the code once I have a better idea of what is needed. This won't happen until a discussion is had on GitHub though I might be able to get some code in prior to that should I find the time and energy. I do hope …
> Initial jprint code

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/util.c
- jparse/util.h
- soup/man/man1/location.1
I also want to say a couple things that were not mentioned in the
previous commit that were added or changed.
Most importantly one can now specify more than one name arg.
Also the -c option to jprint was changed to -T and -c was given the same 
meaning as grep -c.
> Typo fix jprint.c comment

- jparse/jprint.c
- soup/man/man1/location.1
Instead of relying strictly on fopen() with "r" for mode use is_read() 
first. If it returns false it is an error. If it returns true but 
fopen() fails for some other reason it's also an error.
> Explicit check for unreadable files in jprint

- jparse/jprint.c
- jparse/util.c
- jparse/util.h
- soup/man/man1/location.1
Added the function string_to_uintmax() in util.c. This will be needed
for jprint.
In string_to_intmax() there was a possible NULL pointer dereference.
'ret' was always dereferenced to set the return value of strtoimax() but
it was not checked for NULL.
> Add string_to_uintmax + fix NULL pointer

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/util.c
- jparse/util.h
- soup/man/man1/location.1
This commit is an important step in progressing on the tool as now we
can discuss what needs to be done, what has to change etc. wrt the
options and functionality of the tool. What this commit includes is as 
follows.
The getopt() call should be complete but there are few comments except
in the variables for the options. Note that some variable types will
possibly have to change and as far as option arguments being parsed only
the integers and booleans are complete. As the rest of the details
become clearer more can be done.
A word on the usage string. Right now I have the longer version as it
will be useful to have the information when I work more on the code.
As each part is done the usage string in that part can be simplified
I also added the exit codes to the usage string as requested …
> Initial parsing of options in jprint

- CHANGES.md
- jparse/jprint.c
The usual - for stdin now is accepted.
Free tree prior to exiting if an error is not encountered. This probably should be in a separate pull request but it escaped my mind that I already added the other code.
> jprint can now read from stdin + free tree

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
This is currently done with a bitvector and it might change if it's 
discovered that a better way exists. But that won't be known until more
is developed. This was not even the first way I thought of. What will
stay the same is the loop going through the comma-separated optarg but
whether the keeping track and checking of types will be done differently
is TBD later.
Other comma-separated lists in the options will also likely be done in a
similar way but how the information is stored is unknown at this time.
Updated CHANGES.md.
> Parse -t type in jprint

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
Specifying -m depth sets the maximum depth the tool will traverse in the
JSON tree. Used only if the json is valid.
Explicitly include dyn_array.h and update Makefile to be clear on this.
Updated CHANGES.md for new jprint version. Fixed date of previous 
release as well: it said it was 5 June but that's today, not yesterday.
> New jprint version - allow setting max tree depth

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
The last usage string is for the end (how surprising :-) ) of the usage
message but if any additional strings have to be added (or removed) the
last number should be changed. Likely it'll be possible to remove one as
the string will be reduced in size once more is done with the tool (and
thus I don't need to see the usage as much) but this will be found out
later.
> Clarify last usage message number in jprint.c

- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
The program is supposed to exit 0 if no name_arg is specified but it 
only exited 0 if one was specified and there was a match.
I also made a minor fix to the exit code wording in the usage string.
> Fix exit code for no name_arg specified in jprint

- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
At the end of the usage_msg strings there should be only one '\n' as it 
will otherwise (print an additional newline which means two extra lines
between each portion of the usage string when only one is needed).
> Remove extraneous newlines in jprint usage message

- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
In other words whether or not a type should be matched. The following
functions were added:
bool match_none(uintmax_t types);
bool match_int(uintmax_t types);
bool match_float(uintmax_t types);
bool match_exp(uintmax_t types);
bool match_bool(uintmax_t types);
bool match_string(uintmax_t types);
bool match_null(uintmax_t types);
bool match_object(uintmax_t types);
bool match_array(uintmax_t types);
bool match_any(uintmax_t types);
bool match_simple(uintmax_t types);
bool match_compound(uintmax_t types);
but as noted yesterday it might be that something else is devised to do
this instead but bits at this time seem like a simple approach 
especially with these functions.
> Add test match types functions

- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
Add missing -l option itself to getopt().
Add two structs, one contained in the other, for number ranges. This is a work in progress and might change in details.
Add beginning to parsing of these options. Right now it zeroes out the structs and returns true as long as optarg != NULL and *optarg != '\0'.
More will be done in a future commit.
> Start parsing of jprint -l, -i, -N

- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
In the previous commit I also ended up changing the 'print' variable in
jprint_parse_print_option() to be 'print_type'. Now it's 'print_types' 
as it isn't just one necessarily but up to two.
> Fix print types variable in jprint -p option

- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
Using two structs, one within the other, along with some bools it's now
easy to test if a range is required or if an exact number is required or
if a min (number >=) or max (number <=) is required.
The function that does the parsing is:
/* jprint_parse_number_range        - parse a number range for options -l, -n, -i
*
* given:
*
*  option      - option string (e.g. "-l"). Used for error and debug messages.
*  optarg      - the option argument
*  number      - pointer to struct number
*
* Returns true if successfully parsed.
*
* The following rules apply:
*
* (0) an exact number is a number optional arg by itself e.g. -l 5 or -l5.
* (1) an inclusive range is <min>:<max> e.g. -l 5:10
*     (1a) the minimum must be <= the max 
* (2) a minimum number, that is num >= minimum, is <num>:
* (3) …
> Complete parsing number range options -l, -i, -n

- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
There was a duplicate option -I - used for two purposes, indent and
case-insensitive. -i was used for something else, a limit. I changed -i
to -n and the case-insensitive one to be like grep, -i.
> Shift option letters in jprint a bit

- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
Since '\t' is 8 spaces and since the other mode for the options is 
number of spaces if optarg is "t" or "tab" set the variable to 8.
Otherwise attempt to parse as a number. If it fails to parse it's an
error.
This completes at least for now the parsing of all options if I'm not
very much mistaken. As long as I did not miss any in the long list this
is done. Once I start adding functionality (the purpose of the tool
itself) some of the options might very well change.
> Finish parsing jprint options (-b, -I)

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
I forgot to do this yesterday. CHANGES.md updated.
I plan to finish the rest (at least known at this time that I can think
of) of the test functions (for the options set) in the coming commits 
which will probably be reason enough to update the version again but I 
wanted to make sure that this version is specific to all options have 
been parsed.
> Update jprint version for all options parsed

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
New release for mkiocccentry toolkit: 0.0.7 2023-06-08. Great progress
has been made with jprint at its new version 0.0.7 2023-06-08!
At this time I believe all known checks for jprint options have been
added!
The next step is to write some test functions (likely printing debug
messages for different options and their option arguments).
If all is OK the code to traverse the tree to look for simple matches (this does
not mean the JPRINT_TYPE_SIMPLE) can be added. At first the tool will not
check for the constraints but rather just print the name and value (even though
the default is value (JPRINT_PRINT_VALUE) only I want to make sure that the
ability to to print both is there).  This will help make sure that the
traversing works okay before constraints are added. Prior to the following …
> New jprint version - all option arg checks added

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
Add option -K which runs test functions and exits 0 if successful and 1
otherwise. This currently conflicts with the exit codes but this will be
fixed in a future commit.
Number range functions added and everything runs fine.
Next is the bit options but this will take a bit more time and
must be done later as I have to head off for a bit. I hope to do it
today also but this is uncertain.
> New jprint version - initial test code added

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_test.h
- jparse/jprint_util.c
- jparse/jprint_util.h
By accident I had put the -K option description in the middle of the -m
and note about that option.
Also it doesn't test the options parsed but rather constraints whether 
they were passed prior to the -K or not (even if any were passed it 
won't use those) so the description was fixed.
> Fix usage strings in jprint

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_test.h
- jparse/jprint_util.c
- jparse/jprint_util.h
The files jprint_test.{h,c} were by accident left out of the initial
commit. This has been rectified.
If a test fails the exit code is 6 else 0 (the exit codes in the usage
string has been updated for both).
The function jprint_run_tests() now returns true if a test failed
> Add missing jprint test code + fix exit codes

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_test.h
- jparse/jprint_util.c
- jparse/jprint_util.h
This is for the test functionality so that one can pass in say 
"num,bool,str" to the function rather than rely on the command line 
itself (which does not need strdup()).
> Use strdup() on optarg in jprint -t parsing

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_test.h
- jparse/jprint_util.c
- jparse/jprint_util.h
New jprint version - 0.0.9 2023-06-08 - though perhaps this is not 
necessary. The next step is to test the -t option bits but this will 
happen after a break if it happens today (it should as it's very similar
to the -p option and even uses the same function due to a function 
pointer).
The -p test runs successfully.
Also I fixed dead code in the function to check number ranges so that
now both paths are run.
> Add code to test jprint -p option

- jparse/Makefile
Some files were missing from the Makefile source and header files variables so seqcexit was not processing them. The make seqcexit rule was not run as there are currently other changes in two of the files that should be in another commit (with different summary) but which can have in the log that make seqcexit was run but the changes in the file do indeed have some exit codes changed about.
> Fix make seqcexit

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_test.h
- jparse/jprint_util.c
- jparse/jprint_util.h
Fix handling of number range when the maximum is a negative number. This
fix involved the number range check functions to take a new parameter
which is the number of total matches.
There is one debug log that is problematic with this change but this can
be addressed at a later time, possibly by making more than one debug log
message depending on the range.
Sequenced exit codes.
Fix too long lines detected by make picky (previously undetected due to
the files missing in the variables in the Makefile fixed in commit 
3ffe7cf6bbcaa1ee727668f81ab6cd15fe4b9b4e which fixed not only make 
seqcexit as the log said but also make picky).
Updated CHANGES.md with new mkiocccentry release too as this seems like
a good place to do so as this is a very important change to the jprint
tool.
> New jprint version 0.0.10 2023-06-09 - inclusive range fix

- CHANGES.md
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
New jparse version:
The problem was that the column in invalid tokens appeared to be always 1 even when it should have been something else.
For instance given the following input:
$ ./jparse -
{"test":false,
"foo":"bar"},
one would get:
syntax error node type JTYPE_OBJECT in file - at line 2 column 1: <,>
ERROR[1]: ./jparse: invalid JSON
Following the questionable spec that one cannot end the last element with a comma, the ',' on line 2 which is at column 13 is in error since it's the last element of the file. As can be seen it showed column 1 line 2 so the line was correct but the line was not. Now it shows the correct line and column:
$ ./jparse -
{"test":false,
"foo":"bar"},
syntax error node type JTYPE_OBJECT in file - at line 2 column 13: <,>
ERROR[1]: ./jparse: invalid JSON …
> Fix jparse locations - resolve issue #595

- CHANGES.md
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jprint.c
- jparse/jprint.h
- remarks.example.md
Although no name_arg specified always resulted in an exit code of 0 (if
valid JSON) it was not explicit in the code that it will print the 
entire file. There is now a new boolean (admittedly redundant but it 
makes it clearer) that is set to true if there is no name_arg. The 
boolean is called 'print_entire_file'. This boolean has been added 
explicitly to checks even though this is redundant again just to make it
clearer in the code.
> Make more explicit usage of no name_arg in jprint

- CHANGES.md
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jprint.c
- jparse/jprint.h
- remarks.example.md
This is useful to help organise things and also because I think it's
going to be necessary to have a callback or possibly callbacks and since
there are many options / settings it will be helpful to have everything
in a single struct.
Not every variable is in the struct - only those specific to options. I
am still not completely satisfied with some of the variable names but 
this can be worried about another time.
> Move many jprint options to struct jprint_options

- CHANGES.md
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jprint.c
- jparse/jprint.h
- remarks.example.md
Since -j enables several options and -p will change the meaning of only 
part of -j it is an error to use -p and -j together. Note that the
default is to print values so it is only if one explicitly uses -p with
`-j`.
> Make use of jprint -j and -p together an error

- CHANGES.md
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jprint.c
- jparse/jprint.h
- remarks.example.md
It probably doesn't matter much but using code like
for (char *p = text; *p; ++p) { }
is more beautiful in my eyes perhaps because it's a standard C idiom.
The 'char *p' inside the start of the for loop is because it's in a
macro.
Everything checks out okay.
> Make YY_USER_ACTION use char * not array access

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
New version of jprint - 0.0.15 2023-06-12.
The struct jprint will hold other information besides the options 
including additional structs.
In this commit the msg("valid JSON"); call has been made a dbg() call to
match the formatting of the other dbg() calls.
A note on the level DBG_NONE just to be clear. None of these dbg() calls 
will keep the DBG_NONE level. It's only this way for now as I don't want
to have to always specify the -v num option every time I am testing
something but I do want to always have this information during
development. To be entirely clear on this point: all messages currently
are subject to change or being deleted. Messages added later will also 
be subject to change or being deleted and this holds until the tool is
more fully developed where it would be a …
> Make struct jprint options a struct jprint *jprint

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/Makefile
The check was
if (*argv[0] == '-') { /* ... */ }
but this is incorrect because image if someone does:
./jprint -- -555
It would try and read from stdin when the person either made a typo or 
they have for some odd reason a file called '-555'.
Now the entire argv[0] is checked via strcmp(). Why argv[0]? Because
after options are parsed argv and argc are shifted.
Interestingly this was discovered as I was working on a (for now much
like jparse_test.sh) test script with the funny error in the log:
... in file -555 ...
which is obviously very confusing and bogus. The test script has another
issue to be worked out but this is more important to get in as the tool
is not yet complete anyway.
> Fix check of file arg '-' for stdin in jprint

- .gitignore
- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/Makefile
- jparse/test_jparse/jprint_test.sh
It is not much different from jparse_test.sh except that it does not
test the strings file (which has a json 'document' on each line). This
is because the tool does not allow a file arg to be a string from a
file. 
Something it also does do is run jprint -K test mode.
Whether string support should be added to the tool or whether the script 
should be modified so that the strings are faked as stdin are questions
that can be answered at another date.
> Add initial jprint_test.sh script

- .gitignore
- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/Makefile
- jparse/test_jparse/jprint_test.sh
For the string "valid JSON" it goes without saying that the JSON is 
valid at that point so there's no need to report it normally if at all.
For now it's being printed at DBG_MED.
> Typo fix in jprint.c + update dbg level

- .gitignore
- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/Makefile
- jparse/test_jparse/jparse_test.sh
- jparse/test_jparse/jprint_test.sh
At the same time I updated the version even though there's no functional
difference other than a correct usage string. This might be said to be 
done simply to signify that there was a change made even if it was only
something that was outdated.
> Fix incorrect exit codes in jparse_test.sh -h

- .gitignore
- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/Makefile
- jparse/test_jparse/jparse_test.sh
- jparse/test_jparse/jprint_test.sh
Functions to add to the list and to free the list added. Patterns are
appended to the list so that the first pattern/regexp specified is the
first that will be looked for. Whether this will matter in the end is
unknown at this time at least by me.
If a pattern is NULL (should never happen) the function (see below) will
not return. If the pattern is empty an empty pattern is added. This 
might or might not be something that should change but typically one 
would check that the pattern is not empty before calling the function. 
Won't add the same pattern more than once. This check is done in a 
case-sensitive manner but maybe the -i option should have a play in this
decision.
When iterating through the args on the command line it will add each to
the list via add_jprint_pattern(), …
> Add patterns linked list to jprint for searching

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
`-s` now means search substrings. Conflicts with -g. -s was -M.
`-S` sets the path to the tool to run, which although in concept should be a semantics tool checker, it can actually be something else like grep. This option was -s.
`-A` sets the args to the -S path. This option was -S. Empty args are not allowed and use of -A requires use of -S. The difference besides letters is that args now must not be empty though this might not be strictly necessary.
Updated jprint version to "0.0.18 2023-06-15".
> Change jprint options a bit

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
NOTE: to see more rationale behind this see comment https://github.com/ioccc-src/mkiocccentry/issues/523#issuecomment-1593134282.
NOTE: it should not cause problems with substrings unless `-g` is specified. Then it's a command line error. Special care was made so that it can still be used with `-Y` as long as only one name arg is specified, either via `-G` or after the file.json arg. 
NOTE: I have taken special care to avoid problems with option conflicts but if I missed something please let me know and I'll happily fix it!
The way this works is that each pattern now has a boolean to indicate the type: regexp, regular, substring (conflicts with regexp) and also if it should be searching by value or name.
The commit log is below:
--
With -G regexp one can explicitly enable a search for a …
> Add flexibility to jprint regexps/regular patterns

- jparse/jprint.c
- jparse/util.c
- jparse/util.h
- mkiocccentry.c
- txzchk.c
Based on the information in GitHub (it's not on GitHub and even 'in' is
not really the best description :-) ) it appears that if write mode is
enabled it would have to flush both stdin and stdout. However as
discussed in commit 1353ba61065735eefaaace2f8797e21f55fd42ce it cannot 
have both, seemingly, in linux. GitHub comment suggests it might better
be a boolean but it's unclear for certain if it's meant to be both read
and write for jprint. I believed it was both but if so we will have a 
possible problem as again it appears that linux does not support both 
(unless it's an unclear description in the man page); but even if it 
does support both in linux it would likely be "rw" and in macOS it's 
"r+" as the string and thus we will likely have a problem anyway.
> Make pipe_open() flush both stdin and stdout

- jparse/jprint.c
- jparse/util.c
- jparse/util.h
- mkiocccentry.c
- txzchk.c
When no pattern is specified or the new option -W (for 'write') is
specified to jprint the entire file is printed if valid JSON. If it's
not valid JSON it's an error and the file will not be printed. In the
case it is printed the exit code will be 0.
This change is important because it is one of the key features of the 
tool and it's now complete with a new option to do it explicitly (though 
it would technically conflict with a pattern specified so if a pattern 
is specified the -W option is ignored and maybe it should be a command 
line error?)!
New version is 0.0.19 2023-06-16.
> Complete jprint when no pattern specified or -W

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/util.c
- jparse/util.h
- mkiocccentry.c
- txzchk.c
This seems like a better letter to use. The issue of whether or not it 
should be a command line error if -o and any patterns are specified has
not been addressed but my suspicion is it should be an error and 
probably will be made into one. This is TBD at a later point in time, 
perhaps rather soon.
> Change jprint -W to -o for output file

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/util.c
- jparse/util.h
- mkiocccentry.c
- txzchk.c
Some important points to note. First it runs it via shell_cmd() to check
the exit code. This ends up printing out the output but since the exit
code was noted as significant it will do for now.
If it's non zero it will be an error. Otherwise it opens a write-only
pipe. If the pipe is not NULL it will be processed at a later time once
I am clear what needs to happen. If the pipe is NULL it is an error.
This means that the output is printed twice.
Second point of interest is that the -A args option I am not entirely
clear on whether they should be options that are ended by '--' or if
they should be args to the program. It might not matter even but I'm not
sure. Nevertheless right now it's used as options which. Even so one can
do for instance:
$ cat foo.json
{}
Specifying no pattern to …
> jprint now executes -S path if executable

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/json_util.c
The comments suggested it frees the json tree but instead it (as the
name implies) prints the entire tree. Probably the 'yank paste and 
forget to update' problem.
> Fix comments for json_tree_print()

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/json_util.c
Much more needs to be done here but the initial callback is added and 
the code to call it is added and also called itself. Right now no 
constraints on what to print (type, name, value, level etc.) have been 
added and one might see both name and value printed. Not all types are
printed as it's not clear yet how to print all types. The functions are 
definitely incomplete but this is a great start that will help when
actually implementing those constraints and then the right way to print
what is requested.
> Add initial callback and calling code to jprint

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/json_util.c
More thorough testing must be done for this but initial support is at 
least in.
I fixed some a wrong comment (yank paste error) and added a few notes 
about the other number constraints and how it might have to be done (but
then it might not be done that way).
No patterns are looked for yet; it just goes through every pattern as 
long as the depth is okay. It should be noted for patterns that this is
currently patterns requested rather than patterns found. That will have
to change and might involve a new list that is created before printing 
the members. These are details TBD in a future update.
> Add jprint -l level constraint check

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
New jprint version at "0.0.20 2023-06-17".
Fix special handling for -Y option wrt exactly one name arg. The idea behind the check is that if -G is specified then one cannot specify a name_arg. If it is not specified then you must specify one name_arg. If both -G and a name_arg are not specified it is also an error but there was a bug which required that -G was used.
> Fix handling of -Y wrt name_arg count check

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
In other words if a pattern is a regexp don't show "(substrings 
ignored)".
> Don't show substrings info for regexp patterns

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
New jprint version at 0.0.21 2023-06-18.
The jprint tool now has a matches list per pattern. The tree traversal functions will search for matches and after that function finally returns the printing of matches will be found. This will require additional functions that figure out how to print based on the json type and jprint options along with the jprint type but for now it prints just the name and value. Currently everything is added to the list.
Note that by 'everything is added to the list' mentioned above this means that name and value will be added as a value. This is something that will be fixed later but it's the way the tree is traversed that causes this. Be aware also that for _each_ pattern requested every member of currently supported types will be added so you can see …
> New jprint version - matches list added

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
If -Y is used by default it prints out the name of matches (though right
now no check of matches are done except for search by value or name i.e.
if it's not a value and we search by value it's not to be added). I am 
not clear if this is correct. If it's supposed to print out the value as
well then it will have to be changed. But -p modifies this behaviour 
anyway as noted below.
If -p both then print name and value. If -p v (default) then print only
value. If -p n print only the name. If one uses -Y they can still see 
the name and value.
This has only been tested for very simple JSON files and the behaviour 
in full might not be completely correct.
> Print name, value or both depending on options

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
In some cases the use of the two options is problematic. This is due to
the way the traversal of the tree is done where the pattern name is 
added to the match list being incorrect. It ends up where one can have 
the wrong things printed.
This might have been a simple error on my part as I believe I initially
had it. This will have to be fixed in a future commit.
> Note that -Y / -p is somewhat buggy in some cases

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
The functions that traverse the json tree do not print but rather search
for matches so they now suggest this in name.
> Rename some jprint functions

- CHANGES.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/json_parse.c
- jparse/json_parse.h
Don't increment the count of matches if the type is not the same. By type this
refers to the `JTYPE_*` enum found in `json_parse.h`. This means the
`jprint_match` struct now has a type.
Add more strict checks for number types based on options.
Disable explicit check for strings in match function as the check there is
problematic anyway and this helps in another way until the function itself can
be fixed. Strings are more problematic than others but matching also
currently matches on either name or value when it should only match on 
one or the other depending on the options specified.
Type checking is very much a work in progress.
> Check jprint -t / -Y more for matches

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
Based on comments in the GitHub discussion I have implemented the processing of the write-only pipe. The comment suggested only if the JSON document is read from stdin but I presume that it can be if a file on disk too. If this is not correct it can be changed later. Here is an example command and output. I'm not entirely clear on the purpose of this but this is what it looks like with debug level 3 (debug level 3 as that shows the pipe exit status being okay if it is; if it's not it's an error with exit code 7):
$ cat h2g2.json
{"number":42,
"number_str":"42",
"panic":false,
"false":true,
"true":false,
"killers":"Vogons"}
$ jprint -v 3 -Y int -S /bin/cat h2g2.json 42 2>&1|grep -v 'debug\[0\]'
debug[3]: valid JSON
debug[3]: about to execute: /bin/cat h2g2.json >/dev/null 2>&1 …
> Process write only pipe if -S tool specified

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
Now if -c is used only matches of patterns found will be printed in the
same way that grep -c does. Note that without a patterns list there can
be no matches so the -c option will have no effect. If it's desirable to
have it print the number of each json member more work will have to be 
done but this can be decided later on.
Since the options conflict quite a bit the use of -c with any of -B, -L, 
-j and -I is an error except that if -I 0 is used it's not an error. 
Perhaps it is an error and -I 0 should conflict with -c but I don't see
it as a problem either way.
Changed debug level 0 to debug level 1 as they've been in the way for 
some time now that more is implemented.
> Implement jprint -c (count only) option

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
It might be worth noting that all cases of strcmp() (when -i used) have
been replaced with strcasecmp() including searching for the pattern in
the patterns list prior to trying to find matches. That might or might 
not be correct.
> Implement jprint case-insensitive option -i

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
In some cases in a commit earlier today this was removed by accident. 
This commit rectifies that problem.
> Add newline after matches being printed

- CHANGES.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/json_parse.c
- jparse/json_parse.h
Previously it only had booleans for floating point and exponents. More 
correctly it had a boolean for each integer type but not a boolean to
simplify testing if it's a boolean or not. This will be useful for 
jprint later on for -t and -Y processing.
New json parser and jparse versions for this: 1.0.6 2023-06-20.
> Add boolean is_integer to struct json_number

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
Only -n number ranges with max < 0 makes sense. -N especially does not
make sense. It is of questionable value whether or not -l should support
it but for now it does not. If it is desired to have it it can be added
another time.
Made sure to update test functions so that jprint -K does not fail so
that make test does not fail.
Verify that make prep works okay as this has failed a number of times
recently.
> jprint -l and -N cannot have max < 0

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
Note that if one uses -b before -j the -j will override the -b 
previously specified. This probably should be changed so that if -b is 
previously specified it won't be set but for now the order matters.
> Implement jprint -b option

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
Now prints tabs or spaces after levels depending on the -L option when 
printing syntax (-j). It already was done without -j. The text said that
it only has an effect with -j but I thought that it might be of use to 
work without -j and that was done I think yesterday. If this is 
undesired it can easily be fixed.
> Implement jprint -L for -j 

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
What remains is regexp matching as far as matching goes. It should be 
pointed out though that the matching is not complete even besides regexp
and some code will have to change in order to get matches to have values
that are different from the match itself.
These issues also hold for regular (exact) matching as well.
> Implement jprint -s (substring matching)

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
This might have to change more when more of json syntax is printed (for
instance arrays) but for now this is done.
The way it works is a loop that prints the right number of tabs or 
spaces based on the level or depth the matched node is in.
Note that without a match this will not happen. This must be corrected 
later by adding every node as a match so that we don't print the json 
document as a char * but rather by match like if a pattern is specified.
> Implement jprint -I

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_test.c
Do not use strstr() or strcasestr() when finding previously added 
matches as otherwise it will end up adding different matches as the 
same. Put another way, only use the strstr()/strcasestr() functions in 
matching itself not when finding previously added matches.
There still is the problem with the matched string being added as
the name and the value but that'll be worked out in the near future I
hope.
> Fix jprint -s matching

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
Instead of showing the prefix of each pattern (name_arg) matched show just a total count of the matches. This was my intended purpose in the first place when I suggested the option.
> Modify behaviour of jprint -c to match grep -c

- jparse/test_jparse/test_JSON/good/h2g2.json
... with the H2G2 them. Why? Because I believe we should follow the following guideline:
Don't Panic!
:-)
> Add another good json test file

- CHANGES.md
- jparse/jprint.c
- jparse/test_jparse/test_JSON/good/h2g2.json
Don't hard coding in the string the default maximum depth to parse.
Instead it uses the macro JSON_DEFAULT_MAX_DEPTH.
Fixed some wording to try and make things a bit clearer.
> Minor improvements to jprint usage string

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/test_jparse/test_JSON/good/h2g2.json
Implement jprint -P. When this option is disabled the spaces specified still
separate the tokens if printing both name and value. Default is 1 space.
When printing both (without json syntax) print on the same line the name and
value.
Added boolean to indicate that -b was used. Currently this is unused but it
will allow not relying on the spaces being not 0 as the default is 1
(this changed from 0 to 1 as it was always supposed to be 1 space by
default). This boolean is not yet needed but it might be and it's a 
clear way to indicate if the option was used or not.
Make matching printing function a bit more modular by introducing a new
function, jprint_print_match(). Note that the concept of patterns is
incorrect and has to be fixed. Discussion is pending. Also note that
more functions will …
> Implement jprint -P option and modularity

- CHANGES.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/json_util.c
- jparse/test_jparse/test_JSON/good/h2g2.json
When printing a json tree for json type 'null' the print routine showed
NULL. To make it more like JSON and to remove any ambiguity with C's 
NULL I changed it to print 'null'.
Updated jparse and json parser version to 1.0.7 2023-06-22.
> Fix C NULL / JSON null ambiguity in print function

- CHANGES.md
- README.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/json_util.c
- jparse/util.c
When renaming variables in the jprint_match struct checks for two NULL 
pointers were changed to the same pointer checked twice.
> Fix match pointer check

- CHANGES.md
- README.md
- jparse/jprint.c
- jparse/jprint.h
New jprint version is 0.0.26 2023-06-23.
Added some booleans to struct jprint to make it more clear that specific
options are used rather than relying on a uintmax_t not being 0. This 
involved having to rename one uintmax_t to as it was more fitting as a 
boolean.
> Add bools to struct jprint for some options

- CHANGES.md
- README.md
- jparse/jprint.c
- jparse/jprint.h
Add feature test macro _GNU_SOURCE and string.h inclusion to resolve 
implicit declaration of function strcasestr(). This is needed for some 
systems.
> Fix implicit declaration of strcasestr()

- CHANGES.md
- README.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/util.c
This is still a work in progress but a bit of progress has been made 
anyway.
In particular with substring matching:
$ grep num h2g2.json
"number":42,
"number_as_str":"42",
$ ./jprint -P -s -p both h2g2.json num
num : number
num : number_as_str
$ ./jprint -P -s -p n h2g2.json num
num
num
$ ./jprint -P -s -p v h2g2.json num
number
number_as_str
What this means is that what matched is not the same as the pattern 
requested in all cases. Later it will be the actual name and/or value of
the json member but this is not currently possible. Note also that the 
-Y option is not yet working properly which will affect this.
As well the struct jprint_match now has two struct json * nodes: the 
name and value each of which depend upon if searching by value or name 
was requested. Later both will be …
> Improve matching in jprint

- CHANGES.md
- README.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/json_util.c
- jparse/util.c
New jparse version 1.0.8 2023-06-23. 
A problem occurred in vjson_fprint() where it would print the boolean 
indicating if the number was sized as the specific type as the value 
itself. This means that the number would not be printed but instead the  
boolean would be printed cast to the type it is meant to indicate the 
number is.
> Fix display bug in vjson_fprint()

- CHANGES.md
- README.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_test.c
- jparse/json_util.c
- jparse/util.c
Several new functions have been added to print parts of matches (or in
this case characters besides actual matches). In particular the
following functions were added:
bool jprint_print_count(struct jprint *jprint);
void jprint_print_final_comma(struct jprint *jprint);
void jprint_print_brace(struct jprint *jprint, bool open);
These will be useful later for the printing of not just a JSON file if no
pattern requested (which currently is done by just printing the string 
but because of levels and other things like constraints this will have 
to be done differently) but also printing matches. More will be added 
later.
> More jprint match printing modularity

- CHANGES.md
- jparse/Makefile
- jparse/jprint.c
- jparse/man/man1/jprint.1
- jparse/man/man8/jsemtblgen.8
It is incomplete. In particular the options list is incomplete. The
synopsis is correct and the description is a good start (but needs some
work). Examples section is a good start but the commands don't show
correct output yet either except in one condition. Bugs section does not
list these problems as the tool is not finished yet.
I wanted the man page in the repo and it can be discussed and I can also
finish adding the options hopefully in the coming days.
jparse/Makefile updated so that make install will install jprint.1 along
with the other man pages.
> Add initial (incomplete) man page for jprint tool

- CHANGES.md
- jparse/jprint.c
It originally was thought to be -Y type:value but it was changed to be -Y type and then the other part was just a name_arg which is an arg to the program and not part of the option arg.
> Fix -Y usage syntax in jprint usage string

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
This caused a segfault if the check tool does not exist. It might be 
better if the char * is not in the struct jprint but since the program 
is aborted at this point the memory will be freed by the OS anyway so 
it's probably okay.
> Fix use after free in jprint_sanity_chks()

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
New jprint version 0.0.27 2023-06-24.
If -j is used don't make use of -p b or -p both an error. It's only an error if printing of just name or just value is specified (after the -j as -j will set both). Checking for this is just as simple as for -p being used at all and it seems slightly more user-friendly to do it this way.
> Only have -j -p an error if not -p b or -p both

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
In other words jprint_sanity_chks() does a lot more work now. It checks
options combinations, verifies that a path is specified and it exists as
a regular readable file. If this is not true the function will not
return (it will not return on any other error either). It will never
return a NULL pointer (it returns a FILE *) but we check for a NULL
pointer in main() anyway for extra defence. 
It does NOT look at name_args and it does NOT verify it is valid JSON.
Currently that is main()'s job but these things might be moved to other
functions as well.
As the argc and argv need to be shifted inside main() the
jprint_sanity_chks() function takes a int *argc and char ***argv rather
than the usual int argc and char **argv.
> Make jprint options/file checking more modular

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
Move the searching on the command line for name_args to a separate
function (was in main()) which the jprint_sanity_chks function calls.
The reason jprint_sanity_chks() calls it is because some options have to
be checked after name_args are found: -Y requires exactly one name_arg
(!= 1 is an error) and -c cannot be used if a name_arg is specified. As
well no name_arg can be specified if we're printing the entire file 
(this is probably an unnecessary check as an artefact from the removed 
-o option but this does not hurt either).
> Add parse_jprint_name_args() for more modularity

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
The code that was in main() that runs the JSON check tool if -S path
used is now in a new function, run_jprint_check_tool(). The stream for
the pipe is now in the struct jprint. The file contents, the json.file
FILE *, the tool path and tool args are also all in the struct jprint.
This fixes a bug too where the file.json could be printed more than once
if -S was used. For instance doing:
jprint -S /bin/cat h2g2.json
used to print the file three times but now it prints it just once which
I believe is the correct behaviour.
> Fix bug with -S and make it more modular

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
Now quotes are added to strings if printing the entire file, printing 
syntax or if -Q is used. Don't quote strings otherwise.
In the process I discovered that depth was not working right and I fixed
it as well at least as far as what can be tested currently.
> Implement jprint -Q and fix jprint -L

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/man/man1/jprint.1
Although I originally had some use cases it was brought up that it might be not that useful and with the example files that we have nothing is coming to mind that might make it useful so I have removed it.
It should be noted that the jprint_pattern struct (which is not completely correct in concept but it will still exist in some form or another, whether renamed or not, when this is corrected) still has the boolean use_regexp (just as it has use_substrings and use_value) to indicate what kind of search the pattern is (even though it's probably now okay to have them just in the struct jprint it doesn't hurt to have it in the other struct and they might have some use that is not yet shown).
> Remove jprint -G option

- jparse/jprint_util.h
It's still in jprint.h but it probably can be removed now as can probably some of the #includes - but this can be worried about later on. This should fix the warning on GitHub and linux.
> Add back feature test macro for strcasestr

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
Doing this simplifies the printing of levels and tabs by removing duplicate code. Now the indenting and printing levels should work fine though this still does not work for no name_arg as currently that only dumps the entire buffer rather than traversing the tree and printing each node according to the options.
New version of jprint 0.0.29 2023-06-26.
> Fix handling of jprint -L and -I

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/test_jparse/test_JSON/good/JSON_misfeature_number_7.json
This comes from a GitHub comment except I made it slightly less critical
to prevent any possible offence (though I'm sure some would find the 
term 'silly' being applied to json spec objectionable it is not meant to
be and it is silly in numerous aspects anyway).
> Add JSON_misfeature_number_7.json

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/test_JSON/good/h2g2.json
Make sure to check that the match type is JTYPE_STRING before printing
quotes. Whether the match struct needs a type for the name and value or
just the value is TBD later but currently it just has one - the matched 
type.
> Fix to jprint -Q handling

- CHANGES.md
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/test_jparse/test_JSON/good/h2g2.json
A bug in searching for already existing matches was also fixed.
The function add_jprint_match() now takes a char *name_str and char
*value_str and these are used instead of pattern->pattern. The pattern
can now be NULL. If it is then the new jprint->matches list will be
acted on and otherwise pattern->matches list.
Testing of the call to add_jprint_match() where calls are does still
need to be tested more thoroughly (in particular with the name_str and
value_str args) but with the caveat that the value is the same as the
name in the current matches list this cannot be tested as easily.
The purpose of the change to the function is to help with printing the
entire file as there are no patterns (or name_args) when this happens
but until now there was no way to have a match without a pattern …
> Partially fix jprint -Y str

- CHANGES.md
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
For strings and numbers (but see below) the adding of names versus 
values has been corrected. This required a lot of new code and more
modularity is called for but this can be done later. However now one can
get the name or value or both of these types and this goes for the -Y 
type option too.
The caveat is that there might be cases that have not been handled as 
for each type of name there has to be a check for types of values too
and there might be some I missed for numbers (and there might be the
same problem for strings but I am not sure yet). 
Others were not done yet but I wanted this in as it's a
significant accomplishment that will help move forward in the tool. For
that reason I have updated the jprint version again to 0.0.31 2023-06-27.
> Fix adding of value/name matches for num/str

- CHANGES.md
- jparse/jprint_util.c
- jparse/jprint_util.h
The struct now has a type for the name and a type for the value. Although in some cases we can only have one type in some we can determine because a number (for example) cannot be the name so not a string (if it's a string value that's a number that's another matter).
This is not perfect but it does help in some cases and it will be of value later on when both nodes can be passed into the function.
> Improve jprint_match wrt struct json node types

- CHANGES.md
- jparse/json_search.c
- jparse/json_search.h
Part of this was done in the previous commit by accident but additional
fixes were made here and both files have the same comment now.
> Updates to json_search.{h,c} header comments

- CHANGES.md
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/json_search.c
- jparse/json_search.h
Add jprint -R option to disable sub-tree searching
New version of jprint - 0.0.32 2023-06-28.
The purpose of this option will be to allow one to find matches that are
not under a hierarchy of name_args. Although it was originally a 
misunderstanding it was a misunderstanding also in part because I feel 
that there is a great value in having it search in a non recursive way 
(in the sense of two name_args as described elsewhere) and it seems like
a waste of the code I already put in. Since there will be no ambiguity 
there should not be any problem.
The default will be to search in a recursive way but for now that is 
disabled as that feature is not yet implemented.
Fixed a potential memory leak that was discovered at the same time as 
well.
> Add jprint -R option to disable sub-tree searching

- CHANGES.md
- jparse/jparse.h
- jparse/jprint.c
- jparse/jprint.h
- jparse/jprint_util.c
- jparse/jprint_util.h
- jparse/json_search.c
- jparse/json_search.h
- jparse/json_util.c
- jparse/json_util.h
- jparse/man/man3/jparse.3
New jparse and json parser version 1.0.9 2023-06-28.
By matched node string I refer to the string that matched in the parser 
either decoded or not depending on the boolean encoded. This will be
used in jprint to prevent having to use what amounts to almost the same
code repeatedly.
Returns a read-only string. It can return a NULL pointer so it's the
responsibility of the caller to check.
The function is:
char const *json_get_type_str(struct json *node, bool encoded)
and is in json_util.c.
Updated jparse.3 for the new function.
> Add new json function to get matched node string

- CHANGES.md
- jparse/jprint.c
- jparse/jprint_util.c
- jparse/jprint_util.h
Make use of the function json_get_type_str() for strings and numbers. More will follow another time as more cases are added.
For now removed -R as it is thought that other things have to be considered.
> Modularise jprint strings and number matching

- jparse/test_jparse/jparse_test.sh
There was a debug message that was outside a check of the verbosity level and the script also erroneously referred to the non-existent variable pass_test in the same function which tests error locations (run_location_err_test()). The test must always fail which really means that jparse must return non-zero and have the exact same error message as the respective error file in jparse/test_jparse/test_JSON/bad_loc, one error file per JSON file in the same directory.
> Debug log fix in jparse_test.sh

- CHANGES.md
- jparse/json_util.c
Something that might or might not be an issue is that this will classify the number as no common size because it cannot be converted likely due to being too big. It is not clear to me what size should be printed as.
> Add to vjson_fprint() code to print number as_str

- CHANGES.md
- jparse/json_parse.c
- jparse/json_parse.h
- jparse/json_util.c
This is used to simplify checking if the node is valid after conversion
(or attempting to convert). If either item->converted or item->parsed is
true it is valid JSON. It does not mean that it could be converted.
> Add macro VALID_JSON_NODE

- CHANGES.md
- jparse/json_parse.c
- jparse/json_parse.h
- jparse/json_sem.c
- jparse/json_sem.h
- jparse/json_util.c
This function is just like sem_node_valid_converted() but it acts on the
parsed boolean rather than the converted boolean.
It is not yet used as I am not sure where it needs to be used or if it 
needs to be used here.
> Add sem_node_valid_parsed() to json_sem.c

- CHANGES.md
- jparse/jparse.h
- jparse/json_parse.h
- jparse/json_sem.c
- jparse/json_sem.h
- jparse/json_util.c
- jparse/man/man3/jparse.3
- jparse/test_jparse/jnum_chk.c
- soup/chk_validate.c
- soup/entry_util.c
More use of macros added in commit
1e4240bf00fd3abe7e695c0eb302bd682dae12ea.
Renamed sem_node_valid_converted() to sem_node_valid() and update it to
use the macro CONVERTED_PARSED_JSON_NODE (for non-numbers) and 
VALID_JSON_NODE for numbers. For numbers either converted or parsed can
be true: if neither are true it is an error. For other types both 
converted and parsed have to be true.
Unless I am mistaken this commit fully resolves the issue #752. If this
is so I will then update the jparse and json parser version to 1.1.0 but
in case this is not done yet I haven't yet.
> Resolve most or all of issue #752

- CHANGES.md
- jparse/jparse.h
- jparse/json_sem.c
- jparse/json_util.c
- jparse/test_jparse/jnum_chk.c
New JSON parser and jparse version 1.0.12 2023-07-15.
Add more checks for parsed bool in structs if converted is false. In the case of numbers this was already done but for others it was not. However the checks now check (except for numbers as they're allowed to be different) that both converted and parsed are true. If only one is true we print a warning.
Improve how numbers are printed and how strings are printed. For numbers it's messages improved and typo fixed. For strings there are new flags: 'c' for converted and 'p' for parsed. In the case of strings we do explicitly check for either or of converted or parsed but it might be more correct to be like the others: check for both true and warn if only one of them is true.
> More code for json struct parsed bool

- CHANGES.md
- jparse/jparse.h
- jparse/json_parse.h
- jparse/json_sem.c
- jparse/json_util.c
- jparse/man/man3/jparse.3
- jparse/test_jparse/jnum_chk.c
Three new macros have been added to check JSON nodes' converted and 
parsed booleans.
The CONVERTED_PARSED_JSON_NODE macro checks that both are true.
The CONVERTED_JSON_NODE macro checks that only converted is true.
The PARSED_JSON_NODE macro checks that only parsed is true.
These macros are now used in jparse/json_util.c but other files will be
checked and if necessary updated.
> Add new JSON node helper macros

- CHANGES.md
- jparse/jparse.h
As the enhancement issue 'add parsed boolean to the JSON parser' is in fact resolved as of commits I made earlier today I have updated the version to 1.1.0 as this is a significant change. This should allow issue #752 to be closed as complete.
> Make jparse/json parser version 1.1.0

- .gitignore
- CHANGES.md
- jparse/Makefile
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_test.c
- jparse/jfmt_test.h
- jparse/jfmt_util.c
- jparse/jfmt_util.h
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_test.c
- jparse/jnamval_test.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/json_util_README.md
- jparse/jval.c
- jparse/jval.h
- jparse/jval_test.c
- jparse/jval_test.h
- jparse/jval_util.c
- jparse/jval_util.h
- jparse/test_jparse/jfmt_test.sh
- jparse/test_jparse/jnamval_test.sh
- jparse/test_jparse/jval_test.sh
- jparse/util.c
An important key term is TEMPORARY PLACEHOLDER. The files are actually
copies of what were once jprint related but for each tool jprint / 
JPRINT were changed to their new tool counterparts. This is done this 
way because some of the code is common and this way they are in the
repo. A lot of code will be removed but some will be kept. Much will 
also be changed. Option parsing in particular is useful but this will
also have some changes.
As it will take more work to get them in order I have kept the other
things in too for now but this GREATLY simplifies starting the tools
which seems like a worthy thing to do.  A very nice way that this
simplifies starting the tools is that the parsing of the JSON file is
already done. Along with this some of the options being the same and 
some of the …
> Add placeholder JSON tools source and header files

- jparse/json_util_README.md
Just like with jfmt I believe that the -o ofile option is useful for the other tools as well and since it's not used by the other tools for something else I have added it to the json_util_README.md document.
The code for this already exists (as of yesterday) in jfmt (and if memory serves me right it's complete). It's almost completed in jval but as I have other things to do with that tool it's not being committed yet.
> Add -o option to common json tool options

- CHANGES.md
- jparse/jparse.h
- jparse/json_util.c
The function used the wrong macro so that before printing the number it checked if only converted was true (so parsed is false) when it should check for if both are true. The other condition in the else if needs to (and did and still does) check for if converted is false and parsed is true meaning the number is valid but cannot be represented in a C type.
This was discovered by issue #785 in part but also because the file used as an example did not trigger a problem with jval or jnamval.
This does not resolve the issue noted, #785, but it at least will allow the file to be used in the way it needs to be. The issue is an enhancement as much as it is a bug.
> Fix bug in vjson_fprint for number conv checks

- jparse/json_parse.h
They now check that the node != NULL. They look now like:
#define PARSED_JSON_NODE(item) ((item) != NULL && ((item)->parsed == true))
#define CONVERTED_PARSED_JSON_NODE(item) ((item) != NULL && (((item)->parsed == true) && ((item)->converted == true)))
#define VALID_JSON_NODE(item) ((item) != NULL && (((item)->parsed == true) || ((item)->converted == true)))
Although the explicit check of == true for booleans is not my style I kept them in as looking at the macro without looking at the structs it might not be as clear that it's a boolean but this way it's clear.
> Improve JSON validity convenience macros

- CHANGES.md
- jparse/json_parse.h
- jparse/json_util.c
In vjson_fprint() the node type JTYPE_UNSET was printing the json type 
name but it passed to the function the node itself rather than the node
type.
> Fixed fprintf parameter in json_util.c

- CHANGES.md
- jparse/jparse.h
- jparse/json_parse.h
- jparse/json_util.c
As parsed and converted booleans are not strictly part of the numbers or
strings but rather just booleans indicating if it's validly parsed and 
converted these boolean flags ('p' and 'c') now are suffixed with a ':'.
If both are true then it will look like 'p,c:' but if just parsed is
true, for example, it will look like 'p:'.
Originally I had the thought of comma separating all flags but this 
would be problematic as for each one it would have to check if there is
another flag to print and that would greatly complicate things as there
are a lot of flags to inspect.
> Improve parsed,converted flags in debug output

- CHANGES.md
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/jparse.h
- jparse/json_parse.h
- jparse/json_util.c
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
- jparse/jval_util.h
As the options can be specified more than once we need a list of the 
options parsed. I am still not clear on when it's OR or AND but that can
be figured out later.
Unfortunately the -n mode does not work correctly in that checking for 
numbers being converted seems to be broken, seemingly from a change in
the convenience macros. I will have to address this another time. The -S 
option is tested meaning added to list and freeing the list works fine.
It is possible that I made a mistake in the -n processing even though
they're mostly the same.
Some details might change later on but with this I believe all options
are parsed completely. This of course could also change but I believe at
this time it's done.
> jval and jnamval -S and -n options now a list

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_test.c
- jparse/jfmt_test.h
- jparse/jfmt_util.c
- jparse/jfmt_util.h
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_test.c
- jparse/jnamval_test.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/json_util.c
- jparse/json_util.h
- jparse/jval.c
- jparse/jval.h
- jparse/jval_test.c
- jparse/jval_test.h
- jparse/jval_util.c
- jparse/jval_util.h
The struct jfmt, struct jval and struct jnamval now have a single 'struct json_util common' which has the variables that are common to all three tools in json_util.h. Code moved to json_util.c.
The structs (jfmt|jval|jnamval)_number are now json_util_number in json_util.h and the associated code has been moved to json_util.c.
The code for the common -L option to the three tools has also been moved to the json_util.c file.
Any other common (to all three tools) options not mentioned here have also been moved to json_util unless some were missed by accident. I don't believe that is the case but if there are any they will be found and moved accordingly.
The options common to just jval and jnamval have NOT been moved to common structs just yet. That will happen in another commit.
Now why …
> Move common json tool variables to common struct

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_test.c
- jparse/jfmt_test.h
- jparse/jfmt_util.c
- jparse/jfmt_util.h
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_test.c
- jparse/jnamval_test.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/json_util.c
- jparse/json_util.h
- jparse/jval.c
- jparse/jval.h
- jparse/jval_test.c
- jparse/jval_test.h
- jparse/jval_util.c
- jparse/jval_util.h
Although the code for both jval and jnamval that is common to each other
are in json_util now only jval uses that code for now. Some code is the
same but has some minor functional differences and that code has not
been moved over. It might be that it can be later on and at least the
match functions can be later on but the parsing maybe not. This is not
really a problem.
jnamval has options that are not in jval and so in addition to moving
the common code to json_util (which again is not yet done) the code for
that also remains (and will always remain) in jnamval.[ch].
> Update jval common code to be in json_util

- CHANGES.md
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
That is code that is common to both jval and jnamval that still had its own copy in jnamval to json_util.
Some code is the same but has some minor functional differences and that code has not been moved over. It might be that it can be later on and at least the match functions can be later on but the parsing maybe not. This is not really a problem.
jnamval has options that are not in jval and so in addition to moving the common code to json_util the code specific to jnamval remains and will always remain in jnamval*.[ch] itself.
Things not thought of notwithstanding I believe that this really finally does complete command line processing - unless of course the code that has minor functional differences should be moved to json_util: that's not certain as it would require a new variable in …
> Update jnamval common code to be in json_util

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_util.c
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/json_util.h
- jparse/json_util_README.md
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
New version of all three tools: 0.0.5 2023-07-26.
The tools can now work with:
echo '"test"' | ./jfmt
echo '"test"' | ./jval
echo '"test"' | ./jnamval
and also:
./jfmt -
./jval -
./jnamval -
This uses parse_json() instead of parse_json_stream(). We already have
the contents of the stream so this is okay.
Add to json_util struct a char *, json_file_path, which is the file path
specified at the command line.
Check that file path is not empty.
> Fix read from stdin in jfmt, jval and jnamval

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_util.c
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_test.c
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.ref.c
- jparse/json_util.h
- jparse/json_util_README.md
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
New jparse and json parser version - 1.1.3 2023-07-26.
Now the check if filename == NULL in parse_json_stream() is further up
in the function. The purpose was to if NULL make it read from stdin. The
problem is that if filename is NULL the odds are that stream is also
NULL which means that the making it stdin would never occur.
Also do not call fd_is_ready() if stream is stdin. Changing this fixes a
problem where in some cases the stream would not be read from if stdin.
> Fixes when filename is NULL in parse_json_stream()

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/jnamval_util.h
- jparse/json_util_README.md
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
- jparse/jval_util.h
- jparse/man/man1/jval.1
New versions of jfmt, jval and jnamval with some minor bug fixes and enhancements: 0.0.6 2023-07-28, 0.0.7 2023-07-28 and 0.0.6 2023-07-28.
Fixed bug where redirecting stdout to /dev/null resulted in an error:
Warning: vfpr: called from jfmt: vfprintf returned: 56 <= 0: errno[25]: Inappropriate ioctl for device
For jval and jnamval the functions parse_jval_args() and parse_jnamval_args() have been updated to take the proper struct, a pointer to argc from main() and a pointer to argv from main(). That is a int * and a char ***. The functions increment argc/argv past the file name so that main() can check if there are any args without having to worry about argv[0]. The function (not main() - the parsing ones) now show debug information about the args shown. Currently the debug level is 0 so …
> Minor fixes and enhancements to jfmt/jval/jnamval

- CHANGES.md
- jparse/test_jparse/Makefile
With this commit the test_jparse/Makefile now runs test_jparse/print_test as per the suggestion on GitHub. It does NOT redirect stdout or stderr to /dev/null so extra output will now be shown in make release/make prep/make test.
> Add print_test to make test in jparse/test_jparse

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
- jparse/test_jparse/Makefile
In jfmt, jval and jnamval when printing the file contents (which is done
in temporary way) use fpr() not fprintf() now that the tty issue is
resolved.
If jval -c/-C or jnamval -c/-C is used without an arg is a command line
error.  This is done in the sanity check function of each tool.
> fprintf() -> fpr() in jval and jnamval

- CHANGES.md
- jparse/test_jparse/print_test.c
Now checks the file descriptor versions of the printf functions.
Added 'not_reached();' after an error function was called.
There might have been other improvements or fixes.
New version 1.0.1 2023-07-30.
> Improve, typo fix and bug fix print_test.c

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_util.c
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/json_util.c
- jparse/json_util.h
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
New version for all tools 0.0.9 2023-07-31.
The optarg 'color' is aliased to 'colour'. Other options are 'default' and 'pedantic'. Debug output (with DBG_NONE' which has to change - later on) is added based on the optarg.
The option has NOT been added to the man pages. This will come later either later today or another day. Most likely another day.
Add missing setting of variables in alloc_jnamval().
> Add -F format to jfmt, jval and jnamval

- CHANGES.md
- jparse/json_parse.h
- jparse/man/man3/jparse.3
The macros were changed but the man page was not updated.
> Fix jparse.3 for converted/parsed booleans macros

- CHANGES.md
- dbg/dbg.c
- dbg/dbg.h
- dbg/dbg_example.c
- dbg/man/man3/dbg.3
- dyn_array/Makefile
- dyn_array/dyn_test.c
- jparse/jparse.h
- jparse/util.c
- jparse/util.h
Since the debug facility is the one that uses a verbosity_level that I added here I have moved the function from jparse/util.c to dbg/dbg.c.
The dbg.3 man page has been updated with this and also some other improvements. There is a recursive reference to the man page for parse_verbosity(3) in the man page just for fun.
The dbg related changes have already been added to the dbg(3) repo as a pull request.
The dbg_example.c file that I wrote for this repo and the dbg(3) repo has also been updated with a comment change, referring to not strtol(3) but rather the parse_verbosity(3) function.
The dyn_array/dyn_test.c no longer has the parse_verbosity() function as this is in the dbg(3) facility which the dyn_array facility uses.
> Move parse_verbosity(3) to dbg facility

- CHANGES.md
- soup/location.h
- soup/location_main.c
- soup/location_tbl.c
- soup/location_util.c
- soup/man/man1/location.1
New version of location is 1.0.1 2023-08-03.
New option -s searches by substring rather than exact match.
New option -a shows all matches. Only useful with -s as otherwise it's an exact match.
To implement -a we have two new re-entrant functions:
char const *lookup_location_name_r(char const *code, size_t *idx, struct location **location, bool substrings);
char const *lookup_location_code_r(char const *location_name, size_t *idx, struct location **location, bool substrings);
These are the same as lookup_location_name() and lookup_location_code() except that they allow for calling them additional times to get the next match. If idx != NULL set *idx to the position + 1 for the next call. If location != NULL then set *location to the matching location. Then in location's main() (see …
> Improve location tool - make more generally useful

- CHANGES.md
- soup/location_main.c
- soup/man/man1/location.1
New version 1.0.2 2023-08-04.
Change -N to -n.
Always use re-entrant version of the lookup functions as this allows for proper showing of both name and code whether or not one is using -s or -n. If -a we still show all (as before) but without -n we previously showed both name and code like code ==> name when it should only show both if verbosity level is > 0. Note that the chkentry tool SHOULD NOT and DOES NOT use the re-entrant versions.
Use parse_verbosity() for parsing the -v option.
Updated man page with an example added and updating -N to -n.
> Bug fixes in location tool wrt -a and -s options

- CHANGES.md
- mkiocccentry.c
Missing ',' at end of lines in para() made for long lines and merged words.
Moved the call above the warning about ignoring warnings as that warning says no more warnings will be shown so the -y warning should be shown first.
> Fix mkiocccentry -y message

- CHANGES.md
- jparse/jfmt.c
- jparse/jfmt.h
- jparse/jfmt_util.c
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/json_util.c
- jparse/json_util.h
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
- jparse/man/man1/jfmt.1
- jparse/man/man1/jnamval.1
- jparse/man/man1/jval.1
- tmp/TODO.md
The option now looks like:
-F fmt	Change the JSON format style (def: use default)
tty	    When output is to a TTY, use colour, otherwise use simple
simple	    Each line has one JSON level determined by '[]'s and '{}'s
colour	    Simple plus ANSI colour syntax highlighting
color	    Alias for colour (colour excluding you :-) )
1line	    One line output
nows	    One line output, no extra whitespace
Updated man pages for this option as well as a typo fix in jnamval.1 (an option letter was incorrect making it so that the example had no explanation).
Updated tmp/TODO.md - something that has to be done after the specs of these tools are finalised is to make sure common options are in the same order ahead of the other options both in usage strings and man pages.
The -F option is not yet added to …
> Update jfmt, jval and jnamval -F option

- CHANGES.md
- Makefile
The link that was used, https://github.com/lcn2/jparse.git, is actually a fork of the repo that I set up, which will be populated with jparse/ after it is more thoroughly tested in this repo. That is located at https://github.com/xexyl/jparse.git.
> Fix make rule jparse.clone

- CHANGES.md
- jparse/jnamval.c
- jparse/jnamval.h
- jparse/jnamval_util.c
- jparse/json_util.c
- jparse/json_util.h
- jparse/jval.c
- jparse/jval.h
- jparse/jval_util.c
New version of both tools is 0.0.14 2023-08-09.
Fixed the lists of -S and -n option parsing. For now it should just be a string that's strdup()d. The operators are in the list in the order specified, one list for strings and one list for numbers. This can be changed to a single list later on if necessary (as I suspect it might need to be but the way it is now is set up as two which is what I'm operating under).
The -S and -n lists are by default ORed but an option that is to make them AND is to be added. This will require some discussion first so that is not yet added.
The function that frees the -S and -n lists in jval and jnamval is now in json_util.c as they are actually in a struct common to both jval and jnamval. The functions that free them in jval_util.c and jnamval_util.c simply …
> Fixes to jval and jnamval -S and -n options

- test_ioccc/test_txzchk/bad/entry.test-9.9876543211.txt
- test_ioccc/test_txzchk/bad/entry.test-9.9876543211.txt.err
The new fake tarball has files with each new forbidden file:
- README.md
- index.html
- inventory.html
- prog
- prog.orig
- prog.orig.c
> Add test case for forbidden tarball files

- CHANGES.md
- mkiocccentry.c
- soup/entry_util.c
- soup/entry_util.h
- test_ioccc/test_JSON/info.json/bad/info.manifest-README-md.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-index-html.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-inventory-html.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-prog-alt.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-prog-orig-c.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-prog-orig.json
- test_ioccc/test_JSON/info.json/bad/info.manifest-prog.json
- txzchk.c
Each forbidden filename in the manifest now has a separate file to check
it including prog.alt. The -34.json file was also updated to have 
prog.alt as an extra filename though it might be better to also check 
this for other files too if this is not done (been too long and too many
other changes in the other repo to recall if this is done or not).
That means that under test_ioccc/test_JSON/info.json/bad individual 
files that have an extra file with the names of:
- README.md
- index.html
- inventory.html
- prog
- prog.alt
- prog.orig
- prog.orig.c
have been added. Unless other files have to be added later to the list 
of disallowed filenames or there needs to be a more specific check in 
mkiocccentry for filenames of the required files this should complete 
the disallowed and required …
> Add bad manifest filenames tests

- CHANGES.md
- mkiocccentry.c
- soup/entry_util.c
- soup/entry_util.h
- txzchk.c
Add another forbidden file name in submissions: prog.alt (prog.alt.c is allowed).
Modularise the checks for invalid filenames in entries. For instance in check_extra_file() there's no need to check each extra filename and then give the same error message changing the macro of the filename that's disallowed when we can just print the string being tested against. The only difference is that there's one if (with multiple checks) and instead of duplicating the same error message we just print it once with the string being tested against. Note that there are two sets of checks: one for extra files being required filenames and another for disallowed filenames.
Make sure to use the macros for the filenames, not the literal strings (e.g. use PROG_FILENAME not "prog").
Check filenames in …
> Modularise check + add forbidden filename

- Makefile
- test_ioccc/test_txzchk/README.md
- test_ioccc/txzchk_test.sh
The script test_ioccc/test_txzchk.sh now has a new option: -B. This rebuilds the test error files. The script prompts the user to verify that everything is correct. If it does not get a YES (case sensitive!) it will exit 3 (invalid command line). If this is the case the rest of the rule is not run so no notice about adding and committing the new or updated files.
The rule in the Makefile now is called (the previous one still exists though): rebuild_txzchk_test_errors.
The test_ioccc/test_txzchk/README.md file has been updated for this (there was also an error in it but that text has been removed as the make rule tells the user what to do which is what the incorrect text was only of course the text is now corrected).
> Improve rebuilding txzchk test error files

- CHANGES.md
- mkiocccentry.c
- soup/entry_util.c
- soup/utf8_posix_map.c
- soup/utf8_posix_map.h
- test_ioccc/utf8_test.c
- txzchk.h
There was also a typo fix in txzchk.h: the words plus and safe in the function posix_plus_safe() were swapped.
No versions needed to be changed because no code functionality was changed as the regexp was allowed already.
> Fix comments and strings about author_handle regex

- CHANGES.md
- soup/location.h
- soup/location_main.c
- soup/location_tbl.c
- soup/location_util.c
To match what was done in chkentry I have also done it in the location tool code in the same way that was done in the chkentry code and header files.
Also in CHANGES.md I removed a reference to '@xexyl' (a fun pun is attributed to me still, however). This is because otherwise every time a release is made GitHub would tell me I was mentioned which is both confusing (as it's buried deeply) and unnecessary (plus if ever I am mentioned I might otherwise miss it). This problem is actually how I discovered the missing credits mentioned in this commit.
> Add some credits to location code

- CHANGES.md
- README.md
- soup/location_main.c
- soup/man/man1/location.1
Updated LOCATION_VERSION to "1.0.4 2024-05-22" from "1.0.3 2024-03-03".
Fixed usage string in location_main.c so that it shows that one can specify more than one location.
The location(1) tool was missing from the README.md and this seems like a good tool to have there. There might be other tools missing too but that can be determined and if necessary fixed another time.
The man page had a typo as well: in SYNOPSIS it had lookup when it would probably be more correct to say 'look up': the former is the facility and the retrieval of information but one would 'look up information' or in this case 'look up location information' or to be more specific 'look up ISO 3166 codes, location names by name (substring, full) or print the entire table' (this was expanded as well as it was missing some …
> Documentation fixes/additions for location(1)

- Makefile
- dbg/Makefile
- dyn_array/Makefile
- jparse/Makefile
- jparse/test_jparse/Makefile
- soup/Makefile
- test_ioccc/Makefile
It was stated that this would happen sometime in 2023 and we're almost at July in 2024. One of the problem systems that required c11 will be reaching EOL (thanks to Red Hat) on 30 June 2024 so it seems to not be a problem. Rocky linux appears to work with c17 (although I only tested the top level Makefile for that but it should work fine).
> Change C standard to c17

- iocccsize.h
- soup/rule_count.c
- test_ioccc/iocccsize_test.sh
My initial attempt to address this issue.  I'm not yet able to duplicate the failure.  This change still makes sense regardless so worth merging and testing on those platforms with compiler options that failed.
> GH-873 Fix potential keyword buffer overflow off by 1 byte causing stack corruption.

- soup/Makefile
If one were to do make clobber iocccsize it would not build soup/limit_ioccc.sh. It would, however, build the soup.a library, and since it's a useful file to be built, and since tools rely on soup.a, the soup.a rule now makes limit_ioccc.sh.
Doing it this way prevents having to add something like:
${MAKE} -C soup limit_ioccc.sh
to all the rules in the Makefile and now one can do:
make clobber iocccsize
./test_ioccc/iocccsize_test.sh
and have it run okay. Without something like this (that can probably be improved upon / cleaned up) one would have to build everything in order for the file to be built (which maybe indicates a better procedure could be devised).
> Fix limit_ioccc.sh not being generated at times

- .github/ISSUE_TEMPLATE/bug_report.yml
- Makefile.example
The CSILENCE+= and CWARN+= were commented out.
> Fix Makefile.example for gcc specifics

- jparse/README.md
- jparse/json_util_README.md
These files now state that the tools jfmt, jval and jnamval are VERY INCOMPLETE and will be HEAVILY MODIFIED and will be almost entirely rewritten. This is much quicker than updating the code and header files to note this fact but it feels useful as they still exist.
When the tools are rewritten the notice will be removed from both files and jparse/README.md will refer to them again, briefly giving an overview (or at least referring to the other document) and how to render the man pages.
This is partly done as I have updated the README.md in the jparse repo itself to refer to the README.md here to give people a better idea, noting that although one can certainly use the parser/library if they wish, it is still tied to the mkiocccentry repo.
> Update jparse/README.md and json_util_README.md

- .github/workflows/test.yml
... or actually the new make slow_release. This is a test to see if it can install flex and bison and generate the jparse backup files in case the .l/.y files are modified and by accident make release or make parser is not run.
> Add make release to GitHub workflow

- Makefile
The problem, it would appear, is that in trying to be done for the day, I forgot to commit the Makefile, which would mean the rule could not be run since it was not there.
> Fix (hopefully) workflow of make release

- .github/workflows/test.yml
This is needed for the make slow_release. It is not an error if it is not installed but since it's used it might be good to have it work.
> Add clone/install of independ to workflow

- Makefile
As the GitHub repo was changed in the workflow it should also refer to it in the Makefiles.
> Fix picky rule in Makefiles

- CHANGES.md
- dbg/Makefile
- dyn_array/Makefile
- jparse/Makefile
- jparse/test_jparse/Makefile
- soup/Makefile
- soup/entry_util.c
- soup/limit_ioccc.h
- test_ioccc/Makefile
This is part of chkentry(1) - see soup/entry_util.c for details on this
function.
> Add constants for test_formed_timestamp_usec()

- CHANGES.md
- jparse/json_sem.c
In some of the functions sem_member_value_*() (those that validate JSON parse node types) the error message (if the type was wrong) reported incorrectly the type expected and in particular all of them suggested the type should be JTYPE_BOOL but none of the functions were for booleans (though all were for numbers I think).
> Fix a few error messages in jparse/json_sem.c

- FAQ.md
Added version to FAQ - first version is 28.0.0 2024-07-31 (same format
to the temp-test-ioccc repo but since the version is just being added it
is at 28.0.0).
Removed FAQs about how to use the tools in favour of just one FAQ about
how to participate in the contest. This FAQ links to the proper FAQs in
the temp-test-ioccc repo (the rendered html) with the note that the
links will have to be updated once the great fork merge happens (this is
in XXX html comments), the rules and the guidelines. This way the FAQ
here focuses on how to obtain, compile and get help on these tools (as
well as if necessary report bugs though that is also in the other repo's
FAQ). Also the information is not duplicated.
It is however unclear to me if the FAQ in the other repo should just 
refer to the FAQ here: …
> Many updates and fixes to FAQ

- CHANGES.md
- soup/oebxergfB.h
- soup/version.h
This is for the .entry.json and author_handle.json files in the website. These will be used in the hopefully not too distant future but is pending further discussion.
> Add ENTRY_VERSION and AUTHOR_VERSION strings

- .gitignore
There is a problem with GitHub where if one pull request is closed then
accepting ones that come later will merge the closed pull requests. It
is my belief that this only happens if the maintainer closes it; if the
submitter closes it it does not seem to be a problem.
This pull request is the same as a pull request I just closed except the
line order has been swapped. This is not a perfect test and it entirely
depends on the order GitHub does merging (one might think that it would
be the order merged but perhaps it's not that - we do not know as it
should not be happening in the first place).
The diff of THIS commit is:
-.*.sw[a-zA-Z0-9]
.sw[a-zA-Z0-9]
+.*.sw[a-zA-Z0-9]
which means that if all is okay (after this is merged), the glob:
.sw[a-zA-Z0-9]
should come before the glob: …
> Update .gitignore and test GitHub PR issue

- .gitignore
The globs are now:
.sw[a-zA-Z0-9]*
.*.sw[a-zA-Z0-9]*
It is unclear if the file I have in my directory, '.swox', is actually a vim swap file (it happens to be empty which suggests it is NOT a vim swap file) but the format of vim swap files (no longer sure on vi(1) but certainly vim(1)) is .sw[a-z] and .*.sw[a-z] at the very least but it might end up with more than one letter after the third letter (the upper case and digits in the range is in case it also goes that far - I do not know as I never checked the source code but this change seems like a good idea anyway).
> Fix .gitignore wrt vim swap files

- CHANGES.md
- chkentry.c
- chkentry.h
- jparse/util.c
- jparse/util.h
- soup/version.h
As this function is useful for more than just chkentry.c and more than just JSON (though this is all it's used for currently) it has been renamed and moved to jparse/util.c.
This commit is, although useful, not critical at this time. No versions have changed because it is not clear yet what version strings should be changed and because this might not (yet) warrant a new release.
> Move open_json_dir_file to open_dir_file (util.c)

- CHANGES.md
- test_ioccc/hostchk.sh
With the recent updates to the inclusion of the different repos and the MKIOCCCENTRY_SRC a problem in linux for hostchk.sh had to be resolved. This might also be a problem in macOS but since the libraries were already installed this is not detected (it seems that in linux if the other libraries were installed this also was not a problem).
There still exists an issue with building, however, as the make dependencies have system paths (cc -MM will solve this so it might be the way independ works but this is not clear to me at this time). Nonetheless the hostchk.sh should at least now work.
New version of hostchk.sh is 1.0.2 2024-08-28.
> Fix hostchk.sh

- CHANGES.md
- Makefile
- dbg/Makefile
- dyn_array/Makefile
- jparse/Makefile
- jparse/test_jparse/Makefile
- soup/Makefile
- soup/version.h
- test_ioccc/Makefile
Rename dbg.a, dyn_array.a and jparse.a to libdbg.a, libdyn_array.a and libjparse.a, respectively. These respective repos have had the respective change done as well (well the jparse one has not been committed yet as it needs the other libraries in order to work).
This is important for the jparse repo (not the jparse/ subdirectory here though this has also been updated) to be usable outside this repo without having to have ../dbg and ../dyn_array directories containing the correct respective libraries. The jparse repo
(https://github.com/xexyl/jparse) still has to be updated (and there might be some additional changes here as well) but that cannot happen until the dbg and dyn_array repos have also had this done (or rather merged).
The Makefile does NOT use -ldbg, -ldyn_array or -ljparse …
> Rename library filenames for external repos

- CHANGES.md
- dyn_array/Makefile
- jparse/.gitignore
- jparse/Makefile
- jparse/README.md
- jparse/jparse.h
- jparse/jparse_main.h
- jparse/jsemtblgen.h
- jparse/json_parse.c
- jparse/json_parse.h
- jparse/json_sem.h
- jparse/json_util_README.md
- jparse/jstrdecode.h
- jparse/jstrencode.h
- jparse/man/man3/jparse.3
- jparse/man/man3/json_dbg.3
- jparse/man/man3/json_dbg_allowed.3
- jparse/man/man3/json_err_allowed.3
- jparse/man/man3/json_warn_allowed.3
- jparse/man/man3/parse_json.3
- jparse/man/man3/parse_json_file.3
- jparse/man/man3/parse_json_stream.3
- jparse/test_jparse/Makefile
- jparse/test_jparse/jnum_chk.h
- jparse/test_jparse/jnum_gen.h
- jparse/util.c
- jparse/util.h
- jparse/verge.h
With recent updates to the jparse repo
(https://github.com/xexyl/jparse) there was a need to sync that repo to
the jparse/ subdirectory. No code changes were made and the only
functionality changes made are that a few more header files are
installed (and now into a subdirectory - /usr/local/include/jparse) and
an uninstall rule was added (for those who wish to deobfuscate their
system a bit :-) ). The uninstall rule in the top level Makefile (this
repo) does not run make uninstall in other directories but perhaps it
should.
Did the following steps to make sure things are okay:
git status
make release
make clobber
make jparse.help
make jparse.recreate_clone
make jparse.update_from_clone
git status
make release
.. and all is good.
Updated the repo release version to "1.5.6 2024-08-31".
> Sync jparse subdirectory from jparse repo

- CHANGES.md
- FAQ.md
- Makefile
- README.md
- soup/Makefile
- soup/version.h
- test_ioccc/Makefile
Add to Makefiles the 'PREFIX' variable to allow for installing to a different location than the default /usr/local.
Added some uninstall rules to the Makefile in a number of subdirectories. The external repos that are synced to this repo have not had any direct changes as those repos first need those rules (which will be done soon). This is also why the top level Makefile does not run 'make uninstall' in those subdirectories. Once these are all done the top level Makefile can have a simpler uninstall rule.
Along the lines of silencing (non-verbose) install in the install rule one may now do the same with the uninstall (instead of 'INSTALL_V' it is 'RM_V'). This is only done to be congruent with the install rule.
Updated the MKIOCCCENTRY_REPO_VERSION to "1.5.7 2024-09-01".
> Improve Makefiles (install, uninstall rules)

- CHANGES.md
- chkentry.c
- jparse/jparse.h
- mkiocccentry.c
- test_ioccc/fnamchk.c
- txzchk.c
As the json parser is now in its own repo
(https://github.com/xexyl/jparse) it seems like a good idea for the tools here to tell us what version is linked in in the case that there is a divergence (which can happen though it is not necessarily likely).
At the same time, because the parser is now in its own repo, the version of both the tool jparse (which is not in -V as it's not needed) and the library have been updated.
> Add to -V option json parser version

- jparse/.gitignore
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.ref.c
- jparse/jparse_bug_report.sh
- jparse/jparse_main.c
- jparse/json_README.md
- jparse/man/man1/jstrdecode.1
- jparse/man/man1/jstrencode.1
- jparse/man/man8/jnum_chk.8
- jparse/man/man8/jnum_gen.8
- jparse/man/man8/jsemcgen.8
- jparse/man/man8/jsemcgen.sh.8
- jparse/man/man8/jsemtblgen.8
- jparse/man/man8/jstr_test.8
- jparse/man/man8/run_bison.8
- jparse/man/man8/run_bison.sh.8
- jparse/man/man8/run_flex.8
- jparse/man/man8/run_flex.sh.8
- jparse/man/man8/verge.8
- jparse/test_jparse/Makefile
- jparse/test_jparse/jnum_chk.c
- jparse/test_jparse/test_JSON/bad_loc/12345678-1234-4321-abcd-1234567890ab-2-info.json.err
- jparse/test_jparse/test_JSON/bad_loc/open-brace-unbalanced-quotes-comma.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-0-info.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-1-auth.json.err
- jparse/test_jparse/test_JSON/bad_loc/unquoted-name.json.err
- jparse/test_jparse/test_JSON/bad_loc/vtab_comma.json.err
It was decided that the jparse error reporting could be improved. This was done in the following ways:
- If verbosity level is > 0, then it will show the invalid token and hex value of that token (along with the line and column).
- If verbosity is not specified, then it will just show the syntax error (the bad token with the line and column) and then the warning that the JSON tree is NULL (just like if verbosity specified) and then the error message (from jparse(1) itself).
The error files in the bad_loc have been updated as now the error output has changed.
Updated jparse(1) version to 1.1.6 2024-09-07.
The man pages also now refer to the jparse repo, not the mkiocccentry repo.
> Sync jparse/ from jparse repo (again)

- .github/ISSUE_TEMPLATE/enhancement.yml
There have been many issues opened that are enhancements rather than a bug report or something else so it seems fitting that there should be an enhancement issue template (that adds the enhancement tag). One might even say that I added this because I had an issue with the issues. :-)
This comes directly from the jparse repo
(https://github.com/xexyl/jparse/).
> Add enhancement issue template

- .github/ISSUE_TEMPLATE/enhancement.yml
- dbg/Makefile
- dyn_array/Makefile
The Makefiles were out of date and now the legacy_clobber rule removes
the old library filenames.
> Sync dbg and dyn_array from repos

- .github/ISSUE_TEMPLATE/enhancement.yml
- CHANGES.md
- dbg/Makefile
- dyn_array/Makefile
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/test_jparse/Makefile
- soup/version.h
Some fixes to the jparse Makefiles had to be made and these are now
synced to this repo. These fixes include:
- Fix make clobber to remove jparse_test.log and Makefile.orig.
- Fix make legacy_clobber to remove jparse.a.
- Fix ${RM} in Makefiles to use ${Q} variable (not in make depend as it is
used in an earlier command in the multiple line commands), in some cases changed
from the wrong variable, and ${RM_V} (where this was not done).
- Do not use -r in rm in Makefiles unless removing a directory, for safety.
The MKIOCCCENTRY_REPO_VERSION was updated to reflect the CHANGES.md.
> Sync jparse/ from repo

- .github/ISSUE_TEMPLATE/enhancement.yml
- CHANGES.md
- Makefile
- dbg/Makefile
- dyn_array/Makefile
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/test_jparse/Makefile
- soup/Makefile
- soup/version.h
- test_ioccc/Makefile
The clone rules left Makefile.orig files that should be removed and they
now do (for dbg/, dyn_array/ and jparse/).
The ${RM} variable in the Makefiles that did not use ${Q} now do.
The ${RM} no longer uses -r if a directory is not being removed. This
was done in jparse/ at least and the local Makefiles but if it was done
in dbg and dyn_array repos it is not yet merged to be synced up (if it
is not committed it needs to be done).
The ${RM_V} variable is now empty by default except for dbg/ and
dyn_array as those have to be committed, merged and then synced again.
In jparse/ this was already done.
> Fixes in Makefiles

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/jparse_main.c
- jparse/jsemtblgen.c
- jparse/test_jparse/Makefile
- jparse/test_jparse/jnum_chk.c
- jparse/test_jparse/jnum_chk.h
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/jnum_gen.h
- soup/version.h
This includes a number of fixes and improvements to various tools and the Makefiles (which will possibly be implemented here too). One change not mentioned in the changelog in the jparse repo was a legacy of jparse being at one time in this repo, where the tags related rules referred to ../dbg and (incorrectly) ../dyn_alloc (should have been ../dyn_array). These references have been removed outright.
> Sync jparse/ with jparse repo

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/jparse.l
- jparse/jparse.ref.c
- jparse/json_parse.c
- jparse/json_util_README.md
- jparse/jstr_util.c
- jparse/jstr_util.h
- jparse/jstrdecode.c
- jparse/jstrencode.c
- jparse/jstrencode.h
- jparse/man/man1/jparse.1
- jparse/man/man1/jstrdecode.1
- jparse/man/man1/jstrencode.1
- jparse/run_bison.sh
- jparse/test_jparse/Makefile
- jparse/test_jparse/jstr_test.sh
- jparse/test_jparse/pr_jparse_test.c
- jparse/util.c
- jparse/util.h
- soup/version.h
Synced jparse/ from the jparse repo (https://github.com/xexyl/jparse/). This makes some important fixes to the tools jstrdecode(1) and jstrencode(1) where in jstrdecode(1) the -Q option did not work and for both the printing of everything should happen after everything is parsed (especially for the -Q option but not strictly for that reason). The pr_jparse_test tool had a bug fix as well where the -h option did not work.
> Bug fixes and enhancements in jstr{de,en}code

- CHANGES.md
- soup/is_available.sh
- soup/version.h
This script takes a single arg and exits 0 if it can be found via 'type -P', otherwise 1. If -v 1 or greater it gives either the tool's path or says it cannot be found.
This script will be used in prep.sh for a rather important enhancement to help prevent superfluous bug reports.
> Add helper script soup/is_available.sh

- CHANGES.md
- dbg/Makefile
- dyn_array/Makefile
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse.h
- jparse/json_util.c
- jparse/json_util.h
- jparse/man/man1/jparse.1
- soup/Makefile
- soup/is_available.sh
- soup/version.h
- test_ioccc/Makefile
Fix check_man Makefile rule in all Makefiles. Previously it ignored the result
which meant that prep.sh never reported a problem in a problematic man page.
The dbg and dyn_array repos need to have this fix applied and I will do
this as well.
Synced jparse repo for recent changes, which includes the above fix, a 
man page fix and a new helper function besides.
> Fix make check_man, sync jparse

- CHANGES.md
- Makefile
- chkentry.c
- chkentry.h
- jparse/CHANGES.md
- jparse/jparse_main.c
- jparse/jsemtblgen.c
- jparse/jstrdecode.c
- jparse/jstrencode.c
- jparse/test_jparse/jnum_chk.c
- jparse/test_jparse/jnum_gen.c
- jparse/test_jparse/pr_jparse_test.c
- jparse/verge.c
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/Makefile
- soup/location.h
- soup/location_main.c
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/fnamchk.c
- test_ioccc/fnamchk.h
- test_ioccc/utf8_test.c
- txzchk.c
- txzchk.h
Add FOO_BASENAME to all tools in this repo. This is used in both -V option and -h option.
The -V and -h option of all tools now show the JSON parser version. This is because it is helpful to know what parser version is linked in, especially for any bug reports. This should not normally be a problem as the copies in this repo are linked in but in case there is a problem it is now done (for some the parser is actually used so it's even more important).
Sync jparse/ from the jparse repo (https://github.com/xexyl/jparse/). The changes consist of the FOO_BASENAME changes described above for the tools in this repo. This needs to be done for the dbg repo and the dyn_array repo.
The Makefiles were updated where necessary.
> Improve -V / -h options to all tools

- FAQ.md
The three libraries found in three repos that are used by this toolkit are copied into this repo to be used so it is not required to have them. The note now clearly states that it is not required to have them installed and even if you do have them installed the Makefiles link in the mkiocccentry's copy.
> Add note about libraries in FAQ

- test_ioccc/prep.sh
For certain rules the is_available.sh script is used and if it fails the test is skipped. The tool is not used in the Makefiles (yet?) but it could be. In the case of prep.sh it's mostly for maintainers but since they are not vital tools they can allow others to proceed without having a problem (we can fix it instead).
> Add use of is_available.sh in prep.sh

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jstr_util.c
- jparse/test_jparse/is_available.sh
- jparse/test_jparse/prep.sh
- jparse/version.h
- soup/Makefile
- soup/is_available.sh
- test_ioccc/Makefile
- test_ioccc/prep.sh
Improve soup/is_available.sh to now verify that checknr(1) is reliable and if it is unreliable or cannot be found, the step is skipped in prep.sh. The original version of checknr(1) always returned 0 even with an error so this check in is_available.sh expects a non-zero value, not 0, in order to verify it works okay, as in order to make sure that it works right we construct a temporary erroneous man page.
The prep.sh here now skips check_man rule if checknr cannot be found or is unreliable.
The Makefiles (except for dbg and dyn_array as these repos do not yet have the script or the changes) have been updated to better explain the problem if is_available.sh reports non-zero.
Sync jparse from the jparse repo (https://github.com/xexyl/jparse/) with the above changes (jparse is where it …
> Improve is_available.sh - check for checknr(1)

- FAQ.md
- README.md
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jparse.tab.ref.c
- jparse/jparse.tab.ref.h
- jparse/jstrdecode.c
- jparse/sorry.tm.ca.h
- soup/README.md
- test_ioccc/README.md
The top level README.md has been greatly simplified by removing extra
details. It now only talks about using the repo to package a submission
to the IOCCC with some links to the FAQ.
The new soup/README.md file has information for those who wish to
develop for this repo: in particular requirements.
The new test_ioccc/README.md file has much of what used to be in the top
level README.md file. This includes a list of the tools in the repo, or
at least the main ones. It is possible this belongs in soup/README.md
instead.
The FAQ has been updated with some formatting fixes.
> Update README.md files - #955

- CHANGES.md
- jparse/CHANGES.md
- jparse/jstrdecode.c
- jparse/jstrdecode.h
- jparse/jstrencode.c
- jparse/jstrencode.h
- jparse/man/man1/jstrdecode.1
- jparse/man/man1/jstrencode.1
As requested this new option ignores a final newline in input for encoding/decoding. It does NOT change the JSON encoding/decoding rule that an unescaped newline is not allowed; it simply changes the mechanics of the tools. Further rules for this option are being discussed.
> Add new option -N to jstrencode and jstrdecode

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
- test_ioccc/prep.sh
Now the answers version can go in soup/version.h and the EOF marker can go in mkiocccentry.h
At the same time the test_ioccc/prep.sh had a bug fix that prevents the line of the form (regex without quotes) '^OK$' from being let in the log file.
As these were annoying bugs, especially the answers version one, it seemed worth making another pull request, but this is likely my last one until the Great Fork Merge in the other repo: though I guess we'll have to wait and 'C'. :-)
> Fix annoying answers version bug

- jparse/.gitignore
- jparse/Makefile
- jparse/json_util.c
The make clobber rule did not remove a temporary file that is part of the test suite (a recent update to it).
The .gitignore had to be updated for the same file that make clobber did not remove.
A name change of a function that happened many aeons ago was not updated in comments and now it has been updated.
> Sync jparse fixes

- .gitignore
- Makefile.example
To help the judges in integrating winning entries to the winner repo, the Makefile.example file now shows how to include alt code.
It also points out that for variables one should put a space after the '=' unless it is empty.
Disable -g3. I have a lot of experience with -g and it never works well if optimisation is enabled (and it's -O3). Also, in macOS it makes the annoying .dSYM directory.
It points out that for the try rule if the program does not need any arg you do not have to specify any.
Updated .gitignore to have '.*.sw[a-zA-Z0-9]', which was discovered as missing when I had Makefile.example open when committing.
> Update Makefile.example to make more like winners

- .github/workflows/test.yml
- test_ioccc/prep.sh
The typo was that the variable LOGFILE had no G.
The workflow now runs make bug_report. This does run make test again but it seems like a good thing to run as it can help uncover more problems that might not be noticed otherwise. The bug_report.sh script is slow but this seems like a worthy thing to do.
> Bad typo fix in prep.sh, improve test workflow

- .github/workflows/test.yml
- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse_bug_report.sh
- jparse/json_parse.c
- jparse/json_utf8.c
- jparse/json_utf8.h
- jparse/man/man1/jparse_bug_report.1
- jparse/test_jparse/prep.sh
- soup/version.h
- test_ioccc/prep.sh
Sync the jparse/ directory from [jparse
repo](https://github.com/xexyl/jparse/). This includes some important bug fixes,
especially in the make install rule that did not install a header file. Not
having this would cause a compilation error if one were to try and include
jparse/jparse.h outside this repo.
The jparse_bug_report.sh script has an improvement that will test compile a
jparse program to see if the system can link in libjparse.a, libdbg.a and
libdyn_array.a. This script is not needed for this repo though.
Some cosmetic changes were made in a jparse function as well.
> Important bug fix in jparse/Makefile

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/README.md
- jparse/jparse.l
- jparse/jparse.lex.ref.h
- jparse/jparse.ref.c
- jparse/jparse.tab.ref.c
- jparse/jparse.y
- jparse/json_parse.c
- jparse/json_utf8.h
- jparse/version.h
- soup/version.h
Sync the jparse/ directory from jparse repo
(https://github.com/xexyl/jparse/). This adds some extra sanity checks in jstrencode(1)/jstrdecode(1) and it also makes some fixes to the change in decode/encode terminology, namely to do with comments. An unused macro (after a fix) was removed. Comments were updated and improved in jparse.l and jparse.y. Regenerated parser backup files.
> Sync jparse/ - sanity checks and other fixes

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/version.h
- soup/oebxergfB.h
- soup/version.h
Synced jparse/ from the jparse repo (https://github.com/xexyl/jparse/). This includes some important bug fixes in a utility function that resulted, in debug output, invalid JSON, plus an incorrect calculation in one case.
> Important bug fix in jparse/util.c

- jparse/CHANGES.md
- jparse/jparse_utils_README.md
- jparse/json_README.md
- jparse/json_util.c
- jparse/jstrdecode.c
- jparse/jstrdecode.h
- jparse/jstrencode.c
- jparse/jstrencode.h
- jparse/man/man1/jstrdecode.1
- jparse/man/man1/jstrencode.1
- jparse/util.c
- jparse/version.h
Synced jparse/ from the jparse repo (https://github.com/xexyl/jparse/). This came from discussion on JSON debug output as well as discussion about wording. A fix in one of the man pages was also made (no longer true statement) and the man pages and utils README.md were all expanded with more details and examples.
> Improve jparse wording and debug output

- CHANGES.md
This was also meant to be in the original commit that was referred to in the last commit.
> Commit CHANGES.md

- FAQ.md
- bug_report.sh
- test_ioccc/prep.sh
Rather than assume that date(1) is at /bin/date, just use 'date'.
Minor format fixes/clarifications in FAQ.
> Somewhat important fixes in bug_report and prep

- CHANGES.md
- FAQ.md
- bug_report.sh
- chkentry.c
- mkiocccentry.c
- soup/man/man1/txzchk.1
- soup/version.h
- test_ioccc/chkentry_test.sh
- test_ioccc/fnamchk.c
- test_ioccc/man/man8/utf8_test.8
- test_ioccc/prep.sh
- test_ioccc/utf8_test.c
- txzchk.c
> Add missing option -q to txzchk

- Makefile
- bug_report.sh
- jparse/CHANGES.md
- jparse/Makefile
- jparse/jparse_bug_report.sh
- jparse/test_jparse/Makefile
- soup/Makefile
- test_ioccc/Makefile
To be more portable we cannot have install -v the default as not all install(1) implementations support it.
If one needs this functionality they can do:
make INSTALL_V=-v install
The jparse repo was synced with this change. The dbg and dyn_array repos have not been updated yet but as the Makefile does not run make install in either of those directories (or for that matter jparse) it's okay - for the moment at least.
> Disable install -v by default in install rule

- CHANGES.md
- Makefile
- jparse/CHANGES.md
- jparse/Makefile
- jparse/test_jparse/jparse_test.sh
- jparse/version.h
- soup/version.h
Fix exit code errors in jparse_test.sh.
Remove rule rebuild_jparse_err_files from top level Makefile. This rule should only be in jparse/. The reason it would cause a failure is because of argv[0] being in error messages and since in this repo jparse binary is in a subdirectory it changes the name of the program so the error files are incorrect. It might be possible to do a 'cd jparse && ...' but this is not necessary as there are no error location files in this repo itself due to precisely this reason.
Happy New Year!
> jparse related fixes

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/test_jparse/Makefile
- jparse/test_jparse/jparse_test.sh
- jparse/test_jparse/jstr_test.sh
- jparse/test_jparse/not_a_comment.sh
- jparse/test_jparse/prep.sh
- jparse/version.h
Synced jparse/ from jparse repo (https://github.com/xexyl/jparse/) with the new script not_a_comment.sh which is now used in jparse/test_jparse/prep.sh as well. Thanks Landon! Doing this also uncovered a bug in jparse/test_jparse/prep.sh: namely that shellcheck failed due to the fact the script was missing from jparse/test_jparse/Makefile (this goes all the way back to the initial import of jparse as there was no prep.sh at the time!).
> Synced jparse/ from jparse repo (script fixes)

- CHANGES.md
- README.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/version.h
- mkiocccentry.c
- soup/man/man1/mkiocccentry.1
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
Update mkiocccentry_test.sh to test the new subdirectory option of mkiocccentry, with the depth being valid and the depth being too high.
Fix regexp in error message for basename of files according to how sane_relative_path() functions.
Sync jparse/ from jparse repo (https://github.com/xexyl/jparse/) with a comment to sane_relative_path() (about regexp it enforces) and additional test cases to the util test code.
Updated FAQ about how to use mkiocccentry as well as the man page (with some details on how the mkiocccentry will copy directories now). The FAQ, guidelines and rules have to be updated in the winner repo and that'll come next unless something comes up here.
> Various updates for subdirectories in mkiocccentry

- CHANGES.md
- soup/chk_validate.c
- soup/entry_util.c
- soup/entry_util.h
- soup/version.h
Renamed test_extra_file() to better account for what it is: test_extra_filename(). Improved the function to use two char *[]s so that we don't have to have checks on each file manually in each tool that uses it, though at present only chkentry(1) uses it (it is not clear if any other tool can use it in the future but this update allows for more easily maintaining the list of filenames that must be present and that must not be present).
> Improve and rename test_extra_file()

- CHANGES.md
- soup/limit_ioccc.h
- soup/version.h
As try.alt.sh is now included as an optional file there are three optional files, not 2.
This does increase the total number of files included but as optional files are not extra files it is not a problem. Besides the new total should be 39, a prime.
> Increment OPTIONAL_SUBMISSION_FILES by 1

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
Start work on issue #1070. To not interfere with the current system and to allow others (namely Landon) to work on it too, it uses a macro: MKIOCCCENTRY_DEV. If this is defined it will require 2 args and it will not set the prog.c, remarks.md or Makefile variables as they won't exist. This means the functions that pass in those variables are not called either. The usage message is simplified for the dev version. If it is defined it will set the topdir too. Also changed the work_dir variable to workdir (in both modes). If MKIOCCCENTRY_DEV is used to compile the tool then make test WILL fail! This is because the script uses the old four mandatory arguments (and the optional files in some cases too).
Fixed a NULL pointer dereference in mkiocccentry: answers was passed to dbg() even if it was …
> Start work on #1070 and fix NULL ptr dereference

- CHANGES.md
- mkiocccentry.c
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
Add to the macro MKIOCCCENTRY_DEV so that for now it at least will run the tests on prog.c, Makefile and remarks.md and form the tarball even though it's not complete (it won't ignore the right files, it doesn't do anything with the other files etc. but this way at least the program won't fail when working on the issue).
Changed MKIOCCCENTRY_VERSION to "1.2.4 2025-01-20".
Change mkiocccentry_test.sh to not test -d as it now sets -E which causes a failure.
> More work on mkiocccentry command line enhancement

- Makefile
It did not remove the random_answers.* file(s).
> Fix make clobber for mkiocccentry -s seed/-d

- CHANGES.md
- Makefile
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/entry_util.c
- soup/entry_util.h
- soup/version.h
The function count_files() in soup/entry_util.c has been renamed to
collect_files() and it now only counts files that are valid, checking
for unsafe names, depth too deep, too long filenames and so on. If too
many files are found (it does not consider optional files or required
files yet) it is also an error. Nothing is added to a list yet.
The mkiocccentry tool has been updated to use this function, showing
debug output if -v 1. It can no longer fake the paths to prog.c,
Makefile and remarks.md so it exits 0 after the call to the
collect_files() function.  With low debug level (1) it will show what
files are collected.
Updated SOUP_VERSION to "1.1.12 2025-01-24".
Updated MKIOCCCENTRY_VERSION to "1.2.5 2025-01-24".
Sync jparse repo (https://github.com/xexyl/jparse/) to jparse/ to fix
some …
> More work on issue #1070

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/entry_util.c
- soup/version.h
- txzchk.c
The check on files being found now is done from the directory that the user specifies. This involved an enhancement to the jparse function sane_relative_path(). That enhancement allows filenames to start with "./" as when walking from "." the function prepends "./" to each filename. There very possibly will be a new enhancement/utility function required before the filenames can be written to the .info.json file but that will have to be determined later.
A memory error was fixed in the jparse function count_comps().
Updated SOUP_VERSION to "1.1.13 2025-01-26".
Updated MKIOCCCENTRY_VERSION to "1.2.6 2025-01-26". Updated TXZCHK_VERSION to "1.1.6 2025-01-26".
> More work on #1070

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/entry_util.c
- soup/entry_util.h
- soup/version.h
Rename collect_files() to collect_topdir_files(). The function now checks for prog.c, Makefile and remarks.md, running the checks on them (like in the old command line interface), copying them to the work directory if all is okay. To do this it has to record the directory that the tool was run from as well as the topdir (as in file descriptor of it) as it has to switch back and forth between the directories. For the check_prog_c(), check_Makefile() and check_remarks_md() functions the filenames have to be faked: that is they have to be in the form: topdir/prog.c, topdir/Makefile and topdir/remarks.md.
For now the code also allows one to specify extra filenames as optional args. This will change when this issue is resolved completely as only files under topdir will be copied over. Doing …
> Make more progress on #1070

- mkiocccentry.c
- soup/entry_util.c
They should not use strncasecmp() but rather strcasecmp() as otherwise a filename like try.shh would be flagged as an optional filename when it's not.
> Fix new utility is_* functions

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
Instead it now defaults to the new way but with the ability to (for now) 
specify extra files as additional args. This is not how it will remain 
but this change allows for easier development. The mkiocccentry_test.sh
script was updated to account for this. The warn_*() functions no longer
take a char const * of the file they are warning against as it's
required to be the specific names so there is no need to repeat it (plus
it's called in multiple locations and we do not always have the path).
This means that make test can work in the new way though later the script will
have to be changed again.
> Removed MKIOCCCENTRY_DEV macro

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
Sync jparse repo (https://github.com/xexyl/jparse/) to jparse/ for new utility function to check for ignored (or if desired forbidden) path components. This will be useful when traversing directories. It is currently used for this but ignored paths are still not processed (just skipped). (A new function was added to mkiocccentry.c for this too.)
Fixed bug in mkiocccentry where the max depth error was reporting the wrong depth.
Updated MKIOCCCENTRY_VERSION to "1.2.10 2025-01-31".
> New jparse util function for mkiocccentry

- .gitignore
- CHANGES.md
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/mkiocccentry_test.sh
The script ended up repeating author information (duplicate entry) and also changed author handles to wrong strings (in some cases it changed it to n). This happened because the answers() functions (changed throughout the script per test) were not updated when the -y option was added to mkiocccentry (which I added to solve another problem).
The improvement is that to make the args consistent with the mkiocccentry(1) tool itself it now uses the directories test_ioccc/workdir and test_ioccc/topdir: updating the script and the .gitignore file.
Updated MKIOCCCENTRY_TEST_VERSION to "1.0.10 2025-02-11".
> Bug fix and improvements in mkiocccentry_test.sh

- CHANGES.md
- bug_report.sh
- mkiocccentry.c
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/gen_test_JSON.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/man/man8/ioccc_test.8
- test_ioccc/mkiocccentry_test.sh
We cannot test that the file is a regular executable file because there
is no guarantee there is a path supplied and doing test -x make will
fail in most cases. Since make was used previously without a check the
removal of the check should be fine.
> Fix ioccc_test.sh for -m make

- CHANGES.md
- bug_report.sh
- test_ioccc/Makefile
- test_ioccc/gen_test_JSON.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/man/man8/ioccc_test.8
Fix test_ioccc/ioccc_test.sh to have a -m make option for those who need to
specify a path to a GNU make(1) tool. One can use this with make test by way
of:
make MAKE=/path/to/gnumake test
for example.
Fix test_ioccc/gen_test_JSON.sh to work for NetBSD (change in grep regexp).
> NetBSD fixes

- CHANGES.md
- bug_report.sh
- mkiocccentry.c
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/gen_test_JSON.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/man/man8/ioccc_test.8
Add hints to mkiocccentry when reporting files/directories/symlinks that will
not be added/made. If need_hints is false this is not done. This should help
users out so that they do not have to go to the FAQ just to find out what is
wrong.
Updated MKIOCCCENTRY_VERSION to "1.2.21 2025-02-11".
> Add hints to copy_topdir()

- CHANGES.md
- bug_report.sh
- mkiocccentry.c
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/gen_test_JSON.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/man/man8/ioccc_test.8
- test_ioccc/mkiocccentry_test.sh
Change mk_submission_dir() to use mkdir(2) with mode 0 and then use
chmod(2) with the correct modes. This should fix the issue where the directory
made has the wrong mode due to umasks like what happened with NetBSD. (This is
also how the mkdirs() function from jparse works.)
> Fix mk_submission_dir() to use mkdir() and chmod()

- CHANGES.md
- mkiocccentry.c
Important bug fixes in mkiocccentry for issue #1070, as noted below:
- There was a potential invalid pointer references in multiple places in check_submission().
- (I think) Some checks were using the wrong variables (in check_submission() in particular, again I think).
- If any file or directory in the submission directory does not exist in the topdir it is an error.
- Extra sanity checks on the three required files (prog.c, Makefile and remarks.md).
- Now all lists in the topdir must be the same as the submission directory even those that are of size 0 (like directories or extra files).
- Added function array_has_path() which append_unique_str() uses and which copy_topdir() and check_submission() use. This helps identify if a name (path) is the same type of file. For instance if in the …
> Bug fixes for issue #1070

- CHANGES.md
- mkiocccentry.c
- soup/entry_util.c
- soup/version.h
- test_ioccc/test_txzchk/bad/submit.test-1.1922598666.txt.err
- test_ioccc/test_txzchk/bad/submit.test-1.1927515344.txt.err
- test_ioccc/test_txzchk/bad/submit.test-4.9876543210.txt.err
- test_ioccc/test_txzchk/bad/submit.test-5.9876543210.txt.err
- test_ioccc/test_txzchk/bad/submit.test-6.16444111149.txt.err
- test_ioccc/test_txzchk/bad/submit.test-6.1922598666.txt.err
- test_ioccc/test_txzchk/bad/submit.test-6.1922598667.txt.err
- test_ioccc/test_txzchk/bad/submit.test-7.9876543210.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543211.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543212.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.98765432128.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543213.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543214.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543215.txt.err
- test_ioccc/test_txzchk/bad/submit.test-9.9876543219.txt.err
- txzchk.c
- txzchk.h
More sanity checks in `scan_topdir()` and `check_submission()`: make sure that a directory name is not the same as a required or optional filename. That does not mean that one couldn't have a subdirectory with that name but it cannot be in the top level of the submission directory.
Plug some holes in txzchk. This includes not checking the max depth of a directory (only total number of directories was checked), checking that a directory is not named a required/mandatory filename, certain other directory name checks and other such things. Rebuilt the test error files.
Improved is_forbidden_filename(): if it's not in the forbidden filenames list but it does start with a '.' and it's not a required filename like '.auth.json' or '.info.json' it is a forbidden filename (it is true that the …
> Plug more holes in

- .gitignore
- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
Sync jparse repo (https://github.com/xexyl/jparse/) to jparse/ for new utility functions (FTS related as well as at least one other). These FTS related ones are useful for both #1070 (which it now uses) and also the new issue #1152.  Most importantly (at this time) is that we no longer use the fts_open() and fts_read() functions directly: instead it is read_fts() which is a wrapper to it but one can call it multiple times to get the next entry in the tree.  Using this has multiple advantages which will be more fully realised once issue #1152 is being worked on (that includes possibly the new function find_file(), though theoretically #1070 could also use it - it just does not need to). The function find_file() returns the path from the directory searched so one can fopen(3) it if they …
> New util functions for #1070 and #1152

- .gitignore
- CHANGES.md
- chkentry.c
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
Added ignored filenames list option (-i foo).
Only creates the array, adds strings (if not added yet) and at the end 
frees the array. This does not interfere with the current way 
chkentry(1) works.
Man page not updated yet as more work has to be done.
> Start work on issue #1152

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
This is absolutely ESSENTIAL so that we don't have to worry about changes in file sets that would cause problems; if any file set (that we have to confirm is OK) changed the answers file would be ENTIRELY useless because the order of the answers would be different (i.e. we would need an additional line!). To be helpful if answer_yes == true (i.e. -y is used or implied) and !quiet) (i.e. -q not use) we will warn the user that we will answer yes to every question (at the beginning right after the Welcome to mkiocccentry message). We use the print macro from jparse/ rather than msg() from dbg or printf with a single check because it performs many more checks which is very important when always answering yes (perhaps the function pr() that print uses should allow a string without having to …
> Fix issue #1159 - -i answers always answers yes

- CHANGES.md
- jparse/CHANGES.md
- jparse/test_jparse/is_available.sh
- jparse/test_jparse/jparse_test.sh
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/entry_util.c
- soup/entry_util.h
- soup/is_available.sh
- soup/man/man1/mkiocccentry.1
- soup/version.h
Added -I path option to mkiocccentry(1) to ignore a path. This option can be specified more than once. The path is **under** the topdir (in other words if you have a file topdir/foo and you specify topdir as your topdir and you wish to ignore topdir/foo you would use -I foo, not -I topdir/foo). This was added because some people have files/directories in their submission directory that they do not want to submit (but do want in their directory) that would normally be included by mkiocccentry(1). This has been added to help and the man page but not the FAQ, guidelines or rules (yet).
Sync jparse repo (https://github.com/xexyl/jparse/) to jparse/ for improvements (and fixes) to some utility functions (renamed due to the improvements) (one of which is used by the new feature).
Update …
> Add -I path to mkiocccentry to ignore a path

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
Multiple fixes and enhancements in some of the jparse util functions. Updated mkiocccentry for these fixes/enhancements. Note that fts_open(3) has to have either FTS_PHYSICAL or FTS_LOGICAL so the read_fts() function (prior to calling fts_open(3)) now removes both bits and then sets the right one based on the boolean. This is why it's no longer in the options to the function call - it would be removed anyway since we can't assume what is needed (for here we want FTS_PHYSICAL but in some cases it might not be desired and there was no way to be correct otherwise).
There are other improvements and fixes as well.
Updated MKIOCCCENTRY_VERSION to "1.2.26 2025-02-16".
> Multiple fixes and enhancements in jparse

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/version.h
Various fixes and further enhancements to the find_path*() functions in jparse. One in particular will very possibly be very useful for the chkentry(1) updates but it's a useful update anyway (allows filtering file types by an enum of bits). These were synced from the jparse repo (https://github.com/xexyl/jparse/) to jparse/.
Updated MKIOCCCENTRY_VERSION to "1.2.27 2025-02-17".
> Various fixes and enhancements to find_path*()

- CHANGES.md
- mkiocccentry.c
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
Check for NULL or empty workdir and topdir prior to doing anything.
Change mkiocccentry arg count check to be exact as we no longer use extra args (though it didn't hurt to have them it might be better to be clear to the user). This required updating mkiocccentry_test.sh as well.
Updated MKIOCCCENTRY_VERSION to "1.2.29 2025-02-20". Updated MKIOCCCENTRY_TEST_VERSION to "1.0.12 2025-02-20".
> Bug fixes in mkiocccentry

- CHANGES.md
- chkentry.c
- jparse/util.c
- mkiocccentry.c
- mkiocccentry.h
Change mkiocccentry to form .auth.json and then .info.json and then run chkentry(1) on both of the files. This will changed to running it with a single arg - the topdir - but this change allows it to be easier to do once chkentry(1) has been modified to do this (part of it was done - namely that the topdir arg is there and 'set' but it's not used yet).
There was a sequenced exit code change in jparse/util.c. This will be committed 'over there' but this is not strictly a sync as it was from make seqcexit here.
> Make mkiocccentry use chkentry one time

- CHANGES.md
- mkiocccentry.c
- test_ioccc/Makefile.test
- test_ioccc/mkiocccentry_test.sh
It can be a bit confusing with all the different tests that it runs (running it numerous times where it must fail and times where it must succeed) so I added a '--' between invocations.
Previously it looked weird in that it would show that all warnings are ignored and then immediately give an error (because the depth is too deep). But before that warning it would show that one (because of 'test' mode) could not use the tarball as a submission. So this should help separate it a bit.
> Improve display of mkiocccentry_test.sh

- CHANGES.md
- FAQ.md
- chkentry.c
- mkiocccentry.c
- soup/man/man1/chkentry.1
- soup/soup.h
- soup/version.h
- test_ioccc/Makefile.test
- test_ioccc/ioccc_test.sh
- test_ioccc/mkiocccentry_test.sh
Make chkentry one-arg mode only. It now needs a topdir as the arg. More work
has to be done but now at least the topdir is obtained and processed.
Updated CHKENTRY_VERSION to "1.1.1 2025-02-20".
> Make chkentry one arg mode only

- CHANGES.md
- soup/entry_util.c
- soup/entry_util.h
- soup/version.h
Fix many debug calls in soup/entry_util.c at level medium to not reveal information about the submission. This includes GitHub handle and country code, amongst others.
> Critical fixes in soup/entry_util debug calls

- CHANGES.md
- chkentry.c
- jparse/.gitignore
- jparse/CHANGES.md
- jparse/Makefile
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/entry_util.c
- soup/man/man1/mkiocccentry.1
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
Due to what will be needed with chkentry (and also in mkiocccentry - which has been updated) some of the jparse util functions were updated and new ones were added. It cannot always be assumed that finding files should be done in a case-insensitive manner so there is a new boolean in those functions (and in one or two of the new functions). The mkiocccentry had a function that is based on one of them (array_has_path()).
The arrays in the info struct in mkiocccentry now are freed and set to NULL IFF (if and only if) they are empty. This not only allows for not checking them for NULL (except before showing the contents) but it also allows for more checks that were not previously done (some were thought of in the process of this and the below change).
Update exit codes in mkiocccentry, …
> Various improvements with mkiocccentry

- CHANGES.md
- chkentry.c
- soup/version.h
Better checks on topdir in chkentry (as in even though the pointers were checked for NULL they are now only done if topdir is a directory that can be searched).
Updated CHKENTRY_VERSION to "1.1.2 2025-02-21".
> Improve topdir checks in chkentry

- CHANGES.md
- jparse/CHANGES.md
- jparse/Makefile
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/version.h
By refactoring the FTS functions in jparse/util.c the functions are far easier to use now. A great deal of thought and effort was put into this and when the topdir is passed to chk_manifest() (which is being worked on) it will be far easier. The benefit of these changes, besides being much cleaner, simpler and it being modularised, is that if some issue is discovered or some new feature is needed (as has already happened numerous times) function calls do not have to be updated.
mkiocccentry has been updated to use the simplified interface as well.
A note: jparse/ has not been fully synced because of a change in json_sem for chkentry that is not yet complete (this was done prior to deciding to rework the FTS functions). So the CHANGES.md file and the json_sem.[ch] files committed to the …
> Significantly simplify the FTS util functions

- CHANGES.md
- chkentry.c
- jparse/CHANGES.md
- jparse/jsemtblgen.h
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/entry_util.c
- soup/version.h
Fix bug in mkiocccentry where a submission topdir which only had the three required files would abort with an error (due to list being not NULL but empty due to a typo).
Sync [jparse repo](https://github.com/xexyl/jparse/) to jparse/ for some upcoming fixes to chkentry (I thought of a loophole in a new option that was being finalised and more was discovered after this).
chkentry has had a partial fix but more needs to be done (for the loophole I thought of with the -w option). Unfortunately the other things took more time than I hoped and I cannot get it in today - and fixes and improvements to the FTS functions requires a minor update to chkentry (both in chkentry.c and soup/entry_util.c)  minor change or else it will not compile and also will likely segfault.
Updated …
> Fix #1181 and other issues

- CHANGES.md
- chkentry.c
- soup/man/man1/chkentry.1
- soup/version.h
Plug a loophole in chkentry(1) and make it do even more tests that were missing/not previously thought of. This might or might not resolve the issue entirely but it is getting close to being resolved even if it is not yet resolved.
Updated CHKENTRY_VERSION to "1.1.5 2025-02-25".
> More work on #1152

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/version.h
Updated MKIOCCCENTRY_VERSION to "1.2.34 2025-02-26".
> Remove unused arg in write_json_files()

- CHANGES.md
- chkentry.c
- mkiocccentry.c
- mkiocccentry.h
- soup/entry_util.c
- soup/entry_util.h
- soup/man/man1/chkentry.1
- soup/version.h
The tool is run on the submission directory that has the files that came  
from the topdir, not the topdir itself.
> Rename topdir -> submission_dir in chkentry

- CHANGES.md
- mkiocccentry.c
- soup/man/man1/mkiocccentry.1
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
With -i answers used, unless -Y is used, mkiocccentry now will ask you to confirm things are okay (in other words if something goes wrong that would normally be warned about, you'll get to see it).
If you need to not have this you can use the new -Y option which forces -y. This is not usually a good idea but it's required for the test script (mkiocccentry_test.sh) as it is not interactive and shouldn't be.
Updated MKIOCCCENTRY_VERSION to "1.2.35 2025-02-27". Updated MKIOCCCENTRY_TEST_VERSION to "1.0.15 2025-02-26".
> Improve -i answers to prompt for y/n questions

- CHANGES.md
- mkiocccentry.c
In particular there is a note for both workdir and topdir.
> Improve mkiocccentry usage string

- CHANGES.md
- mkiocccentry.c
- soup/version.h
The code did not explicitly check for -Y; it just used the implicit -y from -Y. That is fixed and now if not -q show a simple summary but always show the longer warning to be sure that they know. As for -Y it really ought to be used only for the test script but even -y should be used with EXTREME caution.
It is hoped this is the last update to mkiocccentry(1) prior to the soft code freeze today.
TODO: finish work on the chkentry_test.sh script.
> Fix and improve warning of -y and -Y

- CHANGES.md
- jparse/util.c
- mkiocccentry.c
- soup/version.h
- test_ioccc/chkentry_test.sh
It appears that this was not done or something went wrong when doing so
(as running make seqcexit updated the exit codes and this comes from
after running it in jparse/ and committing and then syncing from
jparse to jparse/).
Also as an update to the previous commit with the minor fix and
improvement to mkiocccentry -y and -Y warnings, I meant to update the
MKIOCCCENTRY_VERSION in the CHANGES.md; it is now "1.2.36 2025-02-28".
> Resequence exit codes in jparse/util

- .gitignore
- CHANGES.md
- Makefile
- chkentry.c
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/Makefile
- soup/version.h
- test_ioccc/Makefile
- test_ioccc/chkentry_test.sh
- txzchk.c
Add extra sanity checks in check_submission_dir(): it now checks towards the beginning if the required files exist (that is, the three user submitted files, not the JSON file as those don't exist yet, though it does check that they do not exist as dot files here would be an error) and are readable and if they are not size 0 (for Makefile and remarks.md - prog.c may be empty).
Updated some literal strings of the three required filenames (as above) to their macros in both mkiocccentry and txzchk.
Fixes in chkentry with checking if files exist or do not exist (depending on options) and also add checks for file sizes for certain files, namely Makefile, remarks.md (in non-winning mode) as well as index.html (in winning mode) and README.md (in winning mode).
Error messages were improved in …
> Additional fixes and updates to various tools

- CHANGES.md
- chkentry.c
- jparse/CHANGES.md
- jparse/util.h
- soup/version.h
- test_ioccc/chkentry_test.sh
- test_ioccc/hostchk.sh
- test_ioccc/ioccc_test.sh
- test_ioccc/iocccsize_test.sh
- test_ioccc/mkiocccentry_test.sh
- test_ioccc/prep.sh
- test_ioccc/txzchk_test.sh
Ahead of the code freeze 🧊 some final fixes have been made.
chkentry now looks for directories that are the wrong permissions as well as directories with a depth beyond the max as well as any type of file other than a regular file or directory.
Bug fix an enum in jparse which caused a util function (used in the above fix to chkentry) to fail.
Updated SOUP_VERSION "2.0.0 2025-02-28".
Updated MKIOCCCENTRY_VERSION to "2.0.0 2025-02-28". Updated FNAMCHK_VERSION to "2.0.0 2025-02-28".
Updated TXZCHK_VERSION to "2.0.0 2025-02-28".
Updated CHKENTRY_VERSION to "2.0.0 2025-02-28".
Updated the version of test_ioccc/chkentry_test.sh, test_ioccc/hostchk.sh, test_ioccc/ioccc_test.sh, test_ioccc/iocccsize_test.sh, test_ioccc/mkiocccentry_test.sh, test_ioccc/prep.sh and test_ioccc/txzchk_test.sh to …
> Various important fixes and updates

- CHANGES.md
- chkentry.c
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/entry_util.c
- soup/entry_util.h
- soup/man/man1/chkentry.1
- soup/version.h
- txzchk.c
Fix a number of bugs in `chkentry(1)` and add new option to ignore permissions of files and directories (`-P`). This option is only meant for the judges and just like with `-i` and `-w` using it when verifying a submission puts one at grave risk of violating the rules; it is not even documented outside the usage message and the man page.
Fix display issues in `mkiocccentry(1)` and `chkentry(1)` with regards to file permissions.
The above fixes required updates to the jparse utility functions so the [jparse repo](https://github.com/xexyl/jparse/) was synced to `jparse/`.
Fix `chdir(2)` error in `chkentry(1)` in some places (it did not restore the directory after a call to `find_paths()`).
Updated `SOUP_VERSION` to `"2.0.1 2025-03-02"`.
Updated `MKIOCCCENTRY_VERSION` to `"2.0.1 …
> Resolve issue #1201.

- CHANGES.md
- chkentry.c
- jparse/CHANGES.md
- jparse/util.c
- soup/version.h
- txzchk.c
This might be important in some cases as we're now at the point of the next contest. The calls are specific to the functions popen(3) in pipe_open() and system(3) in shell_cmd(). In linux in some cases popen() will set errno; in macOS it is unreliable. For system(3) it appears that errno is not set so warnp()/errp() were changed to the non-errno versions.
Updated TXZCHK_VERSION to "2.0.1 2025-03-02".
> Add missing calls to errp() in txzchk

- CHANGES.md
- jparse/.gitignore
- jparse/CHANGES.md
- jparse/Makefile
- jparse/util.c
- jparse/verge.c
- jparse/verge.h
- jparse/verge_main.c
- jparse/version.h
- soup/Makefile
- soup/chk_validate.c
- soup/entry_util.c
- soup/entry_util.h
- soup/version.h
- test_ioccc/gen_test_JSON.sh
Now the version checks for chkentry(1) are a >= check. Uses code from jparse/verge.c. Its main() was moved to verge_main.c and verge.c now has a new function vercmp(). 'verge.o' is linked into the library and chkentry now uses it. Also there are new arrays that we called 'poisoned versions' and this allows for bad versions to be excluded. Each tool and some other versions have a minimum version allowed which at this time is equivalent to the current release. If a version is incremented then the minimum version would be changed to be the version at the time the contest opens. In this way uploaded submissions will not be invalidated. As for poisoned versions the lists are currently empty (just NULL terminated - must be last element).
Updated gen_test_JSON.sh (under test_ioccc/) to have a …
> Resolve issues #1215

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/chk_validate.c
- soup/man/man1/mkiocccentry.1
- soup/version.h
Resolve issue #1206. Some people wanted this option to submit multiple submissions without having to repeatedly copy/paste the UUID. Now they can just put the UUID in a text file and use -u uuid. If the file is not a regular readable file or it does not have a valid UUID it'll prompt like before. If the -i answers flag is used it is not relevant.
Resolve issue #1210. The directory/file lists to be ignored prompting was confusing to some people. The question of 'Is this OK?' was reworded to 'Do you wish to continue?' and the explanation is hopefully a bit clearer too.
Resolve issue #1221. Removed the check for first rule is all (in Makefiles).  This allows one to also have earlier on the format of 'CC:= cc' rather than just 'CC= cc', should they wish. The .info.json file still has this …
> Resolve some (mostly top priority) issues

- CHANGES.md
- iocccsize.c
- mkiocccentry.c
- mkiocccentry.h
- soup/chk_validate.c
- soup/man/man1/mkiocccentry.1
- soup/rule_count.c
- soup/version.h
With guidance from @SirWumpus and Landon, and at their request, the
iocccsize tool no longer warns against wordbuf warning unless verbosity
is high enough; in mkiocccentry it sets the boolean to true or false
depending on the result but it only notes it as a fun fact, suggesting
the user note it in their remarks. Post IOCCC28 the bool will be removed
from .info.json and chkentry(1) functions for it will be removed. For
now the function that checks this value in chkentry(1) simply returns
true. Additionally, the wrong variable was being referenced in
soup/rule_count.c - it was referencing counts.wordbuf_warning when
it should have been referencing counts.ungetc_error. Also, because
rule 13 no longer restricts UTF the char warning is only shown if
verbose enough. This did not need to be …
> Resolve issue #1214

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/man/man1/mkiocccentry.1
- soup/version.h
Also fixed an error with -u uuidfile where it would not set the test boolean to true if the UUID was "true".
The -u uuidfile and -U UUID options may not be used with -i answers, -d or -s seed.
Updated man page for the above changes.
**IMPORTANT NOTE**: you do NOT need to use this update in order to participate in the IOCCC28!
> Add -U UUID option - resolve #1229

- CHANGES.md
- mkiocccentry.c
- mkiocccentry.h
- soup/man/man1/mkiocccentry.1
- soup/sanity.c
- soup/sanity.h
- soup/soup.h
- soup/version.h
- txzchk.c
The -x option to force delete the submission directory and -r
rm option to set path to rm(1) were added to mkiocccentry as part of
issue #1208. The change in order of args is NOT done and will not be
done until AFTER IOCCC28.
Fixed bug where overwrite_answers was always true by default
(mkiocccentry).
> Partial fix to issue #1208

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/verge.c
- jparse/version.h
- mkiocccentry.c
- mkiocccentry.h
- soup/man/man1/mkiocccentry.1
- soup/sanity.c
- soup/sanity.h
- soup/soup.h
- soup/version.h
- test_ioccc/mkiocccentry_test.sh
- txzchk.c
Both mkiocccentry and txzchk (the only ones that use other tools) now 
search $PATH for the tools first by way of the find_utils() function
(modified a fair bit) and a new util function in jparse called 
resolve_path(). The jparse util functions shell_cmd() and pipe_open()
were also improved to resolve paths if no / is in the command name. As
for make: we now search for gmake first as the Makefiles we need are GNU
Makefiles.
> Resolved issues #1233 and #1218

- CHANGES.md
- soup/version.h
This is so the guidelines and FAQ can note the useful recent updates. This will NOT invalidate any submission already uploaded and you do NOT need to update the tools to upload new submissions. These updates are helpful but they are NOT required.
> Updated version of chkentry, mkiocccentry, txzchk

- CHANGES.md
- mkiocccentry.c
- soup/man/man1/txzchk.1
- soup/version.h
mkiocccentry must run make clobber before scanning the topdir and then 
also later when running the checks. This is because if someone tests
their code in their topdir anything compiled will be included as extra
files (unless forbidden) but if the make clobber that follows removes
any of those files the extra files list will be the wrong size. So now
one can test from the topdir and then not have this problem.
Updated MKIOCCCENTRY_VERSION to "2.0.5 2025-04-25".
> Fix issue #1252

- CHANGES.md
- mkiocccentry.c
- soup/version.h
Fix annoying bug where -i answers would warn about using the answer yes option.
Make it an error if the answers file used is in the topdir.
> Minor fixes in mkiocccentry

- CHANGES.md
- chkentry.c
- soup/version.h
Add temporary workaround for issue #1258. It might be that the real fix involves an update to a jparse routine but during the IOCCC28 itself that is not going to be looked at and it is arguable it is not even a good idea to do that anyway.  Instead for the time being in the problematic code an extra check is done with another FTS related routine I had written last year (I guess) in jparse. An XXX comment was added to chkentry.c but it might be (unsure as this was done quickly) that a fix in jparse/util.c has to be done instead. That's TBD later on.
Updated CHKENTRY_VERSION to "2.0.4 2025-05-02".
> Add temporary workaround for issue #1258

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/version.h
- txzchk.c
When -Y is used, don't show warnings even if -i answers is used as that
was the point of it (one should use this with caution as it answers yes
to every question automatically). It is unclear if this should show the
list of files/directories to be copied (showing the contents of the
tarball is part of txzchk's algorithm so this is unrelated) as it
currently does.  It is also unclear if the use of -Y should show
warnings but just not confirm. Given that one is just an informational
notice and that one does say something (at least if the function is
called) it might be better to always show but that really depends on
what other people want (the point of -Y in any case is to always answer
yes even when the answers file is used, as some people do in fact want
this).
Updated …
> Fixes in -i answers with -Y

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/version.h
- test_ioccc/Makefile
- txzchk.c
Don't install prep.sh or hostchk.sh. The uninstall rule still removes these
files to clean out systems which had this problem. Assuming all is already
compiled one could do: 
sudo make uninstall install 
to clean up their system.
Otherwise one should do: 
make; sudo make uninstall install 
as trying to compile the tools with root will cause problems when
trying to run make again (due to ownership change).
> Don't install prep.sh or hostchk.sh - #1219

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/Makefile
- soup/entry_util.c
- soup/entry_util.h
- soup/location.h
- soup/location_main.c
- soup/location_tbl.c
- soup/location_util.c
- soup/version.h
- test_ioccc/Makefile
- txzchk.c
It might be worth noting that if one has an ignored directory name as a
file that it appears to not warn about it even though it will (it
appears as well) ignore it. It is unclear to me if this should be
changed or not.
It would seem that both chkentry and txzchk have this problem as well. A
new issue for each will be opened to be resolved before IOCCC29.
> Resolve issue #1207 - ignore SCCS and RCS

- CHANGES.md
- jparse/CHANGES.md
- jparse/util.c
- jparse/util.h
- jparse/version.h
- mkiocccentry.c
- soup/Makefile
- soup/entry_util.c
- soup/entry_util.h
- soup/location.h
- soup/location_main.c
- soup/location_tbl.c
- soup/location_util.c
- soup/version.h
- test_ioccc/Makefile
- txzchk.c
Added support of globs with the mkiocccentry ignore option (-I). This 
involves syncing jparse/ from the jparse repo. It would appear that
GitHub changed something with workflows so this might fail the workflow 
check. If so that might require a new issue or looking at later. In any
case make prep works fine even if it does fail the workflow (it is not
clear to me if it's due to the dependencies but the last commit to
jparse worked fine and the build steps did not change at all).
Updated MKIOCCCENTRY_VERSION to "2.0.10 2025-06-19".
> Support globs in mkiocccentry ignore option

- CHANGES.md
- jparse/CHANGES.md
- jparse/test_jparse/Makefile
- jparse/verge.h
- jparse/version.h
The CHANGES.md file got overwritten from the jparse repo.
Synced jparse repo (https://github.com/xexyl/jparse) and fixed make depend. It is not clear if this is the case but perhaps the following command was not run:
make jparse.recreate_clone jparse.update_from_clone
which properly runs make depend for this repo.
> Restore overwritten files and fix make depend

- CHANGES.md
- soup/version.h
- test_ioccc/test_file_util.c
Make adjustments to the new test_file_util.c so that it will function in cases where someone has a file called foobar in their directory (this would be me as I use it as part of testing mkiocccentry).
A man page was started but not added yet because the exit codes in the test code need to be fixed first and that cannot happen now.
Updated FILE_UTIL_TEST_VERSION to "2.0.1 2025-09-04".
> Make adjustments to new test_file_util

- CHANGES.md
- jparse/CHANGES.md
- jparse/jparse_main.c
- jparse/man/man1/jparse.1
- jparse/test_jparse/test_JSON/bad_loc/12345678-1234-4321-abcd-1234567890ab-2-auth.json.err
- jparse/test_jparse/test_JSON/bad_loc/12345678-1234-4321-abcd-1234567890ab-2-info.json.err
- jparse/test_jparse/test_JSON/bad_loc/braces-comma-eof.json.err
- jparse/test_jparse/test_JSON/bad_loc/first-line-first-column-comma-eof.json.err
- jparse/test_jparse/test_JSON/bad_loc/open-brace-unbalanced-quotes-comma.json.err
- jparse/test_jparse/test_JSON/bad_loc/open-brace-value-comma.json.err
- jparse/test_jparse/test_JSON/bad_loc/open-brace.json.err
- jparse/test_jparse/test_JSON/bad_loc/party.json.err
- jparse/test_jparse/test_JSON/bad_loc/second-line-first-column-comma-eof.json.err
- jparse/test_jparse/test_JSON/bad_loc/second-line-second-column-comma.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-0-auth.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-0-info.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-1-auth.json.err
- jparse/test_jparse/test_JSON/bad_loc/test-1-info.json.err
- jparse/test_jparse/test_JSON/bad_loc/unquoted-name.json.err
- jparse/test_jparse/test_JSON/bad_loc/vtab_comma.json.err
- jparse/version.h
- soup/version.h
Synced jparse repo (https://github.com/xexyl/jparse) with an enhancement to the jparse(1) tool. This updates the JPARSE_TOOL_VERSION to "2.0.2 2025-09-09".
REMINDER: you do NOT have to install the external libraries from their respective repo in order to use or install this toolkit. Neither do you have to install this toolkit although you are strongly recommended to do so.
> Sync jparse/ from jparse repo - improve jparse(1)

- CHANGES.md
- soup/version.h
- test_ioccc/hostchk.sh
Fix bug in test_ioccc/hostchk.sh where if you did not have dbg and dyn_array installed it would fail as it was looking for new include files. It appears that this did not happen with jparse not being installed but if anyone has an issue (I did a make uninstall but it's possible I missed something) **PLEASE** report it.
Updated HOSTCHK_VERSION to "2.0.2 2025-09-18".
> Fix bug in hostchk.sh wrt dbg/dyn_array updates

- CHANGES.md
- Makefile
- chksubmit.h
- jparse/util.c
- jparse/util.h
- mkiocccentry.h
- soup/Makefile
- soup/entry_util.c
- soup/entry_util.h
- soup/file_util.c
- soup/file_util.h
- soup/util.c
- soup/util.h
- soup/version.h
- txzchk.h
Moved some functions and macros from soup/file_util.[ch] to soup/util.[ch] as they are not strictly file related. This was arbitrarily done although most of the functions that are not strictly file related, if not all, have been moved.
Synced jparse/. This included an important fix for the above which caused all sorts of problems - and if some functions or macros that are not in soup/util.[ch] when they should be (but are instead in soup/file_util.[ch]) this is why.
Updated SOUP_VERSION to "2.0.8 2025-09-21".
> Added soup/util.[ch]
